"""
Agentql Api MCP Server - Pydantic Models

Generated: 2026-03-24 23:33:10 UTC
@generated by MCP Blacksmith (https://mcpblacksmith.com)
"""

from __future__ import annotations

from typing import Literal

from _validators import PermissiveModel, StrictModel
from pydantic import Field

__all__ = [
    "CreateSessionTetraSessionsPostRequest",
    "CreateSessionV1TetraSessionsPostRequest",
    "GetUsageUsageGetRequest",
    "GetUsageV1UsageGetRequest",
    "ListSessionUsageTetraUsageGetRequest",
    "ListSessionUsageV1TetraUsageGetRequest",
    "QueryDataServiceQueryDataPostRequest",
    "QueryDataServiceV1QueryDataPostRequest",
    "BrowserRequest",
    "CustomProxy",
    "TetraProxy",
]

# ============================================================================
# Request Models
# ============================================================================

# Operation: query_webpage_data
class QueryDataServiceV1QueryDataPostRequestHeader(StrictModel):
    content_type: str = Field(default=..., validation_alias="content-type", serialization_alias="content-type", description="MIME type of the request body, required for proper request parsing.")
class QueryDataServiceV1QueryDataPostRequestBodyParams(StrictModel):
    mode: Literal["fast", "standard"] | None = Field(default=None, validation_alias="mode", serialization_alias="mode", description="Controls the response extraction mode. Use 'fast' for lower latency with standard accuracy, or 'standard' for higher accuracy at the cost of speed.")
    wait_for: int | None = Field(default=None, validation_alias="wait_for", serialization_alias="wait_for", description="Number of seconds to wait for dynamic page content to finish loading before capturing the snapshot. Maximum allowed wait time is 10 seconds.")
    is_scroll_to_bottom_enabled: bool | None = Field(default=None, validation_alias="is_scroll_to_bottom_enabled", serialization_alias="is_scroll_to_bottom_enabled", description="When enabled, the browser will scroll to the bottom of the page before capturing the snapshot, ensuring lazy-loaded content is included.")
    is_screenshot_enabled: bool | None = Field(default=None, validation_alias="is_screenshot_enabled", serialization_alias="is_screenshot_enabled", description="When enabled, a screenshot of the page is captured during the query session and included in the response.")
    browser_profile: Literal["light", "stealth", "tf-browser"] | None = Field(default=None, validation_alias="browser_profile", serialization_alias="browser_profile", description="Determines the browser profile used for the session. Use 'light' for fast headless browsing, 'stealth' for anti-bot-detection evasion, or 'tf-browser' for a specialized browser environment.")
    proxy: TetraProxy | CustomProxy | None = Field(default=None, validation_alias="proxy", serialization_alias="proxy", description="Proxy configuration object for routing the browser session through a specified proxy server, useful for geo-restricted or access-controlled pages.")
class QueryDataServiceV1QueryDataPostRequestBody(StrictModel):
    query: str | None = Field(default=None, description="An AgentQL (AQL) query string specifying the data fields to extract from the page. If omitted, a query will be auto-generated from the prompt.")
    prompt: str | None = Field(default=None, description="A natural language description of the data to extract, used to auto-generate an AgentQL query when no explicit query is provided.")
    url: str | None = Field(default=None, description="The fully qualified URL of the webpage to load and query. Either url or html must be provided.")
    html: str | None = Field(default=None, description="Raw HTML content of the webpage to query, used as an alternative to providing a live URL.")
    params: QueryDataServiceV1QueryDataPostRequestBodyParams | None = None
class QueryDataServiceV1QueryDataPostRequest(StrictModel):
    """Extract structured data from a webpage using an AgentQL query or a natural language prompt. Accepts either a live URL or raw HTML as the data source."""
    header: QueryDataServiceV1QueryDataPostRequestHeader
    body: QueryDataServiceV1QueryDataPostRequestBody | None = None

# Operation: get_usage_v1_usage_get
class GetUsageV1UsageGetRequest(StrictModel):
    """Get Usage"""

# Operation: create_browser_session_v1
class CreateSessionV1TetraSessionsPostRequestBody(StrictModel):
    body: BrowserRequest | None = Field(default=None, description="Optional configuration object for customizing the browser session, such as viewport settings, user agent, proxy configuration, or other session-level browser options.")
class CreateSessionV1TetraSessionsPostRequest(StrictModel):
    """Creates a new Tetra browser session, initializing a managed browser environment for automated interaction. Returns session details needed to reference and control the session in subsequent operations."""
    body: CreateSessionV1TetraSessionsPostRequestBody | None = None

# Operation: list_session_usage_v1
class ListSessionUsageV1TetraUsageGetRequestQuery(StrictModel):
    sub_user_id: str | None = Field(default=None, description="Filter results to only include usage records associated with a specific sub-user ID.")
    session_id: str | None = Field(default=None, description="Filter results to only include usage records for a specific browser session ID.")
    start_after: str | None = Field(default=None, description="Return only records that start after this timestamp, enabling time-range filtering. Accepts an ISO 8601 formatted datetime string.")
    end_before: str | None = Field(default=None, description="Return only records that end before this timestamp, enabling time-range filtering. Accepts an ISO 8601 formatted datetime string.")
    status: Literal["running", "ended"] | None = Field(default=None, description="Filter results by session status, limiting records to those matching the specified state.")
    limit: int | None = Field(default=None, description="Maximum number of usage records to return per page. Accepts a value between 1 and 1000.", ge=1, le=1000)
    page: int | None = Field(default=None, description="Page number to retrieve for paginated results, starting at page 1.", ge=1)
class ListSessionUsageV1TetraUsageGetRequest(StrictModel):
    """Retrieve a paginated list of Tetra browser session usage records for the authenticated user, with optional filtering by user, session, time range, and status."""
    query: ListSessionUsageV1TetraUsageGetRequestQuery | None = None

# Operation: query_webpage_data_legacy
class QueryDataServiceQueryDataPostRequestHeader(StrictModel):
    content_type: str = Field(default=..., validation_alias="content-type", serialization_alias="content-type", description="MIME type of the request body, required for proper request parsing.")
class QueryDataServiceQueryDataPostRequestBodyParams(StrictModel):
    mode: Literal["fast", "standard"] | None = Field(default=None, validation_alias="mode", serialization_alias="mode", description="Controls the speed and thoroughness of the query response. Use 'fast' for lower latency and 'standard' for more thorough extraction.")
    wait_for: int | None = Field(default=None, validation_alias="wait_for", serialization_alias="wait_for", description="Number of seconds to wait for dynamic page content to load before capturing the snapshot. Maximum allowed wait time is 10 seconds.")
    is_scroll_to_bottom_enabled: bool | None = Field(default=None, validation_alias="is_scroll_to_bottom_enabled", serialization_alias="is_scroll_to_bottom_enabled", description="When enabled, the browser will scroll to the bottom of the page before capturing the snapshot, useful for triggering lazy-loaded content.")
    is_screenshot_enabled: bool | None = Field(default=None, validation_alias="is_screenshot_enabled", serialization_alias="is_screenshot_enabled", description="When enabled, a screenshot of the page is captured during the query session, which can aid in debugging or visual verification.")
    browser_profile: Literal["light", "stealth", "tf-browser"] | None = Field(default=None, validation_alias="browser_profile", serialization_alias="browser_profile", description="Determines the browser profile used for the session. Use 'light' for fast headless browsing, 'stealth' to bypass bot-detection mechanisms, or 'tf-browser' for specialized browser environments.")
    proxy: TetraProxy | CustomProxy | None = Field(default=None, validation_alias="proxy", serialization_alias="proxy", description="Optional proxy configuration to route the browser session through a specific proxy server, useful for geo-restricted or access-controlled pages.")
class QueryDataServiceQueryDataPostRequestBody(StrictModel):
    query: str | None = Field(default=None, description="An AgentQL (AQL) query string specifying the exact data fields to extract from the page. If omitted, a query will be auto-generated from the provided prompt.")
    prompt: str | None = Field(default=None, description="A natural language description of the data to extract, used to auto-generate an AgentQL query when no explicit query is provided.")
    url: str | None = Field(default=None, description="The fully qualified URL of the webpage to load and query. Either this or html must be provided as the data source.")
    html: str | None = Field(default=None, description="Raw HTML content of the webpage to query, used as an alternative to providing a live URL.")
    params: QueryDataServiceQueryDataPostRequestBodyParams | None = None
class QueryDataServiceQueryDataPostRequest(StrictModel):
    """Extract structured data from a webpage using an AgentQL query or a natural language prompt. Accepts either a live URL or raw HTML as the data source."""
    header: QueryDataServiceQueryDataPostRequestHeader
    body: QueryDataServiceQueryDataPostRequestBody | None = None

# Operation: get_usage_usage_get
class GetUsageUsageGetRequest(StrictModel):
    """Get Usage"""

# Operation: create_browser_session
class CreateSessionTetraSessionsPostRequestBody(StrictModel):
    body: BrowserRequest | None = Field(default=None, description="Optional configuration object for customizing the browser session, such as viewport settings, browser preferences, or session-specific options.")
class CreateSessionTetraSessionsPostRequest(StrictModel):
    """Creates a new Tetra browser session, initializing a managed browser environment for automated interaction. Optionally accepts configuration to customize session behavior."""
    body: CreateSessionTetraSessionsPostRequestBody | None = None

# Operation: list_session_usage
class ListSessionUsageTetraUsageGetRequestQuery(StrictModel):
    sub_user_id: str | None = Field(default=None, description="Filter results to usage records belonging to a specific sub-user by their unique identifier.")
    session_id: str | None = Field(default=None, description="Filter results to a specific browser session by its unique session identifier.")
    start_after: str | None = Field(default=None, description="Return only records that start after this timestamp, enabling time-bounded queries. Accepts an ISO 8601 formatted datetime string.")
    end_before: str | None = Field(default=None, description="Return only records that end before this timestamp, enabling time-bounded queries. Accepts an ISO 8601 formatted datetime string.")
    status: Literal["running", "ended"] | None = Field(default=None, description="Filter results by session status to narrow results to sessions in a particular state.")
    limit: int | None = Field(default=None, description="Maximum number of usage records to return per page. Accepts a value between 1 and 1000.", ge=1, le=1000)
    page: int | None = Field(default=None, description="Page number to retrieve for paginated results, starting at page 1.", ge=1)
class ListSessionUsageTetraUsageGetRequest(StrictModel):
    """Retrieve Tetra browser session usage records for the authenticated user. Supports filtering by user, session, status, and date range with pagination."""
    query: ListSessionUsageTetraUsageGetRequestQuery | None = None

# ============================================================================
# Component Models
# ============================================================================

class CustomProxy(StrictModel):
    """Custom external proxy configuration"""
    type_: Literal["custom"] | None = Field('custom', validation_alias="type", serialization_alias="type", description="Type of proxy: 'custom' for external proxy")
    url: str = Field(..., description="Proxy server URL")
    username: str | None = Field(None, description="Username for proxy authentication")
    password: str | None = Field(None, description="Password for proxy authentication")

class TetraProxy(StrictModel):
    """Tetra built-in proxy configuration"""
    type_: Literal["tetra"] | None = Field('tetra', validation_alias="type", serialization_alias="type", description="Type of proxy: 'tetra' for built-in proxy")
    country_code: str | None = Field('US', description="Country code for tetra proxy")

class BrowserRequest(PermissiveModel):
    """Request model for browser session"""
    browser_ua_preset: Literal["windows", "macos", "linux"] | None = Field('linux', description="The user agent preset to use for the browser session")
    browser_profile: Literal["light", "stealth", "tf-browser"] | None = Field('light', description="Browser profile - 'light' for fast browsing, 'stealth' for anti-detection and full browser features, 'tf-browser' for custom TF Browser")
    shutdown_mode: Literal["on_disconnect", "on_inactivity_timeout"] | None = Field('on_disconnect', description="Controls how the browser session is torn down on disconnect. 'on_disconnect' stops immediately after there are no more active connections to the browser, 'on_inactivity_timeout' keeps alive until t...")
    inactivity_timeout_seconds: int | None = Field(300, description="The inactivity timeout in seconds (up to 24h)", ge=5, le=86400)
    proxy: TetraProxy | CustomProxy | None = Field(None, description="Proxy configuration for this browser session")
    sub_user_id: str | None = Field(None, description="Optional sub-user identifier for tracking sessions within a user account")


# Rebuild models to resolve forward references (required for circular refs)
BrowserRequest.model_rebuild()
CustomProxy.model_rebuild()
TetraProxy.model_rebuild()
