"""
Journeys Track Api MCP Server - Pydantic Models

Generated: 2026-03-28 14:14:43 UTC
@generated by MCP Blacksmith (https://mcpblacksmith.com)
"""

from __future__ import annotations

from typing import Annotated, Any, Literal

from _validators import PermissiveModel, StrictModel
from pydantic import Field

__all__ = [
    "AddDeviceRequest",
    "AddToSegmentRequest",
    "BatchRequest",
    "DeleteDeviceRequest",
    "DeleteRequest",
    "EntityRequest",
    "GetRegionRequest",
    "IdentifyRequest",
    "MergeRequest",
    "MetricsRequest",
    "RemoveFromSegmentRequest",
    "SubmitFormRequest",
    "SuppressRequest",
    "TrackAnonymousRequest",
    "TrackRequest",
    "UnsubscribeRequest",
    "UnsuppressRequest",
    "DeliveryOperations",
    "DeviceObject",
    "IdentifyBodyCioRelationshipsRelationshipsItem",
    "IdentifyPerson",
    "MergeBodyPrimaryV0",
    "MergeBodyPrimaryV1",
    "MergeBodyPrimaryV2",
    "MergeBodySecondaryV0",
    "MergeBodySecondaryV1",
    "MergeBodySecondaryV2",
    "MetricsBodyV0",
    "MetricsBodyV1",
    "MetricsBodyV2",
    "MetricsBodyV3",
    "MetricsBodyV4",
    "MetricsBodyV5",
    "ObjectAddRelationships",
    "ObjectDelete",
    "ObjectDeleteRelationships",
    "ObjectIdentify",
    "ObjectIdentifyAnonymous",
    "ObjectOperations",
    "PersonAddDevice",
    "PersonAddRelationships",
    "PersonDelete",
    "PersonDeleteDevice",
    "PersonDeleteRelationships",
    "PersonEvent",
    "PersonMerge",
    "PersonOperations",
    "PersonPage",
    "PersonScreen",
    "PersonSuppress",
    "PersonUnsuppress",
    "SubmitFormBodyDataV0",
    "SubmitFormBodyDataV1",
    "TrackAnonymousBodyV0",
    "TrackAnonymousBodyV1",
    "TrackAnonymousBodyV2",
    "TrackBodyV0",
    "TrackBodyV1",
    "TrackBodyV2",
]

# ============================================================================
# Request Models
# ============================================================================

# Operation: get_account_region
class GetRegionRequest(StrictModel):
    """Retrieve your account's region and environment details. This endpoint returns the appropriate regional URL and environment ID for your Track API credentials, which you should use for all subsequent API requests."""

# Operation: upsert_customer
class IdentifyRequestPath(StrictModel):
    identifier: str = Field(default=..., description="The unique identifier for the customer, such as an id, email address, or cio_id (prefixed with 'cio_'). The identifier type depends on your workspace configuration.")
class IdentifyRequestBodyCioRelationships(StrictModel):
    action: Literal["add_relationships", "delete_relationships"] | None = Field(default=None, validation_alias="action", serialization_alias="action", description="Specifies whether to add new relationships to the customer or remove existing relationships.")
    relationships: list[IdentifyBodyCioRelationshipsRelationshipsItem] | None = Field(default=None, validation_alias="relationships", serialization_alias="relationships", description="An array of relationship objects to add to or remove from the customer, determined by the action parameter.")
class IdentifyRequestBodyCioSubscriptionPreferences(StrictModel):
    topics: dict[str, bool] | None = Field(default=None, validation_alias="topics", serialization_alias="topics", description="An object containing topic subscription states for active topics in your workspace, with keys formatted as 'topic_<id>'.")
class IdentifyRequestBody(StrictModel):
    update: bool | None = Field(default=None, validation_alias="_update", serialization_alias="_update", description="Set to true to prevent duplicate profile creation when making rapid successive requests. If enabled and the identifier is not found, the request will fail with a Failed Attribute Change event rather than creating a new profile.")
    unsubscribed: bool | None = Field(default=None, description="Set to true to unsubscribe the customer from all messages. When false or omitted, the customer's subscription status is determined by their subscription preferences. Accepts true, TRUE, 1, or '1' for unsubscribed; all other values are treated as subscribed.")
    cio_relationships: IdentifyRequestBodyCioRelationships | None = None
    cio_subscription_preferences: IdentifyRequestBodyCioSubscriptionPreferences | None = None
class IdentifyRequest(StrictModel):
    """Add a new customer or update an existing customer's profile and attributes. Intelligently handles identifier resolution, including merging profiles when necessary, and supports relationship and subscription preference management."""
    path: IdentifyRequestPath
    body: IdentifyRequestBody | None = None

# Operation: delete_customer
class DeleteRequestPath(StrictModel):
    identifier: str = Field(default=..., description="The unique identifier for the customer to delete. This can be a customer ID, email address, or cio_id (prefixed with 'cio_') depending on your workspace configuration.")
class DeleteRequest(StrictModel):
    """Permanently remove a customer and all associated information from Customer.io. Note that customers recreated through other integration methods (such as the JavaScript snippet) after deletion may need to be deleted again."""
    path: DeleteRequestPath

# Operation: register_device
class AddDeviceRequestPath(StrictModel):
    identifier: str = Field(default=..., description="The unique identifier for the customer. This can be their user ID, email address, or CIO ID (prefixed with `cio_`) depending on your workspace configuration.")
class AddDeviceRequestBody(StrictModel):
    device: DeviceObject | None = Field(default=None, description="An object containing the device properties to register or update. Properties are automatically collected by SDKs unless disabled, and can be referenced in segments and Liquid templates.")
class AddDeviceRequest(StrictModel):
    """Register or update a device for a customer. Customers can have multiple devices; use this operation to add or modify iOS and Android devices in a customer profile."""
    path: AddDeviceRequestPath
    body: AddDeviceRequestBody | None = None

# Operation: remove_device
class DeleteDeviceRequestPath(StrictModel):
    identifier: str = Field(default=..., description="The unique identifier for the customer. This can be their user ID, email address, or Customer.io ID (prefixed with `cio_`).")
    device_id: str = Field(default=..., description="The unique identifier of the device to remove from the customer profile.")
class DeleteDeviceRequest(StrictModel):
    """Remove a device from a customer profile. Ensure you stop sending device data to Customer.io to prevent the device from being automatically re-added."""
    path: DeleteDeviceRequestPath

# Operation: suppress_customer
class SuppressRequestPath(StrictModel):
    identifier: str = Field(default=..., description="The unique identifier for the customer to suppress. This can be an email address, customer ID, or CIO ID (prefixed with `cio_`), depending on your workspace configuration. The suppressed identifier cannot be re-added until explicitly unsuppressed.")
class SuppressRequest(StrictModel):
    """Permanently delete a customer profile and suppress their identifier(s) to prevent re-addition to the workspace. All future API calls referencing the suppressed identifier are ignored. This action cannot be undone and should be used primarily for GDPR/CCPA compliance requests."""
    path: SuppressRequestPath

# Operation: unsuppress_customer
class UnsuppressRequestPath(StrictModel):
    identifier: str = Field(default=..., description="The unique identifier for the customer, which can be their ID, email address, or cio_id (prefixed with 'cio_'). The accepted identifier type depends on your workspace configuration.")
class UnsuppressRequest(StrictModel):
    """Reactivate a suppressed customer profile to make their identifier available for new profile creation. Unsuppressing does not restore the previous profile history; it only makes the identifier usable again."""
    path: UnsuppressRequestPath

# Operation: mark_delivery_unsubscribed
class UnsubscribeRequestPath(StrictModel):
    delivery_id: str = Field(default=..., description="The unique identifier of the email delivery associated with the unsubscribe request.")
class UnsubscribeRequestBody(StrictModel):
    unsubscribe: bool | None = Field(default=None, description="Set to true to mark the person as unsubscribed and attribute the unsubscribe action to this delivery.")
class UnsubscribeRequest(StrictModel):
    """Mark a person as unsubscribed from a specific email delivery. Use this endpoint with custom unsubscribe pages to record unsubscribe requests and trigger email_unsubscribed events for audience segmentation."""
    path: UnsubscribeRequestPath
    body: UnsubscribeRequestBody | None = None

# Operation: track_customer_event
class TrackRequestPath(StrictModel):
    identifier: str = Field(default=..., description="The unique identifier for the customer. Can be the customer's ID, email address, or CIO ID depending on workspace configuration.")
class TrackRequestBody(StrictModel):
    body: TrackBodyV0 | TrackBodyV1 | TrackBodyV2 | None = Field(default=None, description="Event payload containing the event type (page, screen, or event), event name, and optional properties. Reserved properties (from_address, recipient, reply_to) will override campaign settings if present.")
class TrackRequest(StrictModel):
    """Record a customer event (page view, screen view, or custom event) associated with a person. Events are automatically trimmed of leading and trailing whitespace, and certain reserved properties can override campaign settings."""
    path: TrackRequestPath
    body: TrackRequestBody | None = None

# Operation: log_anonymous_event
class TrackAnonymousRequestBody(StrictModel):
    body: TrackAnonymousBodyV0 | TrackAnonymousBodyV1 | TrackAnonymousBodyV2 | None = Field(default=None, description="Event data for an anonymous user. Include an `anonymous_id` to enable later association with an identified person. Supports three event types: `page` (website views), `screen` (mobile app views), or `event` (custom events). Event names should not have leading or trailing spaces.")
class TrackAnonymousRequest(StrictModel):
    """Log an event for an unidentified person using an anonymous ID. Events can be associated with a person later when their identity is confirmed, enabling campaign triggers within 72 hours of the event timestamp."""
    body: TrackAnonymousRequestBody | None = None

# Operation: submit_form
class SubmitFormRequestPath(StrictModel):
    form_id: str = Field(default=..., description="Unique identifier for the form. Use a value that is meaningful to your system and traceable to your backend. If Customer.io does not recognize this identifier, a new form connection will be created automatically.")
class SubmitFormRequestBody(StrictModel):
    data: SubmitFormBodyDataV0 | SubmitFormBodyDataV1 | None = Field(default=None, description="Form submission data containing respondent information and form field responses. Must include at least one identifier (id, email, or a field mapped to an identifier) to identify or create the respondent. All form field values must be formatted as strings. Reserved keys (form_id, form_name, form_type, form_url, form_url_param) are ignored if included.")
class SubmitFormRequest(StrictModel):
    """Submit a form response and create or update the respondent in Customer.io. Form submissions are associated with a form connection; if the form_id is unrecognized, a new form connection is automatically created."""
    path: SubmitFormRequestPath
    body: SubmitFormRequestBody | None = None

# Operation: merge_customers
class MergeRequestBody(StrictModel):
    primary: MergeBodyPrimaryV0 | MergeBodyPrimaryV1 | MergeBodyPrimaryV2 | None = Field(default=None, description="The customer profile that persists after the merge. Identify by `id`, `email`, or `cio_id`. This profile receives merged attributes, event history, segments, and campaign journey data from the secondary profile. Required if email is disabled as an identifier in workspace settings.")
    secondary: MergeBodySecondaryV0 | MergeBodySecondaryV1 | MergeBodySecondaryV2 | None = Field(default=None, description="The customer profile to delete after the merge. Identify by `id`, `email`, or `cio_id`. This profile's data (attributes, events, segments, and journeys) is consolidated into the primary profile before deletion. Required if email is disabled as an identifier in workspace settings.")
class MergeRequest(StrictModel):
    """Merge two customer profiles by consolidating the secondary profile into the primary profile, then deleting the secondary. The primary profile must already exist to prevent race conditions. This operation is irreversible."""
    body: MergeRequestBody | None = None

# Operation: report_metrics
class MetricsRequestBody(StrictModel):
    body: MetricsBodyV0 | MetricsBodyV1 | MetricsBodyV2 | MetricsBodyV3 | MetricsBodyV4 | MetricsBodyV5 | None = Field(default=None, description="Metric payload containing the delivery_id (from CIO-Delivery-ID header) and associated metric data to report for tracking message performance and user interactions.")
class MetricsRequest(StrictModel):
    """Report metrics from external channels or non-SDK integrations by associating them with message deliveries. Use the CIO-Delivery-ID header value from message delivery responses as the delivery_id to track user interactions like clicks and conversions."""
    body: MetricsRequestBody | None = None

# Operation: add_customers_to_segment
class AddToSegmentRequestPath(StrictModel):
    segment_id: int = Field(default=..., description="The unique identifier of the manual segment. Find this ID in the dashboard under Segments > [Your Segment] > Usage, or retrieve it using the App API.", json_schema_extra={'format': 'int32'})
class AddToSegmentRequestBody(StrictModel):
    ids: list[str] | None = Field(default=None, description="Array of customer identifiers to add to the segment. The identifier type (ID, email, or CIO ID) is determined by the id_type query parameter. All identifiers in the array must be of the same type; mismatched entries are ignored.", min_length=1, max_length=1000)
class AddToSegmentRequest(StrictModel):
    """Add customers to a manual segment by their identifiers (ID, email, or CIO ID). You can add up to 1000 customers per request; the segment must already exist before adding customers to it."""
    path: AddToSegmentRequestPath
    body: AddToSegmentRequestBody | None = None

# Operation: remove_customers_from_segment
class RemoveFromSegmentRequestPath(StrictModel):
    segment_id: int = Field(default=..., description="The unique identifier of the segment. You can find this ID in the Segments dashboard under Usage, or retrieve it using the Segments API.", json_schema_extra={'format': 'int32'})
class RemoveFromSegmentRequestBody(StrictModel):
    ids: list[str] | None = Field(default=None, description="An array of customer IDs to remove from the segment. Each ID must correspond to a customer with an `id` attribute in your workspace.", min_length=1, max_length=1000)
class RemoveFromSegmentRequest(StrictModel):
    """Remove customers from a manual segment by their IDs. This operation supports up to 1000 customer IDs per request and requires customers to have `id` attributes defined in your workspace."""
    path: RemoveFromSegmentRequestPath
    body: RemoveFromSegmentRequestBody | None = None

# Operation: manage_entity
class EntityRequestBody(StrictModel):
    body: PersonOperations | ObjectOperations | DeliveryOperations | None = Field(default=None, description="Request payload containing entity data and operation details. Maximum payload size is 32KB.")
class EntityRequest(StrictModel):
    """Create, update, or delete a single entity (person or object) and manage relationships between entities and people. Objects can represent any non-person entity such as companies, courses, products, or custom business entities."""
    body: EntityRequestBody | None = None

# Operation: batch_entities
class BatchRequestBody(StrictModel):
    batch: list[Annotated[IdentifyPerson | PersonDelete | PersonEvent | PersonScreen | PersonPage | PersonAddRelationships | PersonDeleteRelationships | PersonAddDevice | PersonDeleteDevice | PersonMerge | PersonSuppress | PersonUnsuppress, Field(discriminator="action")] | Annotated[ObjectIdentify | ObjectIdentifyAnonymous | ObjectDelete | ObjectAddRelationships | ObjectDeleteRelationships, Field(discriminator="action")] | DeliveryOperations] | None = Field(default=None, description="Array of entity operations to process. Each object represents a single person or object modification. The batch payload must not exceed 500kb total, and each individual entity operation must not exceed 32kb. Pass as a JSON-encoded string with a \"type\" discriminator field, e.g. '{\"type\": \"value\", ...}'.")
class BatchRequest(StrictModel):
    """Submit multiple entity operations in a single request to create or modify people and objects. Mix operation types freely within a single batch request."""
    body: BatchRequestBody | None = None

# ============================================================================
# Component Models
# ============================================================================

class CioSubscriptionPreferences(PermissiveModel):
    """Stores your audience's subscription preferences if you enable our [subscription center](/subscription-center/) feature. These items are set automatically when people use the unsubscribe link in your messages, but you can set preferences outside the subscription flow. To update select topic preferences while preserving those set for other topics, use JSON dot notation `"cio_subscription_preferences.topics.topic_<topic ID>":<boolean>`."""
    topics: dict[str, bool] | None = Field(None, description="Contains active topics in your workspace, named `topic_<id>`.")

class DeliveryOperationsAttributes(PermissiveModel):
    """Contains information about the delivery and the individual who received the message."""
    device_token: str = Field(..., description="The device that received the message.")

class DeliveryOperationsIdentifiers(PermissiveModel):
    """Contains identifiers for the delivery itself."""
    id_: str | None = Field(None, validation_alias="id", serialization_alias="id", description="The `delivery_id` for the delivery that you want to attribute metrics to.")

class DeliveryOperations(PermissiveModel):
    """The "delivery" type lets you attribute metrics to messages that don't self-report back to Customer.io, like push and in-app notifications."""
    type_: Literal["delivery"] = Field(..., validation_alias="type", serialization_alias="type", description="The \"delivery\" type lets you attribute metrics to messages that don't self-report back to Customer.io, like push and in-app notifications.")
    action: Literal["event"] = Field(..., description="An `event` action indicates a delivery event. Use the `name` to determine the specific metric that you want to attribute to this delivery.")
    identifiers: DeliveryOperationsIdentifiers = Field(..., description="Contains identifiers for the delivery itself.")
    name: Literal["opened", "converted", "delivered"] = Field(..., description="The name of the metric you want to attribute to this \"delivery\".")
    attributes: DeliveryOperationsAttributes = Field(..., description="Contains information about the delivery and the individual who received the message.")

class DeviceObjectAttributes(PermissiveModel):
    """Attributes that you can reference to segment your audience—like a person's attributes, but specific to a device. These can be either the attributes defined below or custom key-value attributes."""
    device_os: str | None = Field(None, description="The operating system, including the version, on the device.")
    device_model: str | None = Field(None, description="The model of the device a person uses.")
    app_version: str | None = Field(None, description="The version of your app that a customer uses. You might target app versions to let people know when they need to update, or expose them to new features when they do.")
    cio_sdk_version: str | None = Field(None, description="The version of the Customer.io SDK in the app.")
    last_status: Literal["", "bounced", "sent", "suppressed"] | None = Field(None, validation_alias="_last_status", serialization_alias="_last_status", description="The delivery status of the last message sent to the device—sent, bounced, or suppressed. An empty string indicates that that the device hasn't received a push yet.")
    device_locale: str | None = Field(None, description="The four-letter [IETF language code](/localization/#supported-languages) for the device. For example, `en-MX` (indicating an app in Spanish formatted for a user in Mexico) or `es-ES` (indicating an...")
    push_enabled: Literal["true", "false"] | None = Field(None, description="If `\"true\"`, the device is opted-in and can receive push notifications.")

class DeviceObjectCommon(PermissiveModel):
    """Device information common to the v1 and v2 APIs."""
    last_used: int | None = Field(None, description="The `timestamp` when you last identified this device. If you don't pass a timestamp when you add or update a device, we use the time of the request itself. Our SDKs identify a device when a person ...", json_schema_extra={'format': 'unix timestamp'})
    platform: Literal["ios", "android"] = Field(..., description="The device/messaging platform.")
    attributes: dict[str, str] | None = Field(None, description="Attributes that you can reference to segment your audience—like a person's attributes, but specific to a device. These can be either the attributes defined below or custom key-value attributes.")

class DeviceObject(PermissiveModel):
    """The properties representing an individual device. [Our SDK's](/integrations/sdk/) gather all the properties defined below automatically, unless you disable the `autoTrackDeviceAttributes` setting. You can reference the properties outside the `attributes` object in segments or in Liquid."""
    id_: str = Field(..., validation_alias="id", serialization_alias="id", description="The device token.")
    last_used: int | None = Field(None, description="The `timestamp` when you last identified this device. If you don't pass a timestamp when you add or update a device, we use the time of the request itself. Our SDKs identify a device when a person ...", json_schema_extra={'format': 'unix timestamp'})
    platform: Literal["ios", "android"] = Field(..., description="The device/messaging platform.")
    attributes: dict[str, str] | None = Field(None, description="Attributes that you can reference to segment your audience—like a person's attributes, but specific to a device. These can be either the attributes defined below or custom key-value attributes.")

class DeviceObjectCommonAttributes(PermissiveModel):
    """Attributes that you can reference to segment your audience—like a person's attributes, but specific to a device. These can be either the attributes defined below or custom key-value attributes."""
    device_os: str | None = Field(None, description="The operating system, including the version, on the device.")
    device_model: str | None = Field(None, description="The model of the device a person uses.")
    app_version: str | None = Field(None, description="The version of your app that a customer uses. You might target app versions to let people know when they need to update, or expose them to new features when they do.")
    cio_sdk_version: str | None = Field(None, description="The version of the Customer.io SDK in the app.")
    last_status: Literal["", "bounced", "sent", "suppressed"] | None = Field(None, validation_alias="_last_status", serialization_alias="_last_status", description="The delivery status of the last message sent to the device—sent, bounced, or suppressed. An empty string indicates that that the device hasn't received a push yet.")
    device_locale: str | None = Field(None, description="The four-letter [IETF language code](/localization/#supported-languages) for the device. For example, `en-MX` (indicating an app in Spanish formatted for a user in Mexico) or `es-ES` (indicating an...")
    push_enabled: Literal["true", "false"] | None = Field(None, description="If `\"true\"`, the device is opted-in and can receive push notifications.")

class IdentifyBodyCioRelationshipsRelationshipsItemIdentifiersV0(PermissiveModel):
    object_type_id: str = Field(..., description="The object type an object belongs to—like \"Companies\" or \"Accounts\". Object type IDs are string-formatted integers that begin at `1` and increment for each new type.")
    object_id: str = Field(..., description="The unique identifier for an object. If you use an `object_id` that already exists, we'll update the object accordingly.")

class IdentifyBodyCioRelationshipsRelationshipsItemIdentifiersV1(PermissiveModel):
    cio_object_id: str = Field(..., description="A unique value that Customer.io sets for an object when you create it. This ID is immutable.")

class IdentifyBodyCioRelationshipsRelationshipsItem(PermissiveModel):
    identifiers: IdentifyBodyCioRelationshipsRelationshipsItemIdentifiersV0 | IdentifyBodyCioRelationshipsRelationshipsItemIdentifiersV1 | None = Field(None, description="The identifiers for a particular object. You can use either the `object_type_id` and `object_id` (where `object_type_id` represents the type of object and the `object_id` is the individual identifi...")
    relationship_attributes: dict[str, Any] | None = Field(None, description="The attributes associated with a relationship. Passing null or an empty string removes the attribute from the relationship.\n")

class IdentifyPersonAttributes(PermissiveModel):
    """Attributes that you want to add or update for this person. You can pass properties that aren't defined below to set custom attributes; the defined properties are reserved in the Customer.io Track API."""
    cio_subscription_preferences: CioSubscriptionPreferences | None = None
    update: bool | None = Field(False, validation_alias="_update", serialization_alias="_update", description="By default, an `identify` request creates a new person if they don't already exist. If you perform multiple requests in rapid succession, there's a danger that you could create multiple profiles. I...")

class IdentifyPersonIdentifiersV0(PermissiveModel):
    id_: str = Field(..., validation_alias="id", serialization_alias="id")

class IdentifyPersonIdentifiersV1(PermissiveModel):
    email: str

class IdentifyPersonIdentifiersV2(PermissiveModel):
    cio_id: str

class IdentifyPersonV1Attributes(PermissiveModel):
    """Attributes that you want to add or update for this person. You can pass properties that aren't defined below to set custom attributes; the defined properties are reserved in the Customer.io Track API."""
    cio_subscription_preferences: CioSubscriptionPreferences | None = None
    update: bool | None = Field(False, validation_alias="_update", serialization_alias="_update", description="By default, an `identify` request creates a new person if they don't already exist. If you perform multiple requests in rapid succession, there's a danger that you could create multiple profiles. I...")

class MergeBodyPrimaryV0(PermissiveModel):
    id_: str | None = Field(None, validation_alias="id", serialization_alias="id")

class MergeBodyPrimaryV1(PermissiveModel):
    email: str | None = None

class MergeBodyPrimaryV2(PermissiveModel):
    cio_id: str | None = None

class MergeBodySecondaryV0(PermissiveModel):
    id_: str | None = Field(None, validation_alias="id", serialization_alias="id")

class MergeBodySecondaryV1(PermissiveModel):
    email: str | None = None

class MergeBodySecondaryV2(PermissiveModel):
    cio_id: str | None = None

class ObjectAttributes(PermissiveModel):
    """The data that belongs to the object. This is information you might want to associate with people later (through `cio_relationships`). Passing `null` or an empty string removes the attribute from the object. Some attributes have special meaning. Please refer to the list of [reserved attributes](/journeys/objects-create/#reserved-attributes).
"""
    value: dict[str, Any] = Field(..., description="The data that belongs to the object. This is information you might want to associate with people later (through `cio_relationships`). Passing `null` or an empty string removes the attribute from th...")

class ObjectCommonIdentifiersV0(PermissiveModel):
    object_type_id: str
    object_id: str = Field(..., description="The unique identifier for an object. If you use an `object_id` that already exists, we'll update the object accordingly.")

class ObjectCommonIdentifiersV1(PermissiveModel):
    cio_object_id: str = Field(..., description="A unique value that Customer.io sets for an object when you create it. This ID is immutable.")

class ObjectCommonIdentifyIdentifiersV0(PermissiveModel):
    object_type_id: str
    object_id: str = Field(..., description="The unique identifier for an object. If you use an `object_id` that already exists, we'll update the object accordingly.")

class ObjectCommonIdentifyIdentifiersV1(PermissiveModel):
    cio_object_id: str = Field(..., description="A unique value that Customer.io sets for an object when you create it. This ID is immutable.")

class ObjectCommonIdentify(PermissiveModel):
    identifiers: ObjectCommonIdentifyIdentifiersV0 | ObjectCommonIdentifyIdentifiersV1 = Field(..., description="The identifiers for a custom object. When identifying a new object, you *must* use both the `object_type_id` and `object_id` (where `object_type_id` is an integer representing the type of object an...")
    type_: Literal["object"] = Field(..., validation_alias="type", serialization_alias="type", description="The operation modifies a single object—non person data.")

class ObjectIdentifiersIdentifiersV0(PermissiveModel):
    object_type_id: str
    object_id: str = Field(..., description="The unique identifier for an object. If you use an `object_id` that already exists, we'll update the object accordingly.")

class ObjectIdentifiersIdentifiersV1(PermissiveModel):
    cio_object_id: str = Field(..., description="A unique value that Customer.io sets for an object when you create it. This ID is immutable.")

class ObjectIdentifiers(PermissiveModel):
    identifiers: ObjectIdentifiersIdentifiersV0 | ObjectIdentifiersIdentifiersV1 | None = Field(None, description="The identifiers for a particular object. You can use either the `object_type_id` and `object_id` (where `object_type_id` represents the type of object and the `object_id` is the individual identifi...")

class ObjectCommon(PermissiveModel):
    identifiers: ObjectCommonIdentifiersV0 | ObjectCommonIdentifiersV1 | None = Field(None, description="The identifiers for a particular object. You can use either the `object_type_id` and `object_id` (where `object_type_id` represents the type of object and the `object_id` is the individual identifi...")
    type_: Literal["object"] = Field(..., validation_alias="type", serialization_alias="type", description="The operation modifies a single object—non person data.")

class ObjectDelete(PermissiveModel):
    """Delete an object. This also removes relationships from people.
"""
    action: Literal["delete"] = Field(..., description="Indicates that the operation will `delete` the the item of the specified `type`.")

class ObjectIdentifyAnonymousCioRelationshipsItemIdentifiers(PermissiveModel):
    anonymous_id: str | None = None

class ObjectIdentifyAnonymousCioRelationshipsItem(PermissiveModel):
    identifiers: ObjectIdentifyAnonymousCioRelationshipsItemIdentifiers | None = None
    relationship_attributes: dict[str, Any] | None = Field(None, description="Coming October 2023 - The attributes associated with a relationship. Passing null or an empty string removes the attribute from the relationship.")

class ObjectIdentifyAnonymousIdentifiersV0(PermissiveModel):
    object_type_id: str
    object_id: str = Field(..., description="The unique identifier for an object. If you use an `object_id` that already exists, we'll update the object accordingly.")

class ObjectIdentifyAnonymousIdentifiersV1(PermissiveModel):
    cio_object_id: str = Field(..., description="A unique value that Customer.io sets for an object when you create it. This ID is immutable.")

class ObjectIdentifyAnonymous(PermissiveModel):
    """The `identify_anonymous` action lets you relate an object to a person who hasn't yet identified themselves by anonymous_id. When you identify the person, their anonymous relationship will carry over to the identified profile."""
    identifiers: ObjectIdentifyAnonymousIdentifiersV0 | ObjectIdentifyAnonymousIdentifiersV1 = Field(..., description="The identifiers for a custom object. When identifying a new object, you *must* use both the `object_type_id` and `object_id` (where `object_type_id` is an integer representing the type of object an...")
    type_: Literal["object"] = Field(..., validation_alias="type", serialization_alias="type", description="The operation modifies a single object—non person data.")
    action: Literal["identify_anonymous"] = Field(..., description="Indicates that the operation will `identify` the item of the specified `type` and relate it to an `anonymous_id`.")
    attributes: ObjectAttributes | None = None
    cio_relationships: list[ObjectIdentifyAnonymousCioRelationshipsItem] | None = Field(None, description="The anonymous people you want to associate with an object. Each object in the array contains an `anonymous_id` representing a person you haven't yet identified by `id` or `email`.")

class ObjectIdentifyAnonymousV1CioRelationshipsItemIdentifiers(PermissiveModel):
    anonymous_id: str | None = None

class ObjectIdentifyAnonymousV1CioRelationshipsItem(PermissiveModel):
    identifiers: ObjectIdentifyAnonymousV1CioRelationshipsItemIdentifiers | None = None
    relationship_attributes: dict[str, Any] | None = Field(None, description="Coming October 2023 - The attributes associated with a relationship. Passing null or an empty string removes the attribute from the relationship.")

class ObjectIdentifyIdentifiersV0(PermissiveModel):
    object_type_id: str
    object_id: str = Field(..., description="The unique identifier for an object. If you use an `object_id` that already exists, we'll update the object accordingly.")

class ObjectIdentifyIdentifiersV1(PermissiveModel):
    cio_object_id: str = Field(..., description="A unique value that Customer.io sets for an object when you create it. This ID is immutable.")

class ObjectRelationshipsItemIdentifiersV0(PermissiveModel):
    object_type_id: str
    object_id: str = Field(..., description="The unique identifier for an object. If you use an `object_id` that already exists, we'll update the object accordingly.")

class ObjectRelationshipsItemIdentifiersV1(PermissiveModel):
    cio_object_id: str = Field(..., description="A unique value that Customer.io sets for an object when you create it. This ID is immutable.")

class PersonAddDeviceDevice(PermissiveModel):
    """The properties representing an individual device. [Our SDK's](/integrations/sdk/) gather all the properties defined below automatically, unless you disable the `autoTrackDeviceAttributes` setting. You can reference the properties outside the `attributes` object in segments."""
    token: str = Field(..., description="The device token.")
    last_used: int | None = Field(None, description="The `timestamp` when you last identified this device. If you don't pass a timestamp when you add or update a device, we use the time of the request itself. Our SDKs identify a device when a person ...", json_schema_extra={'format': 'unix timestamp'})
    platform: Literal["ios", "android"] = Field(..., description="The device/messaging platform.")
    attributes: dict[str, str] | None = Field(None, description="Attributes that you can reference to segment your audience—like a person's attributes, but specific to a device. These can be either the attributes defined below or custom key-value attributes.")

class PersonAddDeviceDeviceAttributes(PermissiveModel):
    """Attributes that you can reference to segment your audience—like a person's attributes, but specific to a device. These can be either the attributes defined below or custom key-value attributes."""
    device_os: str | None = Field(None, description="The operating system, including the version, on the device.")
    device_model: str | None = Field(None, description="The model of the device a person uses.")
    app_version: str | None = Field(None, description="The version of your app that a customer uses. You might target app versions to let people know when they need to update, or expose them to new features when they do.")
    cio_sdk_version: str | None = Field(None, description="The version of the Customer.io SDK in the app.")
    last_status: Literal["", "bounced", "sent", "suppressed"] | None = Field(None, validation_alias="_last_status", serialization_alias="_last_status", description="The delivery status of the last message sent to the device—sent, bounced, or suppressed. An empty string indicates that that the device hasn't received a push yet.")
    device_locale: str | None = Field(None, description="The four-letter [IETF language code](/localization/#supported-languages) for the device. For example, `en-MX` (indicating an app in Spanish formatted for a user in Mexico) or `es-ES` (indicating an...")
    push_enabled: Literal["true", "false"] | None = Field(None, description="If `\"true\"`, the device is opted-in and can receive push notifications.")

class PersonAddDeviceIdentifiersV0(PermissiveModel):
    id_: str = Field(..., validation_alias="id", serialization_alias="id")

class PersonAddDeviceIdentifiersV1(PermissiveModel):
    email: str

class PersonAddDeviceIdentifiersV2(PermissiveModel):
    cio_id: str

class PersonAddDeviceV1Device(PermissiveModel):
    """The properties representing an individual device. [Our SDK's](/integrations/sdk/) gather all the properties defined below automatically, unless you disable the `autoTrackDeviceAttributes` setting. You can reference the properties outside the `attributes` object in segments."""
    token: str = Field(..., description="The device token.")
    last_used: int | None = Field(None, description="The `timestamp` when you last identified this device. If you don't pass a timestamp when you add or update a device, we use the time of the request itself. Our SDKs identify a device when a person ...", json_schema_extra={'format': 'unix timestamp'})
    platform: Literal["ios", "android"] = Field(..., description="The device/messaging platform.")
    attributes: dict[str, str] | None = Field(None, description="Attributes that you can reference to segment your audience—like a person's attributes, but specific to a device. These can be either the attributes defined below or custom key-value attributes.")

class PersonAddDeviceV1DeviceAttributes(PermissiveModel):
    """Attributes that you can reference to segment your audience—like a person's attributes, but specific to a device. These can be either the attributes defined below or custom key-value attributes."""
    device_os: str | None = Field(None, description="The operating system, including the version, on the device.")
    device_model: str | None = Field(None, description="The model of the device a person uses.")
    app_version: str | None = Field(None, description="The version of your app that a customer uses. You might target app versions to let people know when they need to update, or expose them to new features when they do.")
    cio_sdk_version: str | None = Field(None, description="The version of the Customer.io SDK in the app.")
    last_status: Literal["", "bounced", "sent", "suppressed"] | None = Field(None, validation_alias="_last_status", serialization_alias="_last_status", description="The delivery status of the last message sent to the device—sent, bounced, or suppressed. An empty string indicates that that the device hasn't received a push yet.")
    device_locale: str | None = Field(None, description="The four-letter [IETF language code](/localization/#supported-languages) for the device. For example, `en-MX` (indicating an app in Spanish formatted for a user in Mexico) or `es-ES` (indicating an...")
    push_enabled: Literal["true", "false"] | None = Field(None, description="If `\"true\"`, the device is opted-in and can receive push notifications.")

class PersonAddRelationshipsIdentifiersV0(PermissiveModel):
    id_: str = Field(..., validation_alias="id", serialization_alias="id")

class PersonAddRelationshipsIdentifiersV1(PermissiveModel):
    email: str

class PersonAddRelationshipsIdentifiersV2(PermissiveModel):
    cio_id: str

class PersonCommonIdentifiersV0(PermissiveModel):
    id_: str = Field(..., validation_alias="id", serialization_alias="id")

class PersonCommonIdentifiersV1(PermissiveModel):
    email: str

class PersonCommonIdentifiersV2(PermissiveModel):
    cio_id: str

class PersonCommon(PermissiveModel):
    type_: Literal["person"] = Field(..., validation_alias="type", serialization_alias="type", description="The operation modifies a person in Customer.io")
    identifiers: PersonCommonIdentifiersV0 | PersonCommonIdentifiersV1 | PersonCommonIdentifiersV2 = Field(..., description="The person you want to perform an action for—one of either `id`, `email`, or `cio_id`. You cannot pass multiple identifiers.")

class PersonAddDevice(PermissiveModel):
    """Assign devices to a person."""
    type_: Literal["person"] = Field(..., validation_alias="type", serialization_alias="type", description="The operation modifies a person in Customer.io")
    identifiers: PersonAddDeviceIdentifiersV0 | PersonAddDeviceIdentifiersV1 | PersonAddDeviceIdentifiersV2 = Field(..., description="The person you want to perform an action for—one of either `id`, `email`, or `cio_id`. You cannot pass multiple identifiers.")
    action: Literal["add_device"] = Field(..., description="Add a mobile device to a person's profile.")
    device: PersonAddDeviceDevice = Field(..., description="The properties representing an individual device. [Our SDK's](/integrations/sdk/) gather all the properties defined below automatically, unless you disable the `autoTrackDeviceAttributes` setting. ...")

class PersonDeleteDeviceDevice(PermissiveModel):
    """The device you want to remove."""
    token: str = Field(..., description="The token of the device you want to remove.")

class PersonDeleteDeviceIdentifiersV0(PermissiveModel):
    id_: str = Field(..., validation_alias="id", serialization_alias="id")

class PersonDeleteDeviceIdentifiersV1(PermissiveModel):
    email: str

class PersonDeleteDeviceIdentifiersV2(PermissiveModel):
    cio_id: str

class PersonDeleteDevice(PermissiveModel):
    """Delete devices that belong to a person."""
    type_: Literal["person"] = Field(..., validation_alias="type", serialization_alias="type", description="The operation modifies a person in Customer.io")
    identifiers: PersonDeleteDeviceIdentifiersV0 | PersonDeleteDeviceIdentifiersV1 | PersonDeleteDeviceIdentifiersV2 = Field(..., description="The person you want to perform an action for—one of either `id`, `email`, or `cio_id`. You cannot pass multiple identifiers.")
    action: Literal["delete_device"] = Field(..., description="Delete a device from a person's profile.")
    device: PersonDeleteDeviceDevice = Field(..., description="The device you want to remove.")

class PersonDeleteDeviceV1Device(PermissiveModel):
    """The device you want to remove."""
    token: str = Field(..., description="The token of the device you want to remove.")

class PersonDeleteIdentifiersV0(PermissiveModel):
    id_: str = Field(..., validation_alias="id", serialization_alias="id")

class PersonDeleteIdentifiersV1(PermissiveModel):
    email: str

class PersonDeleteIdentifiersV2(PermissiveModel):
    cio_id: str

class PersonDelete(PermissiveModel):
    """Delete a person from your workspace."""
    type_: Literal["person"] = Field(..., validation_alias="type", serialization_alias="type", description="The operation modifies a person in Customer.io")
    identifiers: PersonDeleteIdentifiersV0 | PersonDeleteIdentifiersV1 | PersonDeleteIdentifiersV2 = Field(..., description="The person you want to perform an action for—one of either `id`, `email`, or `cio_id`. You cannot pass multiple identifiers.")
    action: Literal["delete"] = Field(..., description="Indicates that the operation will `delete` the the item of the specified `type`.")

class PersonDeleteRelationshipsIdentifiersV0(PermissiveModel):
    id_: str = Field(..., validation_alias="id", serialization_alias="id")

class PersonDeleteRelationshipsIdentifiersV1(PermissiveModel):
    email: str

class PersonDeleteRelationshipsIdentifiersV2(PermissiveModel):
    cio_id: str

class PersonEventAttributes(PermissiveModel):
    """Additional information that you might want to reference in a message using liquid or use to set attributes on the identified person.
"""
    recipient: str | None = Field(None, description="The email address of the person associated with the event, overriding the `to` field in emails triggered by the event.", json_schema_extra={'format': 'email'})
    from_address: str | None = Field(None, description="The address you want to trigger messages from, overriding the `from` field in emails triggered by the event.", json_schema_extra={'format': 'email'})
    reply_to: str | None = Field(None, description="The address you want to receive replies to, overriding the `reply to` field for emails triggered by the event.", json_schema_extra={'format': 'email'})

class PersonEventIdentifiersV0(PermissiveModel):
    id_: str = Field(..., validation_alias="id", serialization_alias="id")

class PersonEventIdentifiersV1(PermissiveModel):
    email: str

class PersonEventIdentifiersV2(PermissiveModel):
    cio_id: str

class PersonEvent(PermissiveModel):
    """A custom event attributed to a person. You can use events to trigger campaigns, or reference event information using liquid in your messages."""
    type_: Literal["person"] = Field(..., validation_alias="type", serialization_alias="type", description="The operation modifies a person in Customer.io")
    identifiers: PersonEventIdentifiersV0 | PersonEventIdentifiersV1 | PersonEventIdentifiersV2 = Field(..., description="The person you want to perform an action for—one of either `id`, `email`, or `cio_id`. You cannot pass multiple identifiers.")
    action: Literal["event"] = Field(..., description="A custom event attributed to the specified person.")
    id_: str | None = Field(None, validation_alias="id", serialization_alias="id", description="A valid ULID used to deduplicate events. Note - our Python and Ruby libraries do not pass this id.", json_schema_extra={'format': 'ULID'})
    name: str = Field(..., description="The name of the event. This is how you'll find your event in Customer.io or select it when using events as campaign triggers.")
    timestamp: int | None = Field(None, description="The Unix timestamp when the event happened.")
    attributes: dict[str, Any] | None = Field(None, description="Additional information that you might want to reference in a message using liquid or use to set attributes on the identified person.\n")

class PersonEventV1Attributes(PermissiveModel):
    """Additional information that you might want to reference in a message using liquid or use to set attributes on the identified person.
"""
    recipient: str | None = Field(None, description="The email address of the person associated with the event, overriding the `to` field in emails triggered by the event.", json_schema_extra={'format': 'email'})
    from_address: str | None = Field(None, description="The address you want to trigger messages from, overriding the `from` field in emails triggered by the event.", json_schema_extra={'format': 'email'})
    reply_to: str | None = Field(None, description="The address you want to receive replies to, overriding the `reply to` field for emails triggered by the event.", json_schema_extra={'format': 'email'})

class PersonMergePrimaryV0(PermissiveModel):
    id_: str = Field(..., validation_alias="id", serialization_alias="id")

class PersonMergePrimaryV1(PermissiveModel):
    email: str

class PersonMergePrimaryV2(PermissiveModel):
    cio_id: str

class PersonMergeSecondaryV0(PermissiveModel):
    id_: str = Field(..., validation_alias="id", serialization_alias="id")

class PersonMergeSecondaryV1(PermissiveModel):
    email: str

class PersonMergeSecondaryV2(PermissiveModel):
    cio_id: str

class PersonMerge(PermissiveModel):
    """Merge two people. You'll merge the `secondary` person into the `primary`. The primary profile remains after the merge and the secondary is deleted. This operation is _not_ reversible.

**Important:** The primary profile must already exist in Customer.io for the merge operation to work. If the primary profile doesn't exist, the merge request will not perform any action. This can lead to race conditions if you have concurrent requests that create a profile and merge profiles with the same primary ID.

See our page on [merging duplicate people](/merge-people/) for more information.
"""
    type_: Literal["person"] = Field(..., validation_alias="type", serialization_alias="type", description="The operation modifies a person in Customer.io")
    action: Literal["merge"] = Field(..., description="Merge two people. You'll merge the `secondary` person into the `primary`. The primary profile remains after the merge and the secondary is deleted. This operation is _not_ reversible. See our page ...")
    primary: PersonMergePrimaryV0 | PersonMergePrimaryV1 | PersonMergePrimaryV2 = Field(..., description="The person that you want to remain after the merge, identified by one of `id`, `email`, or `cio_id`. This person receives information from the secondary person in the merge. \n        \nIf email is...")
    secondary: PersonMergeSecondaryV0 | PersonMergeSecondaryV1 | PersonMergeSecondaryV2 = Field(..., description="The person that you want to delete after the merge, identified by one of `id`, `email`, or `cio_id`. This person's information is merged into the primary person's profile and then it is deleted.\n ...")

class PersonPageAttributes(PermissiveModel):
    """Additional information that you might want to reference in a message using liquid or use to set attributes on the identified person."""
    path: str | None = Field(None, description="The path portion of the page's URL. Equivalent to the canonical `path` which defaults to `location.pathname` from the DOM API.")
    referrer: str | None = Field(None, description="The previous page's full URL. Equivalent to `document.referrer` from the DOM API.")
    search: str | None = Field(None, description="The query string portion of the page's URL. Equivalent to `location.search` from the DOM API.")
    title: str | None = Field(None, description="The page's title. Equivalent to `document.title` from the DOM API.")
    url: str | None = Field(None, description="A page's full URL. We first look for the canonical URL. If the canonical URL is not provided, we'll use `location.href` from the DOM API.")
    keywords: list[str] | None = Field(None, description="A list/array of keywords describing the page's content. The keywords are likely the same as, or similar to, the keywords you would find in an HTML `meta` tag for SEO purposes. This property is main...")

class PersonPageIdentifiersV0(PermissiveModel):
    id_: str = Field(..., validation_alias="id", serialization_alias="id")

class PersonPageIdentifiersV1(PermissiveModel):
    email: str

class PersonPageIdentifiersV2(PermissiveModel):
    cio_id: str

class PersonPage(PermissiveModel):
    """A web "pageview" event attributed to a person. Our `screen` and `page` event types are more specific than our standard `event`, and help you track and target people based on the pages people visit in your mobile app or website."""
    type_: Literal["person"] = Field(..., validation_alias="type", serialization_alias="type", description="The operation modifies a person in Customer.io")
    identifiers: PersonPageIdentifiersV0 | PersonPageIdentifiersV1 | PersonPageIdentifiersV2 = Field(..., description="The person you want to perform an action for—one of either `id`, `email`, or `cio_id`. You cannot pass multiple identifiers.")
    action: Literal["page"] = Field(..., description="A web \"pageview\" event attributed to a person. Our `screen` and `page` event types are more specific than our standard `event`, and help you track and target people based on the pages people visi...")
    id_: str | None = Field(None, validation_alias="id", serialization_alias="id", description="A valid ULID used to deduplicate events. Note - our Python and Ruby libraries do not pass this id.", json_schema_extra={'format': 'ULID'})
    name: str = Field(..., description="The name of the page or page path that a person visited. This is how you'll find and select page view events in Customer.io.")
    timestamp: int | None = Field(None, description="The Unix timestamp when the event happened.")
    attributes: dict[str, Any] | None = Field(None, description="Additional information that you might want to reference in a message using liquid or use to set attributes on the identified person.")

class PersonPageV1Attributes(PermissiveModel):
    """Additional information that you might want to reference in a message using liquid or use to set attributes on the identified person."""
    path: str | None = Field(None, description="The path portion of the page's URL. Equivalent to the canonical `path` which defaults to `location.pathname` from the DOM API.")
    referrer: str | None = Field(None, description="The previous page's full URL. Equivalent to `document.referrer` from the DOM API.")
    search: str | None = Field(None, description="The query string portion of the page's URL. Equivalent to `location.search` from the DOM API.")
    title: str | None = Field(None, description="The page's title. Equivalent to `document.title` from the DOM API.")
    url: str | None = Field(None, description="A page's full URL. We first look for the canonical URL. If the canonical URL is not provided, we'll use `location.href` from the DOM API.")
    keywords: list[str] | None = Field(None, description="A list/array of keywords describing the page's content. The keywords are likely the same as, or similar to, the keywords you would find in an HTML `meta` tag for SEO purposes. This property is main...")

class PersonScreenIdentifiersV0(PermissiveModel):
    id_: str = Field(..., validation_alias="id", serialization_alias="id")

class PersonScreenIdentifiersV1(PermissiveModel):
    email: str

class PersonScreenIdentifiersV2(PermissiveModel):
    cio_id: str

class PersonScreen(PermissiveModel):
    """A mobile "screenview" event attributed to a person. Our `screen` and `page` event types are more specific than our standard `event`, and help you track and target people based on the pages people visit in your mobile app or website."""
    type_: Literal["person"] = Field(..., validation_alias="type", serialization_alias="type", description="The operation modifies a person in Customer.io")
    identifiers: PersonScreenIdentifiersV0 | PersonScreenIdentifiersV1 | PersonScreenIdentifiersV2 = Field(..., description="The person you want to perform an action for—one of either `id`, `email`, or `cio_id`. You cannot pass multiple identifiers.")
    action: Literal["screen"] = Field(..., description="A mobile \"screenview\" event attributed to a person. Our `screen` and `page` event types are more specific than our standard `event`, and help you track and target people based on the pages people...")
    id_: str | None = Field(None, validation_alias="id", serialization_alias="id", description="A valid ULID used to deduplicate events. Note - our Python and Ruby libraries do not pass this id.", json_schema_extra={'format': 'ULID'})
    name: str = Field(..., description="The name of the screen a person visited. This is how you'll find and select screen view events in Customer.io.")
    timestamp: int | None = Field(None, description="The Unix timestamp when the event happened.")
    attributes: dict[str, Any] | None = Field(None, description="Additional information that you might want to reference in a message using liquid or use to set attributes on the identified person.")

class PersonSuppressIdentifiersV0(PermissiveModel):
    id_: str = Field(..., validation_alias="id", serialization_alias="id")

class PersonSuppressIdentifiersV1(PermissiveModel):
    email: str

class PersonSuppressIdentifiersV2(PermissiveModel):
    cio_id: str

class PersonSuppress(PermissiveModel):
    """Suppress a person's identifier(s) in Customer.io, so that you can't message a person or add their identifiers back to your workspace. This is separate from suppressions performed by your email provider."""
    type_: Literal["person"] = Field(..., validation_alias="type", serialization_alias="type", description="The operation modifies a person in Customer.io")
    identifiers: PersonSuppressIdentifiersV0 | PersonSuppressIdentifiersV1 | PersonSuppressIdentifiersV2 = Field(..., description="The person you want to perform an action for—one of either `id`, `email`, or `cio_id`. You cannot pass multiple identifiers.")
    action: Literal["suppress"] = Field(..., description="Suppress a person's identifier(s) in Customer.io, so that you can't message a person or add their identifiers back to your workspace. This is separate from suppressions performed by your email prov...")

class PersonUnsuppressIdentifiersV0(PermissiveModel):
    id_: str = Field(..., validation_alias="id", serialization_alias="id")

class PersonUnsuppressIdentifiersV1(PermissiveModel):
    email: str

class PersonUnsuppressIdentifiersV2(PermissiveModel):
    cio_id: str

class PersonUnsuppress(PermissiveModel):
    """Unsuppress a person's identifier(s) in Customer.io, so that you can message a person or add their identifiers back to your workspace. This does not unsuppress addresses that were previously suppressed by your email provider."""
    type_: Literal["person"] = Field(..., validation_alias="type", serialization_alias="type", description="The operation modifies a person in Customer.io")
    identifiers: PersonUnsuppressIdentifiersV0 | PersonUnsuppressIdentifiersV1 | PersonUnsuppressIdentifiersV2 = Field(..., description="The person you want to perform an action for—one of either `id`, `email`, or `cio_id`. You cannot pass multiple identifiers.")
    action: Literal["unsuppress"] = Field(..., description="Unsuppress a person's identifier(s) in Customer.io, so that you can message a person or add their identifiers back to your workspace. This does not unsuppress addresses that were previously suppres...")

class RelationshipAttributes(PermissiveModel):
    """The attributes associated with a relationship. Passing null or an empty string removes the attribute from the relationship.
"""
    value: dict[str, Any] = Field(..., description="The attributes associated with a relationship. Passing null or an empty string removes the attribute from the relationship.\n")

class ObjectRelationshipsItem(PermissiveModel):
    identifiers: ObjectRelationshipsItemIdentifiersV0 | ObjectRelationshipsItemIdentifiersV1 | None = Field(None, description="The identifiers for a particular object. You can use either the `object_type_id` and `object_id` (where `object_type_id` represents the type of object and the `object_id` is the individual identifi...")
    relationship_attributes: RelationshipAttributes | None = None

class ObjectRelationships(PermissiveModel):
    """Each object in the array represents a relationship you want to add to, or remove from, a person."""
    value: list[ObjectRelationshipsItem] = Field(..., description="Each object in the array represents a relationship you want to add to, or remove from, a person.")

class IdentifyPerson(PermissiveModel):
    """Add or update a person."""
    type_: Literal["person"] = Field(..., validation_alias="type", serialization_alias="type", description="The operation modifies a person in Customer.io")
    identifiers: IdentifyPersonIdentifiersV0 | IdentifyPersonIdentifiersV1 | IdentifyPersonIdentifiersV2 = Field(..., description="The person you want to perform an action for—one of either `id`, `email`, or `cio_id`. You cannot pass multiple identifiers.")
    action: Literal["identify"] = Field(..., description="Indicates that the operation will `identify` the the item of the specified `type`.")
    timestamp: int | None = Field(None, description="The Unix timestamp for when the attribute update occurred. This can be used to control the order of attribute updates when multiple requests are sent in rapid succession.")
    attributes: dict[str, Any] | None = Field(None, description="Attributes that you want to add or update for this person. You can pass properties that aren't defined below to set custom attributes; the defined properties are reserved in the Customer.io Track API.")
    cio_relationships: ObjectRelationships | None = None

class PersonAddRelationships(PermissiveModel):
    """Associate multiple objects with a person."""
    type_: Literal["person"] = Field(..., validation_alias="type", serialization_alias="type", description="The operation modifies a person in Customer.io")
    identifiers: PersonAddRelationshipsIdentifiersV0 | PersonAddRelationshipsIdentifiersV1 | PersonAddRelationshipsIdentifiersV2 = Field(..., description="The person you want to perform an action for—one of either `id`, `email`, or `cio_id`. You cannot pass multiple identifiers.")
    action: Literal["add_relationships"] = Field(..., description="This operation associates a person with one or more objects.")
    cio_relationships: ObjectRelationships

class PersonDeleteRelationships(PermissiveModel):
    """Remove multiple object relationships from a person."""
    type_: Literal["person"] = Field(..., validation_alias="type", serialization_alias="type", description="The operation modifies a person in Customer.io")
    identifiers: PersonDeleteRelationshipsIdentifiersV0 | PersonDeleteRelationshipsIdentifiersV1 | PersonDeleteRelationshipsIdentifiersV2 = Field(..., description="The person you want to perform an action for—one of either `id`, `email`, or `cio_id`. You cannot pass multiple identifiers.")
    action: Literal["delete_relationships"] = Field(..., description="This operation deletes an object relationship from one or more people.")
    cio_relationships: ObjectRelationships

class SubmitFormBodyDataV0(PermissiveModel):
    """Identify the person who submitted your form by email."""
    email: str

class SubmitFormBodyDataV1(PermissiveModel):
    """Identify the person who submitted your form by ID."""
    id_: str = Field(..., validation_alias="id", serialization_alias="id")

class TrackAnonymousBodyV0(PermissiveModel):
    anonymous_id: str | None = Field(None, description="An identifier for an anonymous event, like a cookie. If set as an attribute on a person, any events bearing the same anonymous value are associated with this person. This value must be unique and i...")
    name: str = Field(..., description="The name of the event. This is how you'll reference the event in campaigns or segments.")
    id_: str | None = Field(None, validation_alias="id", serialization_alias="id", description="An identifier used to deduplicate events. This value must be a [ULID](https://github.com/ulid/spec). If an event has the same value as an event we previously received, we won't show or process the ...", json_schema_extra={'format': 'ulid'})
    type_: Literal["event", "page", "screen"] | None = Field(None, validation_alias="type", serialization_alias="type", description="Sets the event type. If your event isn't a `page` or `screen` type event, we automatically set this property to `event`.")
    timestamp: int | None = Field(None, description="The unix timestamp when the event took place. If you don't provide this value, we use the date-time when we receive the event.\n", json_schema_extra={'format': 'unix timestamp'})
    data: dict[str, Any] | None = Field(None, description="Additional information that you might want to reference in a message using liquid or use to set attributes on your customer (referenced by `customer_id`). You can include `from_address` and `reply_...")

class TrackAnonymousBodyV1(PermissiveModel):
    anonymous_id: str | None = Field(None, description="An identifier for an anonymous event, like a cookie. If set as an attribute on a person, any events bearing the same anonymous value are associated with this person. This value must be unique and i...")
    name: str = Field(..., description="The name of the event. In general, this should be the URL of the page a person visited, making it easy to segment your audience or trigger campaigns using this event. Make sure you trim leading and...")
    id_: str | None = Field(None, validation_alias="id", serialization_alias="id", description="An identifier used to deduplicate events. This value must be a [ULID](https://github.com/ulid/spec). If an event has the same value as an event we previously received, we won't show or process the ...", json_schema_extra={'format': 'ulid'})
    type_: Literal["page"] = Field(..., validation_alias="type", serialization_alias="type", description="Indicates that the event represents a page view. See [\"page view\" events](/integrations/data-in/connections/javascript/legacy-js/events/#page-view-events), for more information.")
    timestamp: int | None = Field(None, description="The unix timestamp when the event took place. If you don't provide this value, we use the date-time when we receive the event.\n", json_schema_extra={'format': 'unix timestamp'})
    data: dict[str, Any] | None = Field(None, description="Additional information that you might want to reference in a message using liquid or use to set attributes on your customer (referenced by `customer_id`).")

class TrackAnonymousBodyV2(PermissiveModel):
    anonymous_id: str | None = Field(None, description="An identifier for an anonymous event, like a cookie. If set as an attribute on a person, any events bearing the same anonymous value are associated with this person. This value must be unique and i...")
    name: str = Field(..., description="The name of the event. In general, this should be the name of the screen or deep link path that a person viewed, making it easy to segment your audience or trigger campaigns using this event. Make ...")
    id_: str | None = Field(None, validation_alias="id", serialization_alias="id", description="An identifier used to deduplicate events. This value must be a [ULID](https://github.com/ulid/spec). If an event has the same value as an event we previously received, we won't show or process the ...", json_schema_extra={'format': 'ulid'})
    type_: Literal["screen"] = Field(..., validation_alias="type", serialization_alias="type", description="Indicates that the event represents a mobile screen view. You can also capture screen events directly with [our iOS SDK](/integrations/sdk/ios/track-events/#screen-view-events).")
    timestamp: int | None = Field(None, description="The unix timestamp when the event took place. If you don't provide this value, we use the date-time when we receive the event.\n", json_schema_extra={'format': 'unix timestamp'})
    data: dict[str, Any] | None = Field(None, description="Additional information that you might want to reference in a message using liquid or use to set attributes on your customer (referenced by `customer_id`).")

class TrackBodyV0(PermissiveModel):
    name: str = Field(..., description="The name of the event. This is how you'll reference the event in campaigns or segments.")
    id_: str | None = Field(None, validation_alias="id", serialization_alias="id", description="An identifier used to deduplicate events. This value must be a [ULID](https://github.com/ulid/spec). If an event has the same value as an event we previously received, we won't show or process the ...", json_schema_extra={'format': 'ulid'})
    type_: Literal["event"] | None = Field(None, validation_alias="type", serialization_alias="type", description="Sets the event type. If your event isn't a `page` or `screen` type event, we automatically set this property to `event`.")
    timestamp: int | None = Field(None, description="The unix timestamp when the event took place. If you don't provide this value, we use the date-time when we receive the event.\n\n**NOTE**: Events with a timestamp in the past 72 hours can trigger ...", json_schema_extra={'format': 'unix timestamp'})
    data: dict[str, Any] | None = Field(None, description="Additional information that you might want to reference in a message using liquid or use to set attributes on your customer (referenced by `customer_id`).")

class TrackBodyV1(PermissiveModel):
    name: str = Field(..., description="The name of the event. This is how you'll reference the event in campaigns or segments.")
    id_: str | None = Field(None, validation_alias="id", serialization_alias="id", description="An identifier used to deduplicate events. This value must be a [ULID](https://github.com/ulid/spec). If an event has the same value as an event we previously received, we won't show or process the ...", json_schema_extra={'format': 'ulid'})
    type_: Literal["page"] = Field(..., validation_alias="type", serialization_alias="type", description="Indicates that the event represents a page view. See [\"page view\" events](/integrations/data-in/connections/javascript/legacy-js/events/#page-view-events), for more information.")
    timestamp: int | None = Field(None, description="The unix timestamp when the event took place. If you don't provide this value, we use the date-time when we receive the event.\n", json_schema_extra={'format': 'unix timestamp'})
    data: dict[str, Any] | None = Field(None, description="Additional information that you might want to reference in a message using liquid or use to set attributes on your customer (referenced by `customer_id`).")

class TrackBodyV2(PermissiveModel):
    anonymous_id: str = Field(..., description="An identifier for an anonymous event, like a cookie. If set as an attribute on a person, any events bearing the same anonymous value are associated with this person. This value must be unique and i...")
    name: str = Field(..., description="The name of the event. In general, this should be the name of the screen or deep link path that a person viewed, making it easy to segment your audience or trigger campaigns from these events. Make...")
    id_: str | None = Field(None, validation_alias="id", serialization_alias="id", description="An identifier used to deduplicate events. This value must be a [ULID](https://github.com/ulid/spec). If an event has the same value as an event we previously received, we won't show or process the ...", json_schema_extra={'format': 'ulid'})
    type_: Literal["screen"] = Field(..., validation_alias="type", serialization_alias="type", description="Indicates that the event represents a mobile screen view. You can also capture screen events directly with [our iOS SDK](/integrations/sdk/ios/track-events/#screen-view-events).")
    timestamp: int | None = Field(None, description="The unix timestamp when the event took place. If you don't provide this value, we use the date-time when we receive the event.\n", json_schema_extra={'format': 'unix timestamp'})
    data: dict[str, Any] | None = Field(None, description="Additional information that you might want to reference in a message using liquid or use to set attributes on your customer (referenced by `customer_id`).")

class TrackMetrics(PermissiveModel):
    """The base properties shared across multiple metric types."""
    delivery_id: str = Field(..., description="The CIO-Delivery-ID from the notification that you want to associate the `event` with.")
    timestamp: int | None = Field(None, description="The unix timestamp when the event occurred.", json_schema_extra={'format': 'unix timestamp'})

class MetricsBodyV0(PermissiveModel):
    delivery_id: str = Field(..., description="The CIO-Delivery-ID from the notification that you want to associate the `event` with.")
    timestamp: int | None = Field(None, description="The unix timestamp when the event occurred.", json_schema_extra={'format': 'unix timestamp'})
    metric: Literal["bounced", "clicked", "converted", "deferred", "delivered", "dropped", "opened", "spammed"] = Field(..., description="The email metric you want to report back to Customer.io.")
    recipient: str | None = Field(None, description="The email of the person who received the message.")
    reason: str | None = Field(None, description="For metrics indicating a failure (like `bounced`), this field provides the reason for the failure.")
    href: str | None = Field(None, description="For `clicked` metrics, this is the link the recipient clicked.")

class MetricsBodyV1(PermissiveModel):
    delivery_id: str = Field(..., description="The CIO-Delivery-ID from the notification that you want to associate the `event` with.")
    timestamp: int | None = Field(None, description="The unix timestamp when the event occurred.", json_schema_extra={'format': 'unix timestamp'})
    metric: Literal["clicked", "converted", "opened"] = Field(..., description="The type of device-side event you want to report back to Customer.io.")
    recipient: str | None = Field(None, description="The email address or ID of the recipient (depending on the value you use to target in-app messages).")
    href: str | None = Field(None, description="For `clicked` metrics, this is the link the recipient clicked.")

class MetricsBodyV2(PermissiveModel):
    delivery_id: str = Field(..., description="The CIO-Delivery-ID from the notification that you want to associate the `event` with.")
    timestamp: int | None = Field(None, description="The unix timestamp when the event occurred.", json_schema_extra={'format': 'unix timestamp'})
    metric: Literal["converted", "delivered", "opened"] = Field(..., description="The type of device-side event you want to report back to Customer.io.")
    recipient: str | None = Field(None, description="The device ID that the message was sent to.")

class MetricsBodyV3(PermissiveModel):
    delivery_id: str = Field(..., description="The CIO-Delivery-ID from the notification that you want to associate the `event` with.")
    timestamp: int | None = Field(None, description="The unix timestamp when the event occurred.", json_schema_extra={'format': 'unix timestamp'})
    metric: Literal["clicked", "converted", "delivered", "opened"] = Field(..., description="The metric you want to report back to Customer.io.")
    href: str | None = Field(None, description="For `clicked` metrics, this is the link the recipient clicked.")

class MetricsBodyV4(PermissiveModel):
    delivery_id: str = Field(..., description="The CIO-Delivery-ID from the notification that you want to associate the `event` with.")
    timestamp: int | None = Field(None, description="The unix timestamp when the event occurred.", json_schema_extra={'format': 'unix timestamp'})
    metric: Literal["bounced", "clicked", "delivered", "opened"] = Field(..., description="The SMS metric you want to report back to Customer.io.")
    recipient: int | None = Field(None, description="The phone number of the person who received the message.")
    reason: str | None = Field(None, description="For metrics indicating a failure (like `bounced`), this field provides the reason for the failure.")
    href: str | None = Field(None, description="For `clicked` metrics, this is the link the recipient clicked.")

class MetricsBodyV5(PermissiveModel):
    delivery_id: str = Field(..., description="The CIO-Delivery-ID from the notification that you want to associate the `event` with.")
    timestamp: int | None = Field(None, description="The unix timestamp when the event occurred.", json_schema_extra={'format': 'unix timestamp'})
    metric: Literal["bounced", "clicked", "converted", "deferred", "delivered", "dropped", "opened", "spammed"] = Field(..., description="The type of device-side event you want to report back to Customer.io.")
    reason: str | None = Field(None, description="For metrics indicating a failure (like `bounced`), this field provides the reason for the failure.")
    href: str | None = Field(None, description="For `clicked` metrics, this is the link the recipient clicked.")

class V2CioRelationshipsItemIdentifiersV0(PermissiveModel):
    id_: str | None = Field(None, validation_alias="id", serialization_alias="id")

class V2CioRelationshipsItemIdentifiersV1(PermissiveModel):
    email: str | None = None

class V2CioRelationshipsItemIdentifiersV2(PermissiveModel):
    cio_id: str | None = None

class V2CioRelationshipsItem(PermissiveModel):
    identifiers: V2CioRelationshipsItemIdentifiersV0 | V2CioRelationshipsItemIdentifiersV1 | V2CioRelationshipsItemIdentifiersV2 | None = None
    relationship_attributes: dict[str, Any] | None = Field(None, description="The attributes associated with a relationship. Passing null or an empty string removes the attribute from the relationship.\n")

class V2CioRelationships(PermissiveModel):
    """The people you want to associate with an object. Each object in the array represents a person."""
    value: list[V2CioRelationshipsItem] = Field(..., description="The people you want to associate with an object. Each object in the array represents a person.")

class ObjectAddRelationships(PermissiveModel):
    """Add relationships between an object and one or more people."""
    action: Literal["add_relationships"] = Field(..., description="This operation associates an object with one or more people.")
    cio_relationships: V2CioRelationships

class ObjectDeleteRelationships(PermissiveModel):
    """Delete relationships between an object and one or more people."""
    action: Literal["delete_relationships"] = Field(..., description="This operation deletes an object relationship from one or more people.")
    cio_relationships: V2CioRelationships

class ObjectIdentify(PermissiveModel):
    """The `action` determines the type of operation you want to perform with an object. If `identifiers.object_id` does not exist, we'll create a new object; if it exists, we'll update the object accordingly.
"""
    identifiers: ObjectIdentifyIdentifiersV0 | ObjectIdentifyIdentifiersV1 = Field(..., description="The identifiers for a custom object. When identifying a new object, you *must* use both the `object_type_id` and `object_id` (where `object_type_id` is an integer representing the type of object an...")
    type_: Literal["object"] = Field(..., validation_alias="type", serialization_alias="type", description="The operation modifies a single object—non person data.")
    action: Literal["identify"] = Field(..., description="Indicates that the operation will `identify` the the item of the specified `type`.")
    attributes: ObjectAttributes | None = None
    cio_relationships: V2CioRelationships | None = None


# ============================================================================
# Discriminated Union Type Aliases
# ============================================================================

PersonOperations = Annotated[
    IdentifyPerson | PersonDelete | PersonEvent | PersonScreen | PersonPage | PersonAddRelationships | PersonDeleteRelationships | PersonAddDevice | PersonDeleteDevice | PersonMerge | PersonSuppress | PersonUnsuppress,
    Field(discriminator="action")
]

ObjectOperations = Annotated[
    ObjectIdentify | ObjectIdentifyAnonymous | ObjectDelete | ObjectAddRelationships | ObjectDeleteRelationships,
    Field(discriminator="action")
]


# Rebuild models to resolve forward references (required for circular refs)
CioSubscriptionPreferences.model_rebuild()
DeliveryOperations.model_rebuild()
DeliveryOperationsAttributes.model_rebuild()
DeliveryOperationsIdentifiers.model_rebuild()
DeviceObject.model_rebuild()
DeviceObjectAttributes.model_rebuild()
DeviceObjectCommon.model_rebuild()
DeviceObjectCommonAttributes.model_rebuild()
IdentifyBodyCioRelationshipsRelationshipsItem.model_rebuild()
IdentifyBodyCioRelationshipsRelationshipsItemIdentifiersV0.model_rebuild()
IdentifyBodyCioRelationshipsRelationshipsItemIdentifiersV1.model_rebuild()
IdentifyPerson.model_rebuild()
IdentifyPersonAttributes.model_rebuild()
IdentifyPersonIdentifiersV0.model_rebuild()
IdentifyPersonIdentifiersV1.model_rebuild()
IdentifyPersonIdentifiersV2.model_rebuild()
IdentifyPersonV1Attributes.model_rebuild()
MergeBodyPrimaryV0.model_rebuild()
MergeBodyPrimaryV1.model_rebuild()
MergeBodyPrimaryV2.model_rebuild()
MergeBodySecondaryV0.model_rebuild()
MergeBodySecondaryV1.model_rebuild()
MergeBodySecondaryV2.model_rebuild()
MetricsBodyV0.model_rebuild()
MetricsBodyV1.model_rebuild()
MetricsBodyV2.model_rebuild()
MetricsBodyV3.model_rebuild()
MetricsBodyV4.model_rebuild()
MetricsBodyV5.model_rebuild()
ObjectAddRelationships.model_rebuild()
ObjectAttributes.model_rebuild()
ObjectCommon.model_rebuild()
ObjectCommonIdentifiersV0.model_rebuild()
ObjectCommonIdentifiersV1.model_rebuild()
ObjectCommonIdentify.model_rebuild()
ObjectCommonIdentifyIdentifiersV0.model_rebuild()
ObjectCommonIdentifyIdentifiersV1.model_rebuild()
ObjectDelete.model_rebuild()
ObjectDeleteRelationships.model_rebuild()
ObjectIdentifiers.model_rebuild()
ObjectIdentifiersIdentifiersV0.model_rebuild()
ObjectIdentifiersIdentifiersV1.model_rebuild()
ObjectIdentify.model_rebuild()
ObjectIdentifyAnonymous.model_rebuild()
ObjectIdentifyAnonymousCioRelationshipsItem.model_rebuild()
ObjectIdentifyAnonymousCioRelationshipsItemIdentifiers.model_rebuild()
ObjectIdentifyAnonymousIdentifiersV0.model_rebuild()
ObjectIdentifyAnonymousIdentifiersV1.model_rebuild()
ObjectIdentifyAnonymousV1CioRelationshipsItem.model_rebuild()
ObjectIdentifyAnonymousV1CioRelationshipsItemIdentifiers.model_rebuild()
ObjectIdentifyIdentifiersV0.model_rebuild()
ObjectIdentifyIdentifiersV1.model_rebuild()
ObjectRelationships.model_rebuild()
ObjectRelationshipsItem.model_rebuild()
ObjectRelationshipsItemIdentifiersV0.model_rebuild()
ObjectRelationshipsItemIdentifiersV1.model_rebuild()
PersonAddDevice.model_rebuild()
PersonAddDeviceDevice.model_rebuild()
PersonAddDeviceDeviceAttributes.model_rebuild()
PersonAddDeviceIdentifiersV0.model_rebuild()
PersonAddDeviceIdentifiersV1.model_rebuild()
PersonAddDeviceIdentifiersV2.model_rebuild()
PersonAddDeviceV1Device.model_rebuild()
PersonAddDeviceV1DeviceAttributes.model_rebuild()
PersonAddRelationships.model_rebuild()
PersonAddRelationshipsIdentifiersV0.model_rebuild()
PersonAddRelationshipsIdentifiersV1.model_rebuild()
PersonAddRelationshipsIdentifiersV2.model_rebuild()
PersonCommon.model_rebuild()
PersonCommonIdentifiersV0.model_rebuild()
PersonCommonIdentifiersV1.model_rebuild()
PersonCommonIdentifiersV2.model_rebuild()
PersonDelete.model_rebuild()
PersonDeleteDevice.model_rebuild()
PersonDeleteDeviceDevice.model_rebuild()
PersonDeleteDeviceIdentifiersV0.model_rebuild()
PersonDeleteDeviceIdentifiersV1.model_rebuild()
PersonDeleteDeviceIdentifiersV2.model_rebuild()
PersonDeleteDeviceV1Device.model_rebuild()
PersonDeleteIdentifiersV0.model_rebuild()
PersonDeleteIdentifiersV1.model_rebuild()
PersonDeleteIdentifiersV2.model_rebuild()
PersonDeleteRelationships.model_rebuild()
PersonDeleteRelationshipsIdentifiersV0.model_rebuild()
PersonDeleteRelationshipsIdentifiersV1.model_rebuild()
PersonDeleteRelationshipsIdentifiersV2.model_rebuild()
PersonEvent.model_rebuild()
PersonEventAttributes.model_rebuild()
PersonEventIdentifiersV0.model_rebuild()
PersonEventIdentifiersV1.model_rebuild()
PersonEventIdentifiersV2.model_rebuild()
PersonEventV1Attributes.model_rebuild()
PersonMerge.model_rebuild()
PersonMergePrimaryV0.model_rebuild()
PersonMergePrimaryV1.model_rebuild()
PersonMergePrimaryV2.model_rebuild()
PersonMergeSecondaryV0.model_rebuild()
PersonMergeSecondaryV1.model_rebuild()
PersonMergeSecondaryV2.model_rebuild()
PersonPage.model_rebuild()
PersonPageAttributes.model_rebuild()
PersonPageIdentifiersV0.model_rebuild()
PersonPageIdentifiersV1.model_rebuild()
PersonPageIdentifiersV2.model_rebuild()
PersonPageV1Attributes.model_rebuild()
PersonScreen.model_rebuild()
PersonScreenIdentifiersV0.model_rebuild()
PersonScreenIdentifiersV1.model_rebuild()
PersonScreenIdentifiersV2.model_rebuild()
PersonSuppress.model_rebuild()
PersonSuppressIdentifiersV0.model_rebuild()
PersonSuppressIdentifiersV1.model_rebuild()
PersonSuppressIdentifiersV2.model_rebuild()
PersonUnsuppress.model_rebuild()
PersonUnsuppressIdentifiersV0.model_rebuild()
PersonUnsuppressIdentifiersV1.model_rebuild()
PersonUnsuppressIdentifiersV2.model_rebuild()
RelationshipAttributes.model_rebuild()
SubmitFormBodyDataV0.model_rebuild()
SubmitFormBodyDataV1.model_rebuild()
TrackAnonymousBodyV0.model_rebuild()
TrackAnonymousBodyV1.model_rebuild()
TrackAnonymousBodyV2.model_rebuild()
TrackBodyV0.model_rebuild()
TrackBodyV1.model_rebuild()
TrackBodyV2.model_rebuild()
TrackMetrics.model_rebuild()
V2CioRelationships.model_rebuild()
V2CioRelationshipsItem.model_rebuild()
V2CioRelationshipsItemIdentifiersV0.model_rebuild()
V2CioRelationshipsItemIdentifiersV1.model_rebuild()
V2CioRelationshipsItemIdentifiersV2.model_rebuild()
