"""
Authentication module for BambooHR API MCP server.

Generated: 2026-03-25 23:00:53 UTC
@generated by MCP Blacksmith (https://mcpblacksmith.com)

This module contains:
1. Authentication class implementations (OAuth2)
2. Operation-to-auth requirements mapping (OPERATION_AUTH_MAP)
"""

from __future__ import annotations

import base64
import hashlib
import json
import logging
import os
import subprocess
import sys
import threading
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path
from typing import Any
from urllib.parse import parse_qs, urlparse

from authlib.common.security import generate_token
from authlib.integrations.httpx_client import OAuth2Client

logger = logging.getLogger(__name__)

__all__ = [
    "OAuth2Auth",
    "BasicAuth",
    "BearerTokenAuth",
    "APIKeyAuth",
    "OPERATION_AUTH_MAP",
]

# ============================================================================
# Callback Port Configuration
# ============================================================================

# OAuth2/OIDC callback server ports (configured in .env)
# Each auth scheme uses a different port to avoid conflicts when multiple
# schemes are active simultaneously (e.g., OAuth2 + OIDC).
OAUTH2_CALLBACK_PORT = int(os.environ.get("OAUTH2_CALLBACK_PORT", 9400))

# ============================================================================
# Authentication Classes
# ============================================================================

class OAuth2Auth:
    """
    OAuth 2.0 authentication for BambooHR API.

    Flow: authorizationCode
    Uses: authlib for OAuth2 protocol handling

    NOTE: Authorization scheme prefix ("Bearer ") is automatically inserted.
    Access tokens are obtained automatically through OAuth2 flow.

    Configuration (environment variables):
        - OAUTH2_CLIENT_ID: OAuth2 client ID (required)
        - OAUTH2_CLIENT_SECRET: OAuth2 client secret (required)
        - OAUTH2_SCOPES: Comma-separated scopes (required)
    Redirect URI:
        - Fixed: http://localhost:{OAUTH2_CALLBACK_PORT}/callback
        - Configured via OAUTH2_CALLBACK_PORT in .env (default: 9400)
        - Must match redirect URI in your OAuth application configuration
    Token Storage:
        Location: ./tokens/oauth2_tokens.json
        Permissions: 0o600 (owner read/write only)
        Format: JSON with access_token, refresh_token, expires_at

    URLs:
        Authorization URL: /authorize.php
        Token URL: /token.php

    Available Scopes (configure via OAUTH2_SCOPES):
        - access_level
        - benchmarking:compensation
        - background_checks
        - background_checks.write
        - benefit
        - benefit.write
        - company_file
        - company_file.write
        - company:info
        - company:details
        - company:administration
        - company:administration.write
        - data_cleaner
        - payroll
        - payroll.write
        - payroll:legal_entities
        - payroll:retirements
        - payroll:pay_schedules
        - payroll:pay_periods
        - payroll:pay_stubs
        - payroll:payrolls
        - employee:assets
        - employee:assets.write
        - employee:emergency_contacts
        - employee:emergency_contacts.write
        - employee:vaccination
        - employee:vaccination.write
        - employee:custom_fields
        - employee:custom_fields.write
        - employee:custom_fields_encrypted
        - employee:custom_fields_encrypted.write
        - employee:demographic
        - employee:demographic.write
        - employee:dependent
        - employee:dependent.write
        - employee:dependent:ssn
        - employee:dependent:ssn.write
        - employee:education
        - employee:education.write
        - employee:contact
        - employee:contact.write
        - employee:identification
        - employee:identification.write
        - employee:job
        - employee:job.write
        - employee:management
        - employee:management.write
        - employee:photo
        - employee:photo.write
        - employee
        - employee.write
        - employee:name
        - employee:name.write
        - employee_directory
        - employee:file
        - employee:file.write
        - employee:compensation
        - employee:compensation.write
        - employee:providers
        - employee:providers.write
        - employee:providers:payroll
        - employee:providers:payroll.write
        - sensitive_employee:protected_info
        - sensitive_employee:protected_info.write
        - sensitive_employee:address
        - sensitive_employee:address.write
        - sensitive_employee:creditcards
        - sensitive_employee:creditcards.write
        - employee:payroll.write
        - field
        - field.write
        - goal
        - goal.write
        - job_organization
        - job_organization.write
        - job_opening
        - job_opening.write
        - application
        - application.write
        - offline_access
        - openid
        - report
        - tasks
        - tasks.write
        - time_off
        - time_off.write
        - time_tracking
        - time_tracking.write
        - time_tracking:breaks
        - time_tracking:breaks.write
        - scheduling:schedules
        - scheduling:schedules.write
        - scheduling:shifts
        - scheduling:shifts.write
        - training
        - training.write
        - user
        - user:management
        - user:management.write
        - webhooks
        - webhooks.write
        - error_management
        - public.integration
        - public.user
        - gridlets
        - mcp
    """

    def __init__(self):
        """Initialize OAuth2 authentication with authlib."""
        # Store flow type for lifecycle management
        self.flow_type = "authorizationCode"

        # Load configuration from environment
        self.client_id = os.getenv("OAUTH2_CLIENT_ID", "").strip()
        self.client_secret = os.getenv("OAUTH2_CLIENT_SECRET", "").strip()

        # Validate required credentials
        if not self.client_id or not self.client_secret:
            raise ValueError(
                "OAUTH2_CLIENT_ID and OAUTH2_CLIENT_SECRET must be set. "
                "Leave empty in .env to disable OAuth2."
            )

        # Detect common placeholder patterns
        placeholders = ["placeholder", "your-", "example", "change-me", "todo"]
        if any(p in self.client_id.lower() for p in placeholders):
            raise ValueError(
                f"OAUTH2_CLIENT_ID appears to be a placeholder ({self.client_id[:20]}...). "
                "Please set real credentials or leave empty to disable OAuth2."
            )
        if any(p in self.client_secret.lower() for p in placeholders):
            raise ValueError(
                "OAUTH2_CLIENT_SECRET appears to be a placeholder. "
                "Please set real credentials or leave empty to disable OAuth2."
            )

        # Parse scopes from environment (required)
        scopes_env = os.getenv("OAUTH2_SCOPES", "").strip()
        self.scopes = [s.strip() for s in scopes_env.split(",") if s.strip()]
        # Redirect URI for authorization flows (hardcoded port, change in auth.py if needed)
        self.callback_port = OAUTH2_CALLBACK_PORT
        self.redirect_uri = f"http://localhost:{OAUTH2_CALLBACK_PORT}/callback"
        # OAuth2 endpoints from OpenAPI spec
        self.authorization_endpoint = "/authorize.php"
        self.token_endpoint = "/token.php"  # noqa: S105
        self.refresh_url = self.token_endpoint
        self.device_authorization_endpoint = None

        # Initialize authlib OAuth2Client
        self.client = OAuth2Client(
            client_id=self.client_id,
            client_secret=self.client_secret,
            scope=' '.join(self.scopes) if self.scopes else None,
            redirect_uri=self.redirect_uri,
            token_endpoint=self.token_endpoint,
            token_endpoint_auth_method='client_secret_post'  # noqa: S106
        )

        # Token storage path
        self._token_file = self._get_token_storage_path()

        # Load existing token from disk (if available)
        self._load_token()

    # ========================================================================
    # Token Persistence
    # ========================================================================

    def _get_token_storage_path(self) -> Path:
        """Get path to token storage file (tokens/ subdirectory for Docker volume mounts)."""
        tokens_dir = Path(__file__).parent / "tokens"
        tokens_dir.mkdir(exist_ok=True)
        return tokens_dir / "oauth2_tokens.json"

    def _load_token(self) -> None:
        """Load token from disk if it exists."""
        if not self._token_file.exists():
            logger.debug(f"No token file found: {self._token_file}")
            return

        try:
            with open(self._token_file) as f:
                token_data = json.load(f)

            # Give token to authlib client
            self.client.token = token_data

            logger.info(f"Loaded token from {self._token_file}")

        except Exception as e:
            logger.warning(f"Failed to load token: {e}")

    def _save_token(self, token: dict[str, Any]) -> None:
        """Save token to disk with secure permissions."""
        try:
            # Write token file
            with open(self._token_file, 'w') as f:
                json.dump(token, f, indent=2)

            # Set secure permissions (owner read/write only)
            self._token_file.chmod(0o600)

            logger.info(f"Saved token to {self._token_file}")

        except Exception as e:
            logger.error(f"Failed to save token: {e}")

    # ========================================================================
    # Token Acquisition (Flow-Specific)
    # ========================================================================

    def authorize(self, port: int | None = None, timeout: int = 300) -> dict[str, Any]:
        """
        Run authorization code flow with browser and local callback server.

        This method:
            1. Starts local HTTP server on localhost:{port}
            2. Generates authorization URL with PKCE
            3. Opens browser for user consent
            4. Waits for OAuth callback with authorization code
            5. Exchanges code for access + refresh tokens
            6. Saves tokens to disk

        Args:
            port: Local callback server port (default: from OAUTH2_CALLBACK_PORT env or 9400)
            timeout: Max seconds to wait for authorization (default: 300)

        Returns:
            Token dictionary from OAuth provider

        Raises:
            TimeoutError: If user doesn't complete authorization
            ValueError: If authorization fails
        """
        # Use configured port if not explicitly provided
        if port is None:
            port = self.callback_port

        # Update redirect URI for local server
        original_redirect = self.redirect_uri
        self.redirect_uri = f"http://localhost:{port}/callback"
        self.client.redirect_uri = self.redirect_uri

        # Generate PKCE code verifier and challenge
        code_verifier = generate_token(48)
        code_challenge = base64.urlsafe_b64encode(
            hashlib.sha256(code_verifier.encode()).digest()
        ).decode().rstrip('=')

        # Store code_verifier in client metadata for token exchange
        self.client.code_verifier = code_verifier  # type: ignore[attr-defined]

        # Generate authorization URL with PKCE
        auth_url, state = self.client.create_authorization_url(
            self.authorization_endpoint,
            code_challenge=code_challenge,
            code_challenge_method='S256',
            access_type='offline',  # Request refresh token
            prompt='consent'  # Force consent to ensure refresh token is returned
        )

        # Shared state for callback
        auth_code = None
        auth_error = None
        callback_complete = threading.Event()

        class CallbackHandler(BaseHTTPRequestHandler):
            def do_GET(self):
                nonlocal auth_code, auth_error, callback_complete

                query = parse_qs(urlparse(self.path).query)

                # Log callback URL for debugging
                logger.debug(f"OAuth callback received: {self.path}")
                logger.debug(f"Query parameters: {query}")

                if 'error' in query:
                    auth_error = f"{query['error'][0]}: {query.get('error_description', [''])[0]}"
                    logger.error(f"OAuth authorization failed: {auth_error}")
                    self.send_response(400)
                elif 'code' in query:
                    auth_code = query['code'][0]
                    logger.info(f"Authorization code received: {auth_code[:20]}...")
                    self.send_response(200)
                else:
                    auth_error = "No authorization code or error in callback"
                    logger.error(f"OAuth callback missing code/error: {query}")
                    self.send_response(400)

                self.send_header('Content-Type', 'text/html; charset=utf-8')
                self.end_headers()

                if auth_code:
                    html = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Authorization Successful</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
            background-color: #1a1a1a;
            color: #e8e8e8;
            display: flex;
            align-items: center;
            justify-content: center;
            min-height: 100vh;
        }
        .card {
            background: #242424;
            border: 1px solid #333;
            border-radius: 16px;
            padding: 48px 40px;
            text-align: center;
            max-width: 420px;
            width: 90%;
            box-shadow: 0 8px 32px rgba(0,0,0,0.4);
        }
        .logo { width: 64px; height: 64px; margin-bottom: 32px; border-radius: 12px; }
        h1 { font-size: 28px; font-weight: 600; margin-bottom: 10px; }
        p { font-size: 15px; color: #888; line-height: 1.5; }
        .footer { margin-top: 32px; padding-top: 20px; border-top: 1px solid #333; }
        .footer a { color: #ff5722; text-decoration: none; font-size: 13px; }
    </style>
</head>
<body>
    <div class="card">
        <img src="https://wjxawmrpsfuivlicnepc.supabase.co/storage/v1/object/public/newsletter/logo-blacksmith.png" alt="MCP Blacksmith" class="logo">
        <h1>Authorization successful</h1>
        <p>You can close this window.</p>
        <div class="footer"><a href="https://mcpblacksmith.com">mcpblacksmith.com</a></div>
    </div>
</body>
</html>"""
                    self.wfile.write(html.encode('utf-8'))
                else:
                    # Include error details in the failure page
                    error_details = auth_error if auth_error else "Unknown error"
                    html = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Authorization Failed</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
            background-color: #1a1a1a;
            color: #e8e8e8;
            display: flex;
            align-items: center;
            justify-content: center;
            min-height: 100vh;
        }
        .card {
            background: #242424;
            border: 1px solid #333;
            border-radius: 16px;
            padding: 48px 40px;
            text-align: center;
            max-width: 420px;
            width: 90%;
            box-shadow: 0 8px 32px rgba(0,0,0,0.4);
        }
        .logo { width: 64px; height: 64px; margin-bottom: 32px; border-radius: 12px; }
        h1 { font-size: 28px; font-weight: 600; margin-bottom: 10px; color: #ef4444; }
        p { font-size: 15px; color: #888; line-height: 1.5; }
        .error-details {
            font-size: 13px; color: #ff8787; font-family: 'SF Mono', Monaco, monospace;
            background: #1a1a1a; padding: 12px 16px; border-radius: 8px;
            margin-top: 16px; word-break: break-word; text-align: left;
            border: 1px solid #333;
        }
        .footer { margin-top: 32px; padding-top: 20px; border-top: 1px solid #333; }
        .footer a { color: #ff5722; text-decoration: none; font-size: 13px; }
    </style>
</head>
<body>
    <div class="card">
        <img src="https://wjxawmrpsfuivlicnepc.supabase.co/storage/v1/object/public/newsletter/logo-blacksmith.png" alt="MCP Blacksmith" class="logo">
        <h1>Authorization failed</h1>
        <p>The OAuth2 authorization could not be completed.</p>
        <div class="error-details">""" + error_details + """</div>
        <div class="footer"><a href="https://mcpblacksmith.com">mcpblacksmith.com</a></div>
    </div>
</body>
</html>"""
                    self.wfile.write(html.encode('utf-8'))

                callback_complete.set()

            def log_message(self, format: str, *args: object) -> None:  # noqa: A002
                pass  # Suppress logs

        # Start callback server (bind 0.0.0.0 so Docker port-mapping works)
        server = HTTPServer(('0.0.0.0', port), CallbackHandler)  # noqa: S104
        server_thread = threading.Thread(target=server.serve_forever, daemon=True)
        server_thread.start()

        try:
            logger.info("Opening browser for authorization...")
            print(f"\nAuthorize this application by visiting:\n\n  {auth_url}\n")

            # Try to open browser automatically (skip in headless/Docker environments)
            if os.environ.get("DISPLAY") or sys.platform in ('win32', 'darwin'):
                try:
                    if sys.platform == 'win32':
                        subprocess.run(['cmd', '/c', 'start', '', auth_url], check=False)  # noqa: S603 S607
                    elif sys.platform == 'darwin':
                        subprocess.run(['open', auth_url], check=False)  # noqa: S603 S607
                    else:  # Linux
                        subprocess.run(['xdg-open', auth_url], check=False)  # noqa: S603 S607
                except Exception as e:
                    logger.debug(f"Browser launcher failed: {e}")
            else:
                logger.info("Headless environment detected — open the URL above in your browser")
                print("Waiting for authorization...\n")

            # Wait for callback
            if not callback_complete.wait(timeout=timeout):
                raise TimeoutError(f"Authorization timed out after {timeout}s")

            if auth_error:
                raise ValueError(f"Authorization failed: {auth_error}")

            if not auth_code:
                raise ValueError("No authorization code received")

            # Exchange code for token with PKCE verification
            logger.info("Exchanging authorization code for token (PKCE enabled)")
            token = self.client.fetch_token(
                self.token_endpoint,
                authorization_response=f"{self.redirect_uri}?code={auth_code}",
                code_verifier=code_verifier  # Include PKCE verifier
            )

            # Save token
            self._save_token(token)

            logger.info("Authorization successful")
            return token

        finally:
            server.shutdown()
            self.redirect_uri = original_redirect
            self.client.redirect_uri = original_redirect


    # ========================================================================
    # Token Refresh
    # ========================================================================

    def _refresh_token(self) -> dict[str, Any]:
        """
        Refresh access token using refresh token.

        Returns:
            New token dictionary

        Raises:
            ValueError: If refresh fails

        Note:
            authlib automatically handles refresh token logic
        """
        if not self.client.token or 'refresh_token' not in self.client.token:
            raise ValueError("No refresh token available")

        logger.info("Refreshing access token...")

        try:
            # authlib handles refresh automatically
            token = self.client.refresh_token(
                self.refresh_url or self.token_endpoint
            )

            # Save new token
            self._save_token(token)

            logger.info("Token refreshed successfully")
            return token

        except Exception as e:
            logger.error(f"Token refresh failed: {e}")
            raise ValueError(f"Token refresh failed: {e}") from e

    # ========================================================================
    # Main Entry Point (Called before every API request)
    # ========================================================================

    def get_auth_headers(self) -> dict[str, str]:
        """
        Get authentication headers for API requests.

        Token lifecycle:
            1. Check if token exists → acquire if missing
            2. Check if token expires soon → refresh proactively (5-min buffer)
            3. Return Authorization header

        Returns:
            Dictionary with Authorization header

        Raises:
            ValueError: If token acquisition/refresh fails

        Note:
            This method is called before EVERY API request.
            authlib handles token expiration checking automatically.
        """
        # Ensure we have a token
        if not self.client.token:
            # Interactive flows require browser authorization
            logger.info("No token found - authorization required")
            self.authorize()

        # Check if token needs refresh (authlib provides is_expired())
        # Refresh proactively if expires in < 300 seconds (5 minutes)
        if self.client.token.is_expired(leeway=300):
            logger.info("Token expires soon - refreshing proactively")
            # For authorization code flow: always try refresh, raise on failure
            try:
                self._refresh_token()
            except Exception as e:
                raise ValueError(
                    f"Token refresh failed: {e}. "
                    "Please restart server or call authorize() manually."
                ) from e

        # Return authorization header
        return {
            'Authorization': f"Bearer {self.client.token['access_token']}",
            'Content-Type': 'application/json'
        }
class BasicAuth:
    """
    HTTP Basic Authentication for BambooHR API.

    Configuration:
        Credentials are automatically Base64-encoded.
        Provide raw username and password via environment variables.

    Security Note:
        Basic Auth transmits credentials in Base64 encoding (NOT encryption).
        Always use HTTPS to protect credentials in transit.
    """

    def __init__(self, env_var_username: str = "BASIC_AUTH_USERNAME",
                 env_var_password: str = "BASIC_AUTH_PASSWORD"):
        """Initialize Basic Auth from environment variables.

        Args:
            env_var_username: Environment variable name for the username.
            env_var_password: Environment variable name for the password.
        """
        self.username = os.getenv(env_var_username, "").strip()
        self.password = os.getenv(env_var_password, "").strip()

        # Check for empty or placeholder values
        if not self.username or not self.password:
            raise ValueError(
                f"Both {env_var_username} and {env_var_password} environment variables must be set. "
                "Leave empty in .env to disable Basic Auth."
            )

        # Detect common placeholder patterns
        placeholders = ["placeholder", "your-", "example", "change-me", "todo"]
        username_lower = self.username.lower()
        password_lower = self.password.lower()

        if any(p in username_lower or p in password_lower for p in placeholders):
            raise ValueError(
                f"Basic Auth credentials appear to be placeholders (username: {self.username[:20]}...). "
                "Please set real credentials or leave empty to disable Basic Auth."
            )

    def get_auth_headers(self) -> dict[str, str]:
        """Get authentication headers with Basic Auth credentials."""
        # Encode credentials
        credentials = f"{self.username}:{self.password}"
        encoded_credentials = base64.b64encode(credentials.encode('utf-8')).decode('utf-8')

        return {
            'Authorization': f'Basic {encoded_credentials}',
            'Content-Type': 'application/json'
        }
class BearerTokenAuth:
    """
    Bearer token authentication for BambooHR API.

    Configuration:
        Provide the raw token in the environment variable.
        The authorization scheme prefix is automatically inserted.
    """

    def __init__(self, env_var: str = "BEARER_TOKEN", token_format: str = "Bearer"):
        """Initialize bearer token authentication from environment variable.

        Args:
            env_var: Environment variable name containing the bearer token.
            token_format: Authorization scheme prefix (e.g., 'Bearer').
        """
        self.token_format = token_format
        self.token = os.getenv(env_var, "").strip()

        # Check for empty token
        if not self.token:
            raise ValueError(
                f"{env_var} environment variable not set. "
                "Leave empty in .env to disable Bearer Token auth."
            )

        # Detect common placeholder patterns
        placeholders = ["placeholder", "your-", "example", "change-me", "todo", "sk_test_placeholder"]
        token_lower = self.token.lower()

        if any(p in token_lower for p in placeholders):
            raise ValueError(
                f"Bearer token appears to be a placeholder ({self.token[:20]}...). "
                "Please set a real token or leave empty to disable Bearer Token auth."
            )

    def get_auth_headers(self) -> dict[str, str]:
        """Get authentication headers for API requests."""
        return {
            'Authorization': f'{self.token_format} {self.token}'
        }
class APIKeyAuth:
    """
    API Key authentication for BambooHR API.

    Supports header, query parameter, and cookie-based API key injection.
    Configure location and parameter name via constructor arguments.
    """

    def __init__(self, env_var: str = "API_KEY", location: str = "header",
                 param_name: str = "Authorization", prefix: str = ""):
        """Initialize API key authentication from environment variable.

        Args:
            env_var: Environment variable name containing the API key.
            location: Where to inject the key - 'header', 'query', or 'cookie'.
            param_name: Name of the header, query parameter, or cookie.
            prefix: Optional prefix before the key value (e.g., 'Bearer').
        """
        self.location = location
        self.param_name = param_name
        self.prefix = prefix
        self.api_key = os.getenv(env_var, "").strip()

        # Check for empty API key
        if not self.api_key:
            raise ValueError(
                f"{env_var} environment variable not set. "
                "Leave empty in .env to disable API Key auth."
            )

        # Detect common placeholder patterns
        placeholders = ["placeholder", "your-", "example", "change-me", "todo", "bot placeholder"]
        api_key_lower = self.api_key.lower()

        if any(p in api_key_lower for p in placeholders):
            raise ValueError(
                f"API key appears to be a placeholder ({self.api_key[:20]}...). "
                "Please set a real API key or leave empty to disable API Key auth."
            )

    def get_auth_headers(self) -> dict[str, str]:
        """Get authentication headers for API requests."""
        if self.location != "header":
            return {}
        if self.param_name == "Authorization":
            prefix = self.prefix + " " if self.prefix else "Bearer "
            return {"Authorization": f"{prefix}{self.api_key}"}
        value = f"{self.prefix} {self.api_key}" if self.prefix else self.api_key
        return {self.param_name: value}

    def get_auth_params(self) -> dict[str, str]:
        """Get authentication query parameters."""
        if self.location != "query":
            return {}
        return {self.param_name: self.api_key}

    def get_auth_cookies(self) -> dict[str, str]:
        """Get authentication cookies."""
        if self.location != "cookie":
            return {}
        return {self.param_name: self.api_key}

# ============================================================================
# Operation Auth Requirements Map
# ============================================================================

"""
Operation-to-authentication requirements mapping.

This dictionary defines which authentication schemes are required for each operation,
using OR/AND relationships (outer list = OR, inner list = AND).
"""
OPERATION_AUTH_MAP: dict[str, list[list[str]]] = {
    "create_project": [["oauth"], ["basic"]],
    "list_break_assessments": [["oauth"], ["basic"]],
    "get_break": [["oauth"], ["basic"]],
    "update_break": [["oauth"], ["basic"]],
    "delete_break": [["oauth"], ["basic"]],
    "list_break_policy_breaks": [["oauth"], ["basic"]],
    "create_break": [["oauth"], ["basic"]],
    "replace_break_policy_breaks": [["oauth"], ["basic"]],
    "assign_employees_to_break_policy": [["oauth"], ["basic"]],
    "assign_break_policy_employees": [["oauth"], ["basic"]],
    "unassign_employees_from_break_policy": [["oauth"], ["basic"]],
    "get_break_policy": [["oauth"], ["basic"]],
    "update_break_policy": [["oauth"], ["basic"]],
    "delete_break_policy": [["oauth"], ["basic"]],
    "list_break_policies": [["oauth"], ["basic"]],
    "create_break_policy": [["oauth"], ["basic"]],
    "list_employee_break_availabilities": [["oauth"], ["basic"]],
    "list_employee_break_policies": [["oauth"], ["basic"]],
    "list_break_policy_employees": [["oauth"], ["basic"]],
    "replace_break_policy": [["oauth"], ["basic"]],
    "delete_clock_entries": [["oauth"], ["basic"]],
    "delete_hour_entries": [["oauth"], ["basic"]],
    "list_timesheet_entries": [["oauth"], ["basic"]],
    "clock_in_employee": [["oauth"], ["basic"]],
    "clock_out_employee": [["oauth"], ["basic"]],
    "bulk_upsert_clock_entries": [["oauth"], ["basic"]],
    "bulk_upsert_timesheet_entries": [["oauth"], ["basic"]],
    "list_webhooks": [["oauth"], ["basic"]],
    "create_webhook": [["oauth"], ["basic"]],
    "get_webhook": [["oauth"], ["basic"]],
    "update_webhook": [["oauth"], ["basic"]],
    "delete_webhook": [["oauth"], ["basic"]],
    "list_webhook_logs": [["oauth"], ["basic"]],
    "list_webhook_monitor_fields": [["oauth"], ["basic"]],
    "list_webhook_post_fields": [["oauth"], ["basic"]],
    "query_dataset": [["oauth"], ["basic"]],
    "get_custom_report": [["oauth"], ["basic"]],
    "list_datasets": [["oauth"], ["basic"]],
    "list_dataset_fields": [["oauth"], ["basic"]],
    "list_custom_reports": [["oauth"], ["basic"]],
    "get_field_options": [["oauth"], ["basic"]],
    "list_datasets_v1_2": [["oauth"], ["basic"]],
    "list_dataset_fields_v1_2": [["oauth"], ["basic"]],
    "get_field_options_rfc7807": [["oauth"], ["basic"]],
    "list_applications": [["oauth"], ["basic"]],
    "list_applicant_statuses": [["oauth"], ["basic"]],
    "list_job_locations": [["oauth"], ["basic"]],
    "list_hiring_leads": [["oauth"], ["basic"]],
    "create_candidate": [["oauth"], ["basic"]],
    "create_job_opening": [["oauth"], ["basic"]],
    "list_company_benefits": [["oauth"], ["basic"]],
    "list_employee_benefits": [["oauth"], ["basic"]],
    "list_member_benefit_events": [["oauth"], ["basic"]],
    "list_member_benefits": [["oauth"], ["basic"]],
    "list_benefit_deduction_types": [["oauth"], ["basic"]],
    "get_company_profile": [["oauth"], ["basic"]],
    "list_enabled_integrations": [["oauth"], ["basic"]],
    "list_employees": [["oauth"]],
    "create_employee": [["oauth"], ["basic"]],
    "update_employee_table_row": [["oauth"], ["basic"]],
    "delete_employee_table_row": [["oauth"], ["basic"]],
    "download_company_file": [["oauth"], ["basic"]],
    "update_company_file": [["oauth"], ["basic"]],
    "delete_company_file": [["oauth"], ["basic"]],
    "download_employee_file": [["oauth"], ["basic"]],
    "update_employee_file": [["oauth"], ["basic"]],
    "delete_employee_file": [["oauth"], ["basic"]],
    "list_employee_goals": [["oauth"], ["basic"]],
    "create_employee_goal": [["oauth"], ["basic"]],
    "delete_employee_goal": [["oauth"], ["basic"]],
    "update_goal_progress": [["oauth"], ["basic"]],
    "update_milestone_progress": [["oauth"], ["basic"]],
    "set_goal_sharing": [["oauth"], ["basic"]],
    "check_goal_creation_permission": [["oauth"], ["basic"]],
    "list_goal_share_options": [["oauth"], ["basic"]],
    "list_goal_comments": [["oauth"], ["basic"]],
    "add_goal_comment": [["oauth"], ["basic"]],
    "update_goal_comment": [["oauth"], ["basic"]],
    "delete_goal_comment": [["oauth"], ["basic"]],
    "get_goal_aggregate": [["oauth"], ["basic"]],
    "list_goal_alignment_options": [["oauth"], ["basic"]],
    "close_goal": [["oauth"], ["basic"]],
    "reopen_goal": [["oauth"], ["basic"]],
    "update_goal_with_milestones": [["oauth"], ["basic"]],
    "get_goal_filters": [["oauth"], ["basic"]],
    "get_employee_goals_aggregate": [["oauth"], ["basic"]],
    "get_time_tracking_record": [["oauth"], ["basic"]],
    "create_time_entry": [["oauth"], ["basic"]],
    "upsert_hour_records": [["oauth"], ["basic"]],
    "update_time_entry": [["oauth"], ["basic"]],
    "delete_time_tracking_record": [["oauth"], ["basic"]],
    "list_country_states": [["oauth"], ["basic"]],
    "list_countries": [["oauth"], ["basic"]],
    "list_timezones": [],
    "list_employee_fields": [["oauth"], ["basic"]],
    "list_users": [["oauth"], ["basic"]],
    "get_employee": [["oauth"], ["basic"]],
    "update_employee": [["oauth"], ["basic"]],
    "list_changed_employee_table_rows": [["oauth"], ["basic"]],
    "list_employee_table_rows": [["oauth"], ["basic"]],
    "create_employee_table_row": [["oauth"], ["basic"]],
    "update_employee_table_row_v1_1": [["oauth"], ["basic"]],
    "create_employee_table_row_v1_1": [["oauth"], ["basic"]],
    "list_changed_employees": [["oauth"], ["basic"]],
    "get_employee_photo": [["oauth"], ["basic"]],
    "create_employee_file_categories": [["oauth"], ["basic"]],
    "create_file_categories": [["oauth"], ["basic"]],
    "upload_employee_file": [["oauth"], ["basic"]],
    "upload_file": [["oauth"], ["basic"]],
    "list_employee_time_off_policies": [["oauth"], ["basic"]],
    "assign_employee_time_off_policies": [["oauth"], ["basic"]],
    "list_employee_time_off_policies_extended": [["oauth"], ["basic"]],
    "assign_time_off_policies": [["oauth"], ["basic"]],
    "get_application": [["oauth"], ["basic"]],
    "add_application_comment": [["oauth"], ["basic"]],
    "list_jobs": [["oauth"], ["basic"]],
    "update_application_status": [["oauth"], ["basic"]],
    "list_benefit_coverages": [["oauth"], ["basic"]],
    "get_employee_dependent": [["oauth"], ["basic"]],
    "update_dependent": [["oauth"], ["basic"]],
    "list_employee_dependents": [["oauth"], ["basic"]],
    "create_employee_dependent": [["oauth"], ["basic"]],
    "get_employee_directory": [["oauth"], ["basic"]],
    "list_company_files": [["oauth"], ["basic"]],
    "list_employee_files": [["oauth"], ["basic"]],
    "list_list_fields": [["oauth"], ["basic"]],
    "update_list_field_options": [["oauth"], ["basic"]],
    "list_tabular_fields": [["oauth"], ["basic"]],
    "get_employee_time_off_balance": [["oauth"], ["basic"]],
    "create_time_off_history_entry": [["oauth"], ["basic"]],
    "adjust_time_off_balance": [["oauth"], ["basic"]],
    "list_time_off_policies": [["oauth"], ["basic"]],
    "create_time_off_request": [["oauth"], ["basic"]],
    "update_time_off_request_status": [["oauth"], ["basic"]],
    "list_time_off_requests": [["oauth"], ["basic"]],
    "list_time_off_types": [["oauth"], ["basic"]],
    "list_training_types": [["oauth"], ["basic"]],
    "create_training_type": [["oauth"], ["basic"]],
    "update_training_type": [["oauth"], ["basic"]],
    "delete_training_type": [["oauth"], ["basic"]],
    "list_training_categories": [["oauth"], ["basic"]],
    "create_training_category": [["oauth"], ["basic"]],
    "update_training_category": [["oauth"], ["basic"]],
    "delete_training_category": [["oauth"], ["basic"]],
    "list_employee_training_records": [["oauth"], ["basic"]],
    "create_employee_training_record": [["oauth"], ["basic"]],
    "update_training_record": [["oauth"], ["basic"]],
    "delete_training_record": [["oauth"], ["basic"]],
    "upload_employee_photo": [["oauth"], ["basic"]],
    "list_whos_out": [["oauth"], ["basic"]]
}
