"""
Authentication module for Rootly MCP server.

Generated: 2026-04-23 21:09:28 UTC
Generator: MCP Blacksmith v1.1.0 (https://mcpblacksmith.com)

This module contains:
1. Authentication class implementations (OAuth2)
2. Operation-to-auth requirements mapping (OPERATION_AUTH_MAP)
"""

from __future__ import annotations

import logging
import os

logger = logging.getLogger(__name__)

__all__ = [
    "BearerTokenAuth",
    "OPERATION_AUTH_MAP",
]

# ============================================================================
# Authentication Classes
# ============================================================================

class BearerTokenAuth:
    """
    Bearer token authentication for Rootly API v1.

    Configuration:
        Provide the raw token in the environment variable.
        The authorization scheme prefix is automatically inserted.
    """

    def __init__(self, env_var: str = "BEARER_TOKEN", token_format: str = "Bearer"):
        """Initialize bearer token authentication from environment variable.

        Args:
            env_var: Environment variable name containing the bearer token.
            token_format: Authorization scheme prefix (e.g., 'Bearer').
        """
        self.token_format = token_format
        self.token = os.getenv(env_var, "").strip()

        # Check for empty token
        if not self.token:
            raise ValueError(
                f"{env_var} environment variable not set. "
                "Leave empty in .env to disable Bearer Token auth."
            )

        # Detect common placeholder patterns
        placeholders = ["placeholder", "your-", "example", "change-me", "todo", "sk_test_placeholder"]
        token_lower = self.token.lower()

        if any(p in token_lower for p in placeholders):
            raise ValueError(
                f"Bearer token appears to be a placeholder ({self.token[:20]}...). "
                "Please set a real token or leave empty to disable Bearer Token auth."
            )

    def get_auth_headers(self) -> dict[str, str]:
        """Get authentication headers for API requests."""
        return {
            'Authorization': f'{self.token_format} {self.token}'
        }


# ============================================================================
# Operation Auth Requirements Map
# ============================================================================

"""
Operation-to-authentication requirements mapping.

This dictionary defines which authentication schemes are required for each operation,
using OR/AND relationships (outer list = OR, inner list = AND).
"""
OPERATION_AUTH_MAP: dict[str, list[list[str]]] = {
    "list_alert_events": [["bearer_auth"]],
    "create_alert_event": [["bearer_auth"]],
    "get_alert_event": [["bearer_auth"]],
    "update_alert_event": [["bearer_auth"]],
    "delete_alert_event": [["bearer_auth"]],
    "list_alert_groups": [["bearer_auth"]],
    "create_alert_group": [["bearer_auth"]],
    "get_alert_group": [["bearer_auth"]],
    "update_alert_group": [["bearer_auth"]],
    "delete_alert_group": [["bearer_auth"]],
    "list_alert_urgencies": [["bearer_auth"]],
    "create_alert_urgency": [["bearer_auth"]],
    "get_alert_urgency": [["bearer_auth"]],
    "update_alert_urgency": [["bearer_auth"]],
    "delete_alert_urgency": [["bearer_auth"]],
    "list_alert_sources": [["bearer_auth"]],
    "create_alert_source": [["bearer_auth"]],
    "get_alert_source": [["bearer_auth"]],
    "update_alert_source": [["bearer_auth"]],
    "delete_alert_source": [["bearer_auth"]],
    "list_incident_alerts": [["bearer_auth"]],
    "attach_alerts_to_incident": [["bearer_auth"]],
    "list_alerts": [["bearer_auth"]],
    "create_alert": [["bearer_auth"]],
    "get_alert": [["bearer_auth"]],
    "update_alert": [["bearer_auth"]],
    "acknowledge_alert": [["bearer_auth"]],
    "resolve_alert": [["bearer_auth"]],
    "list_audits": [["bearer_auth"]],
    "get_authorization": [["bearer_auth"]],
    "delete_authorization": [["bearer_auth"]],
    "list_catalog_entities": [["bearer_auth"]],
    "create_catalog_entity": [["bearer_auth"]],
    "get_catalog_entity": [["bearer_auth"]],
    "update_catalog_entity": [["bearer_auth"]],
    "delete_catalog_entity": [["bearer_auth"]],
    "list_catalog_entity_properties": [["bearer_auth"]],
    "create_catalog_entity_property": [["bearer_auth"]],
    "get_catalog_entity_property": [["bearer_auth"]],
    "update_catalog_entity_property": [["bearer_auth"]],
    "delete_catalog_entity_property": [["bearer_auth"]],
    "list_catalog_fields": [["bearer_auth"]],
    "create_catalog_field": [["bearer_auth"]],
    "get_catalog_field": [["bearer_auth"]],
    "update_catalog_field": [["bearer_auth"]],
    "delete_catalog_field": [["bearer_auth"]],
    "list_catalogs": [["bearer_auth"]],
    "create_catalog": [["bearer_auth"]],
    "get_catalog": [["bearer_auth"]],
    "update_catalog": [["bearer_auth"]],
    "delete_catalog": [["bearer_auth"]],
    "list_causes": [["bearer_auth"]],
    "create_cause": [["bearer_auth"]],
    "get_cause": [["bearer_auth"]],
    "update_cause": [["bearer_auth"]],
    "delete_cause": [["bearer_auth"]],
    "list_custom_forms": [["bearer_auth"]],
    "create_custom_form": [["bearer_auth"]],
    "get_custom_form": [["bearer_auth"]],
    "update_custom_form": [["bearer_auth"]],
    "delete_custom_form": [["bearer_auth"]],
    "list_dashboard_panels": [["bearer_auth"]],
    "create_dashboard_panel": [["bearer_auth"]],
    "duplicate_dashboard_panel": [["bearer_auth"]],
    "get_dashboard_panel": [["bearer_auth"]],
    "update_dashboard_panel": [["bearer_auth"]],
    "delete_dashboard_panel": [["bearer_auth"]],
    "list_dashboards": [["bearer_auth"]],
    "create_dashboard": [["bearer_auth"]],
    "duplicate_dashboard": [["bearer_auth"]],
    "set_dashboard_as_default": [["bearer_auth"]],
    "get_dashboard": [["bearer_auth"]],
    "update_dashboard": [["bearer_auth"]],
    "delete_dashboard": [["bearer_auth"]],
    "list_environments": [["bearer_auth"]],
    "create_environment": [["bearer_auth"]],
    "get_environment": [["bearer_auth"]],
    "update_environment": [["bearer_auth"]],
    "delete_environment": [["bearer_auth"]],
    "list_escalation_policies": [["bearer_auth"]],
    "create_escalation_policy": [["bearer_auth"]],
    "get_escalation_policy": [["bearer_auth"]],
    "update_escalation_policy": [["bearer_auth"]],
    "delete_escalation_policy": [["bearer_auth"]],
    "list_escalation_levels": [["bearer_auth"]],
    "create_escalation_level": [["bearer_auth"]],
    "list_escalation_levels_for_escalation_path": [["bearer_auth"]],
    "create_escalation_level_path": [["bearer_auth"]],
    "get_escalation_level": [["bearer_auth"]],
    "update_escalation_level": [["bearer_auth"]],
    "delete_escalation_level": [["bearer_auth"]],
    "list_escalation_paths": [["bearer_auth"]],
    "get_escalation_path": [["bearer_auth"]],
    "update_escalation_path": [["bearer_auth"]],
    "delete_escalation_path": [["bearer_auth"]],
    "list_form_field_options": [["bearer_auth"]],
    "add_form_field_option": [["bearer_auth"]],
    "get_form_field_option": [["bearer_auth"]],
    "update_form_field_option": [["bearer_auth"]],
    "delete_form_field_option": [["bearer_auth"]],
    "list_form_field_placement_conditions": [["bearer_auth"]],
    "delete_form_field_placement_condition": [["bearer_auth"]],
    "list_form_field_placements": [["bearer_auth"]],
    "create_form_field_placement": [["bearer_auth"]],
    "list_form_field_positions": [["bearer_auth"]],
    "create_form_field_position": [["bearer_auth"]],
    "get_form_field_position": [["bearer_auth"]],
    "list_form_fields": [["bearer_auth"]],
    "create_form_field": [["bearer_auth"]],
    "get_form_field": [["bearer_auth"]],
    "update_form_field": [["bearer_auth"]],
    "delete_form_field": [["bearer_auth"]],
    "list_form_set_conditions": [["bearer_auth"]],
    "create_form_set_condition": [["bearer_auth"]],
    "get_form_set_condition": [["bearer_auth"]],
    "update_form_set_condition": [["bearer_auth"]],
    "delete_form_set_condition": [["bearer_auth"]],
    "list_form_sets": [["bearer_auth"]],
    "create_form_set": [["bearer_auth"]],
    "get_form_set": [["bearer_auth"]],
    "update_form_set": [["bearer_auth"]],
    "delete_form_set": [["bearer_auth"]],
    "list_functionalities": [["bearer_auth"]],
    "create_functionality": [["bearer_auth"]],
    "get_functionality": [["bearer_auth"]],
    "update_functionality": [["bearer_auth"]],
    "delete_functionality": [["bearer_auth"]],
    "get_functionality_incidents_chart": [["bearer_auth"]],
    "get_functionality_uptime_chart": [["bearer_auth"]],
    "list_workflow_tasks": [["bearer_auth"]],
    "create_workflow_task": [["bearer_auth"]],
    "get_workflow_task": [["bearer_auth"]],
    "update_workflow_task": [["bearer_auth"]],
    "delete_workflow_task": [["bearer_auth"]],
    "list_workflow_form_field_conditions": [["bearer_auth"]],
    "get_workflow_form_field_condition": [["bearer_auth"]],
    "list_workflow_groups": [["bearer_auth"]],
    "get_workflow_group": [["bearer_auth"]],
    "update_workflow_group": [["bearer_auth"]],
    "delete_workflow_group": [["bearer_auth"]],
    "list_workflow_runs": [["bearer_auth"]],
    "create_workflow_run": [["bearer_auth"]],
    "get_workflow": [["bearer_auth"]],
    "delete_workflow": [["bearer_auth"]],
    "list_heartbeats": [["bearer_auth"]],
    "create_heartbeat": [["bearer_auth"]],
    "get_heartbeat": [["bearer_auth"]],
    "update_heartbeat": [["bearer_auth"]],
    "delete_heartbeat": [["bearer_auth"]],
    "list_incident_action_items": [["bearer_auth"]],
    "create_incident_action_item": [["bearer_auth"]],
    "get_incident_action_item": [["bearer_auth"]],
    "update_incident_action_item": [["bearer_auth"]],
    "delete_incident_action_item": [["bearer_auth"]],
    "list_action_items": [["bearer_auth"]],
    "list_incident_event_functionalities": [["bearer_auth"]],
    "add_functionality_to_incident_event": [["bearer_auth"]],
    "get_incident_event_functionality": [["bearer_auth"]],
    "update_incident_event_functionality": [["bearer_auth"]],
    "delete_incident_event_functionality": [["bearer_auth"]],
    "list_incident_event_services": [["bearer_auth"]],
    "add_service_to_incident_event": [["bearer_auth"]],
    "get_incident_event_service": [["bearer_auth"]],
    "update_incident_event_service_status": [["bearer_auth"]],
    "delete_incident_event_service": [["bearer_auth"]],
    "list_incident_events": [["bearer_auth"]],
    "create_incident_event": [["bearer_auth"]],
    "get_incident_event": [["bearer_auth"]],
    "update_incident_event": [["bearer_auth"]],
    "delete_incident_event": [["bearer_auth"]],
    "list_incident_feedbacks": [["bearer_auth"]],
    "create_incident_feedback": [["bearer_auth"]],
    "get_incident_feedback": [["bearer_auth"]],
    "update_incident_feedback": [["bearer_auth"]],
    "list_incident_form_field_selections": [["bearer_auth"]],
    "create_incident_form_field_selection": [["bearer_auth"]],
    "get_incident_form_field_selection": [["bearer_auth"]],
    "list_incident_post_mortems": [["bearer_auth"]],
    "get_incident_postmortem": [["bearer_auth"]],
    "update_incident_postmortem": [["bearer_auth"]],
    "get_incident_retrospective_step": [["bearer_auth"]],
    "update_incident_retrospective_step": [["bearer_auth"]],
    "list_incident_role_tasks": [["bearer_auth"]],
    "create_incident_role_task": [["bearer_auth"]],
    "get_incident_role_task": [["bearer_auth"]],
    "update_incident_role_task": [["bearer_auth"]],
    "delete_incident_role_task": [["bearer_auth"]],
    "list_incident_roles": [["bearer_auth"]],
    "create_incident_role": [["bearer_auth"]],
    "get_incident_role": [["bearer_auth"]],
    "update_incident_role": [["bearer_auth"]],
    "delete_incident_role": [["bearer_auth"]],
    "list_incident_status_page_events": [["bearer_auth"]],
    "create_incident_status_page_event": [["bearer_auth"]],
    "get_incident_status_page_event": [["bearer_auth"]],
    "update_incident_status_page_event": [["bearer_auth"]],
    "delete_status_page_event": [["bearer_auth"]],
    "list_incident_types": [["bearer_auth"]],
    "create_incident_type": [["bearer_auth"]],
    "get_incident_type": [["bearer_auth"]],
    "update_incident_type": [["bearer_auth"]],
    "delete_incident_type": [["bearer_auth"]],
    "list_incidents": [["bearer_auth"]],
    "create_incident": [["bearer_auth"]],
    "get_incident": [["bearer_auth"]],
    "update_incident": [["bearer_auth"]],
    "delete_incident": [["bearer_auth"]],
    "mitigate_incident": [["bearer_auth"]],
    "resolve_incident": [["bearer_auth"]],
    "cancel_incident": [["bearer_auth"]],
    "update_incident_to_triage": [["bearer_auth"]],
    "restart_incident": [["bearer_auth"]],
    "add_subscribers_to_incident": [["bearer_auth"]],
    "remove_subscribers_from_incident": [["bearer_auth"]],
    "list_live_call_routers": [["bearer_auth"]],
    "create_live_call_router": [["bearer_auth"]],
    "generate_phone_number_for_live_call_router": [["bearer_auth"]],
    "get_live_call_router": [["bearer_auth"]],
    "update_live_call_router": [["bearer_auth"]],
    "delete_live_call_router": [["bearer_auth"]],
    "list_on_call_roles": [["bearer_auth"]],
    "create_on_call_role": [["bearer_auth"]],
    "get_on_call_role": [["bearer_auth"]],
    "update_on_call_role": [["bearer_auth"]],
    "delete_on_call_role": [["bearer_auth"]],
    "list_on_call_shadows": [["bearer_auth"]],
    "create_on_call_shadow": [["bearer_auth"]],
    "get_on_call_shadow": [["bearer_auth"]],
    "update_on_call_shadow": [["bearer_auth"]],
    "delete_on_call_shadow": [["bearer_auth"]],
    "list_override_shifts": [["bearer_auth"]],
    "create_override_shift": [["bearer_auth"]],
    "get_override_shift": [["bearer_auth"]],
    "update_override_shift": [["bearer_auth"]],
    "delete_override_shift": [["bearer_auth"]],
    "list_playbook_tasks": [["bearer_auth"]],
    "create_playbook_task": [["bearer_auth"]],
    "get_playbook_task": [["bearer_auth"]],
    "update_playbook_task": [["bearer_auth"]],
    "delete_playbook_task": [["bearer_auth"]],
    "list_playbooks": [["bearer_auth"]],
    "create_playbook": [["bearer_auth"]],
    "get_playbook": [["bearer_auth"]],
    "update_playbook": [["bearer_auth"]],
    "delete_playbook": [["bearer_auth"]],
    "list_postmortem_templates": [["bearer_auth"]],
    "create_postmortem_template": [["bearer_auth"]],
    "get_postmortem_template": [["bearer_auth"]],
    "update_postmortem_template": [["bearer_auth"]],
    "delete_postmortem_template": [["bearer_auth"]],
    "list_pulses": [["bearer_auth"]],
    "create_pulse": [["bearer_auth"]],
    "get_pulse": [["bearer_auth"]],
    "update_pulse": [["bearer_auth"]],
    "list_retrospective_configurations": [["bearer_auth"]],
    "get_retrospective_configuration": [["bearer_auth"]],
    "update_retrospective_configuration": [["bearer_auth"]],
    "list_retrospective_process_group_steps": [["bearer_auth"]],
    "get_retrospective_process_group_step": [["bearer_auth"]],
    "list_retrospective_process_groups": [["bearer_auth"]],
    "get_retrospective_process_group": [["bearer_auth"]],
    "list_retrospective_processes": [["bearer_auth"]],
    "create_retrospective_process": [["bearer_auth"]],
    "get_retrospective_process": [["bearer_auth"]],
    "update_retrospective_process": [["bearer_auth"]],
    "delete_retrospective_process": [["bearer_auth"]],
    "list_retrospective_steps": [["bearer_auth"]],
    "create_retrospective_step": [["bearer_auth"]],
    "get_retrospective_step": [["bearer_auth"]],
    "update_retrospective_step": [["bearer_auth"]],
    "delete_retrospective_step": [["bearer_auth"]],
    "list_roles": [["bearer_auth"]],
    "get_role": [["bearer_auth"]],
    "delete_role": [["bearer_auth"]],
    "list_schedule_rotation_active_days": [["bearer_auth"]],
    "add_active_day_to_schedule_rotation": [["bearer_auth"]],
    "get_schedule_rotation_active_day": [["bearer_auth"]],
    "update_schedule_rotation_active_day": [["bearer_auth"]],
    "delete_schedule_rotation_active_day": [["bearer_auth"]],
    "list_schedule_rotation_users": [["bearer_auth"]],
    "add_user_to_schedule_rotation": [["bearer_auth"]],
    "get_schedule_rotation_user": [["bearer_auth"]],
    "update_schedule_rotation_user": [["bearer_auth"]],
    "delete_schedule_rotation_user": [["bearer_auth"]],
    "list_schedule_rotations": [["bearer_auth"]],
    "create_schedule_rotation": [["bearer_auth"]],
    "get_schedule_rotation": [["bearer_auth"]],
    "update_schedule_rotation": [["bearer_auth"]],
    "delete_schedule_rotation": [["bearer_auth"]],
    "list_schedules": [["bearer_auth"]],
    "create_schedule": [["bearer_auth"]],
    "get_schedule": [["bearer_auth"]],
    "update_schedule": [["bearer_auth"]],
    "delete_schedule": [["bearer_auth"]],
    "list_schedule_shifts": [["bearer_auth"]],
    "get_secret": [["bearer_auth"]],
    "update_secret": [["bearer_auth"]],
    "delete_secret": [["bearer_auth"]],
    "list_services": [["bearer_auth"]],
    "create_service": [["bearer_auth"]],
    "get_service": [["bearer_auth"]],
    "update_service": [["bearer_auth"]],
    "delete_service": [["bearer_auth"]],
    "get_service_incidents_chart": [["bearer_auth"]],
    "get_service_uptime_chart": [["bearer_auth"]],
    "list_severities": [["bearer_auth"]],
    "create_severity": [["bearer_auth"]],
    "get_severity": [["bearer_auth"]],
    "update_severity": [["bearer_auth"]],
    "delete_severity": [["bearer_auth"]],
    "list_shifts": [["bearer_auth"]],
    "list_status_page_templates": [["bearer_auth"]],
    "get_status_page_template": [["bearer_auth"]],
    "delete_status_page_template": [["bearer_auth"]],
    "list_status_pages": [["bearer_auth"]],
    "create_status_page": [["bearer_auth"]],
    "get_status_page": [["bearer_auth"]],
    "update_status_page": [["bearer_auth"]],
    "delete_status_page": [["bearer_auth"]],
    "list_teams": [["bearer_auth"]],
    "create_team": [["bearer_auth"]],
    "get_team": [["bearer_auth"]],
    "update_team": [["bearer_auth"]],
    "delete_team": [["bearer_auth"]],
    "get_team_incidents_chart": [["bearer_auth"]],
    "list_user_email_addresses": [["bearer_auth"]],
    "add_email_address_to_user": [["bearer_auth"]],
    "get_email_address": [["bearer_auth"]],
    "update_user_email_address": [["bearer_auth"]],
    "delete_email_address": [["bearer_auth"]],
    "get_notification_rule": [["bearer_auth"]],
    "delete_notification_rule": [["bearer_auth"]],
    "list_user_phone_numbers": [["bearer_auth"]],
    "add_phone_number_to_user": [["bearer_auth"]],
    "get_phone_number": [["bearer_auth"]],
    "update_user_phone_number": [["bearer_auth"]],
    "delete_user_phone_number": [["bearer_auth"]],
    "list_users": [["bearer_auth"]],
    "get_current_user": [["bearer_auth"]],
    "get_user": [["bearer_auth"]],
    "update_user": [["bearer_auth"]],
    "delete_user": [["bearer_auth"]],
    "list_webhook_deliveries": [["bearer_auth"]],
    "retry_webhook_delivery": [["bearer_auth"]],
    "get_webhook_delivery": [["bearer_auth"]],
    "list_webhook_endpoints": [["bearer_auth"]],
    "get_webhook_endpoint": [["bearer_auth"]],
    "update_webhooks_endpoint": [["bearer_auth"]],
    "delete_webhook_endpoint": [["bearer_auth"]]
}
