"""
Authentication module for ConvertAPI MCP server.

Generated: 2026-03-28 01:29:23 UTC
@generated by MCP Blacksmith (https://mcpblacksmith.com)

This module contains:
1. Authentication class implementations (OAuth2)
2. Operation-to-auth requirements mapping (OPERATION_AUTH_MAP)
"""

from __future__ import annotations

import logging
import os
from datetime import datetime, timedelta, timezone
from typing import Any

import jwt  # PyJWT for JWT token operations

logger = logging.getLogger(__name__)

__all__ = [
    "BearerTokenAuth",
    "JWTAuth",
    "OPERATION_AUTH_MAP",
]

# ============================================================================
# Authentication Classes
# ============================================================================

class BearerTokenAuth:
    """
    Bearer token authentication for ConvertAPI.

    Configuration:
        Provide the raw token in the environment variable.
        The authorization scheme prefix is automatically inserted.
    """

    def __init__(self, env_var: str = "BEARER_TOKEN", token_format: str = "Bearer"):
        """Initialize bearer token authentication from environment variable.

        Args:
            env_var: Environment variable name containing the bearer token.
            token_format: Authorization scheme prefix (e.g., 'Bearer').
        """
        self.token_format = token_format
        self.token = os.getenv(env_var, "").strip()

        # Check for empty token
        if not self.token:
            raise ValueError(
                f"{env_var} environment variable not set. "
                "Leave empty in .env to disable Bearer Token auth."
            )

        # Detect common placeholder patterns
        placeholders = ["placeholder", "your-", "example", "change-me", "todo", "sk_test_placeholder"]
        token_lower = self.token.lower()

        if any(p in token_lower for p in placeholders):
            raise ValueError(
                f"Bearer token appears to be a placeholder ({self.token[:20]}...). "
                "Please set a real token or leave empty to disable Bearer Token auth."
            )

    def get_auth_headers(self) -> dict[str, str]:
        """Get authentication headers for API requests."""
        return {
            'Authorization': f'{self.token_format} {self.token}'
        }
class JWTAuth:
    """
    JWT authentication for ConvertAPI.

    Configuration:
        Provide a pre-generated JWT token and/or a secret key for
        token generation via environment variables.

    Features:
        - Automatic token generation
        - Token expiration handling
        - Token validation
        - Token refresh support
    """

    def __init__(self, env_var_token: str = "JWT_TOKEN", env_var_secret: str = "JWT_SECRET",
                 algorithm: str = "HS256", token_format: str = "Bearer",
                 issuer: str | None = None, subject: str | None = None,
                 audience: str | None = None):
        """Initialize JWT authentication from environment variables.

        Args:
            env_var_token: Environment variable name for the pre-generated JWT token.
            env_var_secret: Environment variable name for the JWT secret key.
            algorithm: JWT signing algorithm (e.g., 'HS256', 'RS256').
            token_format: Authorization header prefix (e.g., 'Bearer').
            issuer: JWT issuer claim (iss).
            subject: JWT subject claim (sub).
            audience: JWT audience claim (aud).
        """
        # Try to get pre-generated token first
        self.current_token = os.getenv(env_var_token, "").strip()

        # Get secret key for token generation/validation
        self.secret_key = os.getenv(env_var_secret, "").strip()

        # Configuration
        self.algorithm = algorithm
        self.token_format = token_format
        self.token_expiry_minutes = 60
        self.token_expires_at = None
        self.issuer = issuer
        self.subject = subject
        self.audience = audience

        # If no token provided but secret available, we can generate tokens
        if not self.current_token and not self.secret_key:
            raise ValueError(
                f"Either {env_var_token} or {env_var_secret} must be set. "
                "Leave empty in .env to disable JWT auth."
            )

        # Detect common placeholder patterns
        placeholders = ["placeholder", "your-", "example", "change-me", "todo"]
        if self.current_token and any(p in self.current_token.lower() for p in placeholders):
            raise ValueError(
                f"{env_var_token} appears to be a placeholder ({self.current_token[:20]}...). "
                "Please set a real token or leave empty to disable JWT auth."
            )
        if self.secret_key and any(p in self.secret_key.lower() for p in placeholders):
            raise ValueError(
                f"{env_var_secret} appears to be a placeholder. "
                "Please set a real secret or leave empty to disable JWT auth."
            )

    def generate_token(self, payload: dict[str, Any] | None = None) -> str:
        """
        Generate a new JWT token.

        Args:
            payload: Additional claims to include in the token

        Returns:
            Generated JWT token

        Raises:
            ValueError: If secret key is not available
        """
        if not self.secret_key:
            raise ValueError("Cannot generate token without JWT_SECRET")

        now = datetime.now(timezone.utc)
        expires_at = now + timedelta(minutes=self.token_expiry_minutes)

        # Standard JWT claims
        token_payload: dict[str, Any] = {
            'iat': now,  # Issued at
            'exp': expires_at,  # Expiration
        }
        if self.issuer:
            token_payload['iss'] = self.issuer
        if self.subject:
            token_payload['sub'] = self.subject
        if self.audience:
            token_payload['aud'] = self.audience

        # Merge with custom payload
        if payload:
            token_payload.update(payload)

        # Generate token
        token = jwt.encode(token_payload, self.secret_key, algorithm=self.algorithm)

        # Update state
        self.current_token = token
        self.token_expires_at = expires_at

        return token

    def verify_token(self, token: str | None = None) -> dict[str, Any]:
        """
        Verify and decode a JWT token.

        Args:
            token: Token to verify (uses current_token if not provided)

        Returns:
            Decoded token payload

        Raises:
            ValueError: If token is invalid or expired
        """
        if not self.secret_key:
            raise ValueError("Cannot verify token without JWT_SECRET")

        token_to_verify = token or self.current_token

        if not token_to_verify:
            raise ValueError("No token available for verification")

        try:
            decode_kwargs: dict[str, Any] = {
                'algorithms': [self.algorithm],
            }
            if self.audience:
                decode_kwargs['audience'] = self.audience
            if self.issuer:
                decode_kwargs['issuer'] = self.issuer

            return jwt.decode(
                token_to_verify,
                self.secret_key,
                **decode_kwargs,
            )

        except jwt.ExpiredSignatureError:
            raise ValueError("JWT token has expired") from None
        except jwt.InvalidTokenError as e:
            raise ValueError(f"Invalid JWT token: {e}") from e

    def get_valid_token(self) -> str:
        """
        Get a valid JWT token, generating a new one if expired.

        Returns:
            Valid JWT token

        Raises:
            ValueError: If neither pre-generated token nor secret key available
        """
        # If we have a pre-generated token and no secret, we can't generate new ones
        if self.current_token and not self.secret_key:
            return self.current_token

        # If we have a secret, check if current token is expired
        if self.secret_key:
            now = datetime.now(timezone.utc)

            # No token yet, or token expired
            if not self.current_token or (self.token_expires_at and now >= self.token_expires_at):
                return self.generate_token()

            # Try to verify current token
            try:
                self.verify_token(self.current_token)
                return self.current_token
            except ValueError:
                # Token invalid or expired, generate new one
                return self.generate_token()

        # Shouldn't reach here, but return current token as fallback
        if self.current_token:
            return self.current_token

        raise ValueError("No valid token available")

    def get_auth_headers(self) -> dict[str, str]:
        """Get authentication headers with valid JWT token."""
        token = self.get_valid_token()

        return {
            'Authorization': f'{self.token_format} {token}',
            'Content-Type': 'application/json'
        }

# ============================================================================
# Operation Auth Requirements Map
# ============================================================================

"""
Operation-to-authentication requirements mapping.

This dictionary defines which authentication schemes are required for each operation,
using OR/AND relationships (outer list = OR, inner list = AND).
"""
OPERATION_AUTH_MAP: dict[str, list[list[str]]] = {
    "upload_file": [],
    "download_file": [],
    "delete_file": [],
    "get_file_metadata": [],
    "get_account": [["secret"]],
    "get_usage_statistics": [["secret"]],
    "convert_image_to_jpg": [["secret"], ["token"], ["jwt"]],
    "convert_ai_to_png": [["secret"], ["token"], ["jwt"]],
    "convert_image_to_pnm": [["secret"], ["token"], ["jwt"]],
    "convert_ai_to_svg": [["secret"], ["token"], ["jwt"]],
    "convert_ai_to_tiff": [["secret"], ["token"], ["jwt"]],
    "convert_image_to_webp": [["secret"], ["token"], ["jwt"]],
    "convert_image_bmp_to_jpg": [["secret"], ["token"], ["jwt"]],
    "convert_image_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_image_bmp_to_png": [["secret"], ["token"], ["jwt"]],
    "convert_image_bmp_to_pnm": [["secret"], ["token"], ["jwt"]],
    "convert_image_to_svg_bmp": [["secret"], ["token"], ["jwt"]],
    "convert_image_bmp_to_tiff": [["secret"], ["token"], ["jwt"]],
    "convert_image_bmp_to_webp": [["secret"], ["token"], ["jwt"]],
    "convert_csv_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_csv_to_xlsx": [["secret"], ["token"], ["jwt"]],
    "convert_djvu_to_jpg": [["secret"], ["token"], ["jwt"]],
    "convert_djvu_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_djvu_to_png": [["secret"], ["token"], ["jwt"]],
    "convert_djvu_to_tiff": [["secret"], ["token"], ["jwt"]],
    "convert_djvu_to_webp": [["secret"], ["token"], ["jwt"]],
    "convert_document_to_docx": [["secret"], ["token"], ["jwt"]],
    "compare_docx_documents": [["secret"], ["token"], ["jwt"]],
    "convert_document": [["secret"], ["token"], ["jwt"]],
    "convert_document_to_html": [["secret"], ["token"], ["jwt"]],
    "convert_document_to_image": [["secret"], ["token"], ["jwt"]],
    "convert_document_to_markdown": [["secret"], ["token"], ["jwt"]],
    "convert_document_docx_to_odt": [["secret"], ["token"], ["jwt"]],
    "convert_document_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_document_to_image_png": [["secret"], ["token"], ["jwt"]],
    "convert_document_to_protected_word": [["secret"], ["token"], ["jwt"]],
    "convert_document_docx_to_rtf": [["secret"], ["token"], ["jwt"]],
    "convert_document_to_tiff": [["secret"], ["token"], ["jwt"]],
    "convert_document_to_text": [["secret"], ["token"], ["jwt"]],
    "convert_document_to_webp": [["secret"], ["token"], ["jwt"]],
    "convert_docx_to_xml": [["secret"], ["token"], ["jwt"]],
    "convert_document_to_jpg": [["secret"], ["token"], ["jwt"]],
    "convert_dotx_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_dwf_to_jpg": [["secret"], ["token"], ["jwt"]],
    "convert_dwf_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_dwf_to_png": [["secret"], ["token"], ["jwt"]],
    "convert_dwf_to_svg": [["secret"], ["token"], ["jwt"]],
    "convert_dwf_to_tiff": [["secret"], ["token"], ["jwt"]],
    "convert_dwf_to_webp": [["secret"], ["token"], ["jwt"]],
    "convert_dwg_to_jpg": [["secret"], ["token"], ["jwt"]],
    "convert_dwg_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_dwg_to_png": [["secret"], ["token"], ["jwt"]],
    "convert_dwg_to_svg": [["secret"], ["token"], ["jwt"]],
    "convert_dwg_to_tiff": [["secret"], ["token"], ["jwt"]],
    "convert_dwg_to_webp": [["secret"], ["token"], ["jwt"]],
    "convert_dxf_to_jpg": [["secret"], ["token"], ["jwt"]],
    "convert_dxf_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_dxf_to_png": [["secret"], ["token"], ["jwt"]],
    "convert_dxf_to_svg": [["secret"], ["token"], ["jwt"]],
    "convert_dxf_to_tiff": [["secret"], ["token"], ["jwt"]],
    "convert_dxf_to_webp": [["secret"], ["token"], ["jwt"]],
    "extract_email_attachments": [["secret"], ["token"], ["jwt"]],
    "extract_email_metadata": [["secret"], ["token"], ["jwt"]],
    "convert_email_to_image": [["secret"], ["token"], ["jwt"]],
    "convert_eml_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_email_to_png": [["secret"], ["token"], ["jwt"]],
    "convert_eml_to_tiff": [["secret"], ["token"], ["jwt"]],
    "convert_eml_to_webp": [["secret"], ["token"], ["jwt"]],
    "convert_eps_to_jpg": [["secret"], ["token"], ["jwt"]],
    "convert_eps_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_eps_to_png": [["secret"], ["token"], ["jwt"]],
    "convert_eps_to_tiff": [["secret"], ["token"], ["jwt"]],
    "convert_epub_to_jpg": [["secret"], ["token"], ["jwt"]],
    "convert_epub_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_epub_to_png": [["secret"], ["token"], ["jwt"]],
    "convert_epub_to_tiff": [["secret"], ["token"], ["jwt"]],
    "convert_epub_to_webp": [["secret"], ["token"], ["jwt"]],
    "convert_file_to_pdf": [["secret"], ["token"], ["jwt"]],
    "compress_files_to_archive": [["secret"], ["token"], ["jwt"]],
    "convert_gif_animation": [["secret"], ["token"], ["jwt"]],
    "convert_gif_to_jpg": [["secret"], ["token"], ["jwt"]],
    "convert_gif_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_gif_to_png": [["secret"], ["token"], ["jwt"]],
    "convert_gif_to_pnm": [["secret"], ["token"], ["jwt"]],
    "convert_gif_to_svg": [["secret"], ["token"], ["jwt"]],
    "convert_gif_to_tiff": [["secret"], ["token"], ["jwt"]],
    "convert_gif_to_webp": [["secret"], ["token"], ["jwt"]],
    "convert_heic_to_jpg": [["secret"], ["token"], ["jwt"]],
    "convert_image_heic_to_jxl": [["secret"], ["token"], ["jwt"]],
    "convert_heic_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_heic_to_png": [["secret"], ["token"], ["jwt"]],
    "convert_image_heic_to_pnm": [["secret"], ["token"], ["jwt"]],
    "convert_heic_to_svg": [["secret"], ["token"], ["jwt"]],
    "convert_heic_to_tiff": [["secret"], ["token"], ["jwt"]],
    "convert_image_heic_to_webp": [["secret"], ["token"], ["jwt"]],
    "convert_heif_to_jpg": [["secret"], ["token"], ["jwt"]],
    "convert_heif_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_html_to_docx": [["secret"], ["token"], ["jwt"]],
    "convert_html_to_jpg": [["secret"], ["token"], ["jwt"]],
    "convert_html_to_markdown": [["secret"], ["token"], ["jwt"]],
    "convert_html_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_html_to_png": [["secret"], ["token"], ["jwt"]],
    "convert_html_to_text": [["secret"], ["token"], ["jwt"]],
    "convert_html_to_spreadsheet": [["secret"], ["token"], ["jwt"]],
    "convert_html_to_xlsx": [["secret"], ["token"], ["jwt"]],
    "convert_image_ico_to_jpg": [["secret"], ["token"], ["jwt"]],
    "convert_ico_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_image_ico_to_png": [["secret"], ["token"], ["jwt"]],
    "convert_icon_to_svg": [["secret"], ["token"], ["jwt"]],
    "convert_image_ico_to_webp": [["secret"], ["token"], ["jwt"]],
    "join_images": [["secret"], ["token"], ["jwt"]],
    "convert_images_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_jfif_to_pdf": [["secret"], ["token"], ["jwt"]],
    "compress_jpg_image": [["secret"], ["token"], ["jwt"]],
    "convert_image_to_gif": [["secret"], ["token"], ["jwt"]],
    "convert_image_format": [["secret"], ["token"], ["jwt"]],
    "convert_image_jpg_to_jxl": [["secret"], ["token"], ["jwt"]],
    "convert_image_to_pdf_jpeg": [["secret"], ["token"], ["jwt"]],
    "convert_image_jpg_to_png": [["secret"], ["token"], ["jwt"]],
    "convert_image_jpg_to_pnm": [["secret"], ["token"], ["jwt"]],
    "convert_image_to_svg_jpg": [["secret"], ["token"], ["jwt"]],
    "convert_image_to_tiff": [["secret"], ["token"], ["jwt"]],
    "extract_text_from_image": [["secret"], ["token"], ["jwt"]],
    "convert_image_jpg_to_webp": [["secret"], ["token"], ["jwt"]],
    "convert_presentation_to_pptx": [["secret"], ["token"], ["jwt"]],
    "convert_log_to_docx": [["secret"], ["token"], ["jwt"]],
    "convert_log_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_log_to_text": [["secret"], ["token"], ["jwt"]],
    "convert_markdown_to_html": [["secret"], ["token"], ["jwt"]],
    "convert_markdown_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_mhtml_to_docx": [["secret"], ["token"], ["jwt"]],
    "convert_mobi_to_jpg": [["secret"], ["token"], ["jwt"]],
    "convert_mobi_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_mobi_to_png": [["secret"], ["token"], ["jwt"]],
    "convert_mobi_to_tiff": [["secret"], ["token"], ["jwt"]],
    "convert_mobi_to_webp": [["secret"], ["token"], ["jwt"]],
    "convert_email_to_jpg": [["secret"], ["token"], ["jwt"]],
    "convert_msg_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_email_to_png_outlook": [["secret"], ["token"], ["jwt"]],
    "convert_msg_to_tiff": [["secret"], ["token"], ["jwt"]],
    "convert_message_to_webp": [["secret"], ["token"], ["jwt"]],
    "convert_numbers_to_csv": [["secret"], ["token"], ["jwt"]],
    "convert_numbers_to_xlsx": [["secret"], ["token"], ["jwt"]],
    "convert_document_to_jpg_spreadsheet": [["secret"], ["token"], ["jwt"]],
    "convert_odc_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_odc_to_png": [["secret"], ["token"], ["jwt"]],
    "convert_document_to_jpg_formula": [["secret"], ["token"], ["jwt"]],
    "convert_document_to_pdf_odf": [["secret"], ["token"], ["jwt"]],
    "convert_document_to_png": [["secret"], ["token"], ["jwt"]],
    "convert_odg_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_presentation_to_jpg": [["secret"], ["token"], ["jwt"]],
    "convert_odp_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_presentation_to_png": [["secret"], ["token"], ["jwt"]],
    "convert_spreadsheet_to_image": [["secret"], ["token"], ["jwt"]],
    "convert_ods_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_ods_to_png": [["secret"], ["token"], ["jwt"]],
    "convert_document_odt_to_docx": [["secret"], ["token"], ["jwt"]],
    "convert_document_to_jpg_text": [["secret"], ["token"], ["jwt"]],
    "convert_document_to_pdf_odt": [["secret"], ["token"], ["jwt"]],
    "convert_document_to_png_text": [["secret"], ["token"], ["jwt"]],
    "convert_document_odt_to_txt": [["secret"], ["token"], ["jwt"]],
    "convert_document_to_xml": [["secret"], ["token"], ["jwt"]],
    "convert_office_document_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_pages_to_docx": [["secret"], ["token"], ["jwt"]],
    "convert_pages_to_text": [["secret"], ["token"], ["jwt"]],
    "compress_pdf": [["secret"], ["token"], ["jwt"]],
    "crop_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_pdf_to_csv": [["secret"], ["token"], ["jwt"]],
    "delete_pdf_pages": [["secret"], ["token"], ["jwt"]],
    "convert_pdf_to_docx": [["secret"], ["token"], ["jwt"]],
    "extract_data_from_pdf": [["secret"], ["token"], ["jwt"]],
    "extract_images_from_pdf": [["secret"], ["token"], ["jwt"]],
    "extract_pdf_form_fields": [["secret"], ["token"], ["jwt"]],
    "import_pdf_with_fdf_form_data": [["secret"], ["token"], ["jwt"]],
    "flatten_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_pdf_to_html": [["secret"], ["token"], ["jwt"]],
    "add_watermark_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_pdf_to_jpg": [["secret"], ["token"], ["jwt"]],
    "merge_pdfs": [["secret"], ["token"], ["jwt"]],
    "convert_pdf_to_metadata": [["secret"], ["token"], ["jwt"]],
    "extract_text_from_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_pdf_to_pcl": [["secret"], ["token"], ["jwt"]],
    "convert_pdf_to_pdf": [["secret"], ["token"], ["jwt"]],
    "add_watermark_to_pdf_document": [["secret"], ["token"], ["jwt"]],
    "convert_pdf_to_pdfa": [["secret"], ["token"], ["jwt"]],
    "convert_pdf_to_pdfua": [["secret"], ["token"], ["jwt"]],
    "convert_pdf_to_png": [["secret"], ["token"], ["jwt"]],
    "convert_pdf_to_pptx": [["secret"], ["token"], ["jwt"]],
    "convert_pdf_to_print": [["secret"], ["token"], ["jwt"]],
    "protect_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_pdf_to_rasterized_image": [["secret"], ["token"], ["jwt"]],
    "redact_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_pdf_to_repair": [["secret"], ["token"], ["jwt"]],
    "resize_pdf_pages": [["secret"], ["token"], ["jwt"]],
    "rotate_pdf_pages": [["secret"], ["token"], ["jwt"]],
    "convert_pdf_to_rtf": [["secret"], ["token"], ["jwt"]],
    "split_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_pdf_to_svg": [["secret"], ["token"], ["jwt"]],
    "convert_pdf_to_text_with_watermark": [["secret"], ["token"], ["jwt"]],
    "convert_pdf_to_tiff": [["secret"], ["token"], ["jwt"]],
    "convert_pdf_to_tiff_fax": [["secret"], ["token"], ["jwt"]],
    "convert_pdf_to_text": [["secret"], ["token"], ["jwt"]],
    "unprotect_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_pdf_to_webp": [["secret"], ["token"], ["jwt"]],
    "convert_pdf_to_xlsx": [["secret"], ["token"], ["jwt"]],
    "validate_pdfa_conformance": [["secret"], ["token"], ["jwt"]],
    "convert_png_to_gif": [["secret"], ["token"], ["jwt"]],
    "convert_image_png_to_jpg": [["secret"], ["token"], ["jwt"]],
    "convert_image_to_pdf_png": [["secret"], ["token"], ["jwt"]],
    "convert_image_format_png": [["secret"], ["token"], ["jwt"]],
    "convert_image_png_to_pnm": [["secret"], ["token"], ["jwt"]],
    "convert_image_to_svg": [["secret"], ["token"], ["jwt"]],
    "convert_png_to_tiff": [["secret"], ["token"], ["jwt"]],
    "convert_image_png_to_webp": [["secret"], ["token"], ["jwt"]],
    "translate_po_file": [["secret"], ["token"], ["jwt"]],
    "convert_presentation_to_jpg_template": [["secret"], ["token"], ["jwt"]],
    "convert_presentation_template_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_presentation_to_png_template": [["secret"], ["token"], ["jwt"]],
    "convert_potx_to_pptx": [["secret"], ["token"], ["jwt"]],
    "convert_presentation_template_to_tiff": [["secret"], ["token"], ["jwt"]],
    "convert_presentation_to_webp_template": [["secret"], ["token"], ["jwt"]],
    "convert_presentation_to_jpg_slideshow": [["secret"], ["token"], ["jwt"]],
    "convert_presentation_slideshow_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_presentation_to_png_slideshow": [["secret"], ["token"], ["jwt"]],
    "convert_presentation_ppsx_to_pptx": [["secret"], ["token"], ["jwt"]],
    "convert_presentation_slideshow_to_tiff": [["secret"], ["token"], ["jwt"]],
    "convert_presentation_to_webp_slideshow": [["secret"], ["token"], ["jwt"]],
    "convert_presentation_ppt_to_pptx": [["secret"], ["token"], ["jwt"]],
    "convert_presentation_to_images": [["secret"], ["token"], ["jwt"]],
    "convert_presentation_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_presentation_to_images_png": [["secret"], ["token"], ["jwt"]],
    "convert_presentation": [["secret"], ["token"], ["jwt"]],
    "encrypt_presentation": [["secret"], ["token"], ["jwt"]],
    "convert_presentation_to_tiff": [["secret"], ["token"], ["jwt"]],
    "convert_presentation_to_webp": [["secret"], ["token"], ["jwt"]],
    "convert_prn_to_jpg": [["secret"], ["token"], ["jwt"]],
    "convert_prn_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_prn_to_png": [["secret"], ["token"], ["jwt"]],
    "convert_prn_to_tiff": [["secret"], ["token"], ["jwt"]],
    "convert_postscript_to_jpg": [["secret"], ["token"], ["jwt"]],
    "convert_postscript_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_postscript_to_png": [["secret"], ["token"], ["jwt"]],
    "convert_postscript_to_tiff": [["secret"], ["token"], ["jwt"]],
    "convert_psd_to_jpg": [["secret"], ["token"], ["jwt"]],
    "convert_image_psd_to_png": [["secret"], ["token"], ["jwt"]],
    "convert_image_psd_to_pnm": [["secret"], ["token"], ["jwt"]],
    "convert_psd_to_svg": [["secret"], ["token"], ["jwt"]],
    "convert_psd_to_tiff": [["secret"], ["token"], ["jwt"]],
    "convert_image_psd_to_webp": [["secret"], ["token"], ["jwt"]],
    "convert_publication_to_jpg": [["secret"], ["token"], ["jwt"]],
    "convert_pub_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_pub_to_png": [["secret"], ["token"], ["jwt"]],
    "convert_pub_to_tiff": [["secret"], ["token"], ["jwt"]],
    "convert_rtf_to_html": [["secret"], ["token"], ["jwt"]],
    "convert_rtf_to_jpg": [["secret"], ["token"], ["jwt"]],
    "convert_rtf_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_rtf_to_text": [["secret"], ["token"], ["jwt"]],
    "convert_svg_to_jpg": [["secret"], ["token"], ["jwt"]],
    "convert_svg_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_svg_to_png": [["secret"], ["token"], ["jwt"]],
    "convert_svg_to_pnm": [["secret"], ["token"], ["jwt"]],
    "convert_svg_image": [["secret"], ["token"], ["jwt"]],
    "convert_svg_to_tiff": [["secret"], ["token"], ["jwt"]],
    "convert_svg_to_webp": [["secret"], ["token"], ["jwt"]],
    "fill_template_to_docx": [["secret"], ["token"], ["jwt"]],
    "convert_template_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_tiff_to_jpg": [["secret"], ["token"], ["jwt"]],
    "convert_tiff_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_tiff_to_png": [["secret"], ["token"], ["jwt"]],
    "convert_tiff_to_pnm": [["secret"], ["token"], ["jwt"]],
    "convert_tiff_to_svg": [["secret"], ["token"], ["jwt"]],
    "convert_tiff_image": [["secret"], ["token"], ["jwt"]],
    "convert_image_tiff_to_webp": [["secret"], ["token"], ["jwt"]],
    "convert_text_to_image": [["secret"], ["token"], ["jwt"]],
    "convert_text_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_vsdx_to_jpg": [["secret"], ["token"], ["jwt"]],
    "convert_vsdx_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_vsdx_to_png": [["secret"], ["token"], ["jwt"]],
    "convert_vsdx_to_tiff": [["secret"], ["token"], ["jwt"]],
    "convert_webpage_to_jpg": [["secret"], ["token"], ["jwt"]],
    "convert_webpage_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_webpage_to_png": [["secret"], ["token"], ["jwt"]],
    "convert_webpage_to_text": [["secret"], ["token"], ["jwt"]],
    "convert_webp_to_gif": [["secret"], ["token"], ["jwt"]],
    "convert_webp_to_jpg": [["secret"], ["token"], ["jwt"]],
    "convert_webp_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_webp_to_png": [["secret"], ["token"], ["jwt"]],
    "convert_webp_to_pnm": [["secret"], ["token"], ["jwt"]],
    "convert_webp_to_svg": [["secret"], ["token"], ["jwt"]],
    "convert_webp_to_tiff": [["secret"], ["token"], ["jwt"]],
    "convert_webp_image": [["secret"], ["token"], ["jwt"]],
    "convert_wpd_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_spreadsheet_format": [["secret"], ["token"], ["jwt"]],
    "convert_spreadsheet_xls_to_xlsx": [["secret"], ["token"], ["jwt"]],
    "convert_xlsb_to_csv": [["secret"], ["token"], ["jwt"]],
    "convert_xlsb_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_spreadsheet_to_csv": [["secret"], ["token"], ["jwt"]],
    "convert_spreadsheet_to_image_xlsx": [["secret"], ["token"], ["jwt"]],
    "convert_spreadsheet_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_spreadsheet_to_image_png": [["secret"], ["token"], ["jwt"]],
    "encrypt_xlsx_workbook": [["secret"], ["token"], ["jwt"]],
    "convert_spreadsheet_to_tiff": [["secret"], ["token"], ["jwt"]],
    "convert_spreadsheet_to_image_webp": [["secret"], ["token"], ["jwt"]],
    "convert_spreadsheet_format_modern": [["secret"], ["token"], ["jwt"]],
    "convert_spreadsheet_template_to_pdf": [["secret"], ["token"], ["jwt"]],
    "convert_xml_to_docx": [["secret"], ["token"], ["jwt"]],
    "extract_archive": [["secret"], ["token"], ["jwt"]]
}
