"""
Authentication module for PostHog MCP server.

Generated: 2026-05-11 20:07:50 UTC
Generator: MCP Blacksmith v1.1.0 (https://mcpblacksmith.com)

This module contains:
1. Authentication class implementations (OAuth2)
2. Operation-to-auth requirements mapping (OPERATION_AUTH_MAP)
"""

from __future__ import annotations

import logging
import os

logger = logging.getLogger(__name__)

__all__ = [
    "BearerTokenAuth",
    "OPERATION_AUTH_MAP",
]

# ============================================================================
# Authentication Classes
# ============================================================================

class BearerTokenAuth:
    """
    Bearer token authentication for PostHog API.

    Configuration:
        Provide the raw token in the environment variable.
        The authorization scheme prefix is automatically inserted.
    """

    def __init__(self, env_var: str = "BEARER_TOKEN", token_format: str = "Bearer"):
        """Initialize bearer token authentication from environment variable.

        Args:
            env_var: Environment variable name containing the bearer token.
            token_format: Authorization scheme prefix (e.g., 'Bearer').
        """
        self.token_format = token_format
        self.token = os.getenv(env_var, "").strip()

        # Check for empty token
        if not self.token:
            raise ValueError(
                f"{env_var} environment variable not set. "
                "Leave empty in .env to disable Bearer Token auth."
            )

        # Detect common placeholder patterns
        placeholders = ["placeholder", "your-", "example", "change-me", "todo", "sk_test_placeholder"]
        token_lower = self.token.lower()

        if any(p in token_lower for p in placeholders):
            raise ValueError(
                f"Bearer token appears to be a placeholder ({self.token[:20]}...). "
                "Please set a real token or leave empty to disable Bearer Token auth."
            )

    def get_auth_headers(self) -> dict[str, str]:
        """Get authentication headers for API requests."""
        return {
            'Authorization': f'{self.token_format} {self.token}'
        }


# ============================================================================
# Operation Auth Requirements Map
# ============================================================================

"""
Operation-to-authentication requirements mapping.

This dictionary defines which authentication schemes are required for each operation,
using OR/AND relationships (outer list = OR, inner list = AND).
"""
OPERATION_AUTH_MAP: dict[str, list[list[str]]] = {
    "list_conversations": [["PersonalAPIKeyAuth"]],
    "send_conversation_message": [["PersonalAPIKeyAuth"]],
    "get_conversation": [["PersonalAPIKeyAuth"]],
    "list_customer_profile_configs": [["PersonalAPIKeyAuth"]],
    "get_customer_profile_config": [["PersonalAPIKeyAuth"]],
    "list_dashboard_collaborators": [["PersonalAPIKeyAuth"]],
    "remove_dashboard_collaborator": [["PersonalAPIKeyAuth"]],
    "list_desktop_recordings": [["PersonalAPIKeyAuth"]],
    "create_desktop_recording": [["PersonalAPIKeyAuth"]],
    "get_desktop_recording": [["PersonalAPIKeyAuth"]],
    "update_desktop_recording": [["PersonalAPIKeyAuth"]],
    "update_desktop_recording_partial": [["PersonalAPIKeyAuth"]],
    "delete_desktop_recording": [["PersonalAPIKeyAuth"]],
    "append_segments_to_desktop_recording": [["PersonalAPIKeyAuth"]],
    "list_error_tracking_assignment_rules": [["PersonalAPIKeyAuth"]],
    "get_error_tracking_assignment_rule": [["PersonalAPIKeyAuth"]],
    "update_error_tracking_assignment_rule": [["PersonalAPIKeyAuth"]],
    "update_error_tracking_assignment_rule_partial": [["PersonalAPIKeyAuth"]],
    "delete_error_tracking_assignment_rule": [["PersonalAPIKeyAuth"]],
    "list_error_tracking_fingerprints": [["PersonalAPIKeyAuth"]],
    "get_error_fingerprint": [["PersonalAPIKeyAuth"]],
    "list_error_tracking_grouping_rules": [["PersonalAPIKeyAuth"]],
    "get_error_tracking_grouping_rule": [["PersonalAPIKeyAuth"]],
    "update_error_tracking_grouping_rule": [["PersonalAPIKeyAuth"]],
    "update_error_tracking_grouping_rule_partial": [["PersonalAPIKeyAuth"]],
    "delete_error_tracking_grouping_rule": [["PersonalAPIKeyAuth"]],
    "list_error_tracking_issues": [["PersonalAPIKeyAuth"]],
    "create_error_tracking_issue": [["PersonalAPIKeyAuth"]],
    "get_error_tracking_issue": [["PersonalAPIKeyAuth"]],
    "update_error_tracking_issue": [["PersonalAPIKeyAuth"]],
    "update_error_tracking_issue_partial": [["PersonalAPIKeyAuth"]],
    "get_error_tracking_issue_activity": [["PersonalAPIKeyAuth"]],
    "list_error_tracking_issues_activity": [["PersonalAPIKeyAuth"]],
    "list_error_tracking_releases": [["PersonalAPIKeyAuth"]],
    "create_error_tracking_release": [["PersonalAPIKeyAuth"]],
    "get_error_tracking_release": [["PersonalAPIKeyAuth"]],
    "update_error_tracking_release": [["PersonalAPIKeyAuth"]],
    "update_error_tracking_release_partial": [["PersonalAPIKeyAuth"]],
    "delete_error_tracking_release": [["PersonalAPIKeyAuth"]],
    "get_error_tracking_release_by_hash": [["PersonalAPIKeyAuth"]],
    "list_error_tracking_spike_events": [["PersonalAPIKeyAuth"]],
    "list_error_tracking_suppression_rules": [["PersonalAPIKeyAuth"]],
    "get_error_tracking_suppression_rule": [["PersonalAPIKeyAuth"]],
    "update_error_tracking_suppression_rule": [["PersonalAPIKeyAuth"]],
    "update_error_tracking_suppression_rule_partial": [["PersonalAPIKeyAuth"]],
    "delete_error_tracking_suppression_rule": [["PersonalAPIKeyAuth"]],
    "list_error_tracking_symbol_sets": [["PersonalAPIKeyAuth"]],
    "get_error_tracking_symbol_set": [["PersonalAPIKeyAuth"]],
    "update_error_tracking_symbol_set": [["PersonalAPIKeyAuth"]],
    "delete_error_tracking_symbol_set": [["PersonalAPIKeyAuth"]],
    "finish_symbol_set_bulk_upload": [["PersonalAPIKeyAuth"]],
    "start_symbol_sets_bulk_upload": [["PersonalAPIKeyAuth"]],
    "list_evaluations": [["PersonalAPIKeyAuth"]],
    "create_evaluation": [["PersonalAPIKeyAuth"]],
    "get_evaluation": [["PersonalAPIKeyAuth"]],
    "update_evaluation": [["PersonalAPIKeyAuth"]],
    "update_evaluation_partial": [["PersonalAPIKeyAuth"]],
    "list_health_issues": [["PersonalAPIKeyAuth"]],
    "get_health_issue": [["PersonalAPIKeyAuth"]],
    "update_health_issue": [["PersonalAPIKeyAuth"]],
    "list_clustering_jobs": [["PersonalAPIKeyAuth"]],
    "create_llm_analytics_clustering_job": [["PersonalAPIKeyAuth"]],
    "get_clustering_job": [["PersonalAPIKeyAuth"]],
    "update_clustering_job": [["PersonalAPIKeyAuth"]],
    "update_clustering_job_partial": [["PersonalAPIKeyAuth"]],
    "delete_clustering_job": [["PersonalAPIKeyAuth"]],
    "get_llm_analytics_evaluation_config": [["PersonalAPIKeyAuth"]],
    "generate_llm_evaluation_summary": [["PersonalAPIKeyAuth"]],
    "list_llm_analytics_provider_keys": [["PersonalAPIKeyAuth"]],
    "get_llm_provider_key": [["PersonalAPIKeyAuth"]],
    "update_llm_provider_key": [["PersonalAPIKeyAuth"]],
    "update_llm_provider_key_partial": [["PersonalAPIKeyAuth"]],
    "delete_llm_provider_key": [["PersonalAPIKeyAuth"]],
    "list_dependent_configs_for_provider_key": [["PersonalAPIKeyAuth"]],
    "validate_llm_provider_key": [["PersonalAPIKeyAuth"]],
    "list_review_queue_items": [["PersonalAPIKeyAuth"]],
    "add_trace_to_review_queue": [["PersonalAPIKeyAuth"]],
    "get_review_queue_item": [["PersonalAPIKeyAuth"]],
    "update_review_queue_item": [["PersonalAPIKeyAuth"]],
    "delete_llm_analytics_review_queue_item": [["PersonalAPIKeyAuth"]],
    "list_llm_analytics_review_queues": [["PersonalAPIKeyAuth"]],
    "create_llm_analytics_review_queue": [["PersonalAPIKeyAuth"]],
    "get_review_queue": [["PersonalAPIKeyAuth"]],
    "update_review_queue": [["PersonalAPIKeyAuth"]],
    "delete_review_queue": [["PersonalAPIKeyAuth"]],
    "list_llm_analytics_score_definitions": [["PersonalAPIKeyAuth"]],
    "create_llm_analytics_score_definition": [["PersonalAPIKeyAuth"]],
    "get_llm_analytics_score_definition": [["PersonalAPIKeyAuth"]],
    "update_llm_analytics_score_definition": [["PersonalAPIKeyAuth"]],
    "analyze_sentiment_for_llm_outputs": [["PersonalAPIKeyAuth"]],
    "list_trace_reviews": [["PersonalAPIKeyAuth"]],
    "create_trace_review": [["PersonalAPIKeyAuth"]],
    "get_trace_review": [["PersonalAPIKeyAuth"]],
    "update_trace_review": [["PersonalAPIKeyAuth"]],
    "delete_trace_review": [["PersonalAPIKeyAuth"]],
    "list_llm_prompts": [["PersonalAPIKeyAuth"]],
    "create_llm_prompt": [["PersonalAPIKeyAuth"]],
    "get_llm_prompt_by_name": [["PersonalAPIKeyAuth"]],
    "archive_llm_prompt_by_name": [["PersonalAPIKeyAuth"]],
    "duplicate_llm_prompt": [["PersonalAPIKeyAuth"]],
    "get_llm_prompt_by_name_resolved": [["PersonalAPIKeyAuth"]],
    "explain_log_with_ai": [["PersonalAPIKeyAuth"]],
    "list_log_views": [["PersonalAPIKeyAuth"]],
    "create_logs_view": [["PersonalAPIKeyAuth"]],
    "get_log_view": [["PersonalAPIKeyAuth"]],
    "update_logs_view": [["PersonalAPIKeyAuth"]],
    "update_logs_view_partial": [["PersonalAPIKeyAuth"]],
    "delete_log_view": [["PersonalAPIKeyAuth"]],
    "list_user_interviews": [["PersonalAPIKeyAuth"]],
    "get_user_interview": [["PersonalAPIKeyAuth"]],
    "update_user_interview": [["PersonalAPIKeyAuth"]],
    "update_user_interview_partial": [["PersonalAPIKeyAuth"]],
    "delete_user_interview": [["PersonalAPIKeyAuth"]],
    "get_web_vitals_for_pathname": [["PersonalAPIKeyAuth"]],
    "list_organizations": [["PersonalAPIKeyAuth"]],
    "create_organization": [["PersonalAPIKeyAuth"]],
    "get_organization": [["PersonalAPIKeyAuth"]],
    "update_organization": [["PersonalAPIKeyAuth"]],
    "update_organization_partial": [["PersonalAPIKeyAuth"]],
    "delete_organization": [["PersonalAPIKeyAuth"]],
    "list_batch_exports": [["PersonalAPIKeyAuth"]],
    "get_batch_export": [["PersonalAPIKeyAuth"]],
    "update_batch_export": [["PersonalAPIKeyAuth"]],
    "update_batch_export_partial": [["PersonalAPIKeyAuth"]],
    "delete_batch_export": [["PersonalAPIKeyAuth"]],
    "pause_batch_export": [["PersonalAPIKeyAuth"]],
    "create_batch_export_test_run": [["PersonalAPIKeyAuth"]],
    "unpause_batch_export": [["PersonalAPIKeyAuth"]],
    "create_batch_export_test_run_new": [["PersonalAPIKeyAuth"]],
    "list_domains": [["PersonalAPIKeyAuth"]],
    "create_domain": [["PersonalAPIKeyAuth"]],
    "get_domain": [["PersonalAPIKeyAuth"]],
    "update_domain": [["PersonalAPIKeyAuth"]],
    "update_domain_partial": [["PersonalAPIKeyAuth"]],
    "delete_domain": [["PersonalAPIKeyAuth"]],
    "list_organization_integrations": [["PersonalAPIKeyAuth"]],
    "get_organization_integration": [["PersonalAPIKeyAuth"]],
    "list_organization_invites": [["PersonalAPIKeyAuth"]],
    "send_organization_invite": [["PersonalAPIKeyAuth"]],
    "delete_organization_invite": [["PersonalAPIKeyAuth"]],
    "list_organization_members": [["PersonalAPIKeyAuth"]],
    "update_organization_member": [["PersonalAPIKeyAuth"]],
    "update_organization_member_level": [["PersonalAPIKeyAuth"]],
    "remove_member_from_organization": [["PersonalAPIKeyAuth"]],
    "list_oauth_applications": [["PersonalAPIKeyAuth"]],
    "list_projects_for_organization": [["PersonalAPIKeyAuth"]],
    "create_project": [["PersonalAPIKeyAuth"]],
    "get_project": [["PersonalAPIKeyAuth"]],
    "update_project": [["PersonalAPIKeyAuth"]],
    "update_project_settings": [["PersonalAPIKeyAuth"]],
    "delete_project": [["PersonalAPIKeyAuth"]],
    "list_proxy_records": [["PersonalAPIKeyAuth"]],
    "create_proxy_record": [["PersonalAPIKeyAuth"]],
    "get_proxy_record": [["PersonalAPIKeyAuth"]],
    "delete_proxy_record": [["PersonalAPIKeyAuth"]],
    "get_role": [["PersonalAPIKeyAuth"]],
    "update_role": [["PersonalAPIKeyAuth"]],
    "delete_role": [["PersonalAPIKeyAuth"]],
    "list_role_memberships": [["PersonalAPIKeyAuth"]],
    "add_user_to_role": [["PersonalAPIKeyAuth"]],
    "get_role_membership": [["PersonalAPIKeyAuth"]],
    "remove_role_membership": [["PersonalAPIKeyAuth"]],
    "list_actions": [["PersonalAPIKeyAuth"]],
    "create_action": [["PersonalAPIKeyAuth"]],
    "get_action": [["PersonalAPIKeyAuth"]],
    "update_action": [["PersonalAPIKeyAuth"]],
    "update_action_partial": [["PersonalAPIKeyAuth"]],
    "actions_destroy": [["PersonalAPIKeyAuth"]],
    "list_action_references": [["PersonalAPIKeyAuth"]],
    "list_activity_logs": [["PersonalAPIKeyAuth"]],
    "list_advanced_activity_logs": [["PersonalAPIKeyAuth"]],
    "list_alerts": [["PersonalAPIKeyAuth"]],
    "create_alert": [["PersonalAPIKeyAuth"]],
    "get_alert": [["PersonalAPIKeyAuth"]],
    "update_alert": [["PersonalAPIKeyAuth"]],
    "update_alert_configuration": [["PersonalAPIKeyAuth"]],
    "delete_alert": [["PersonalAPIKeyAuth"]],
    "simulate_detector_on_insight": [["PersonalAPIKeyAuth"]],
    "list_annotations": [["PersonalAPIKeyAuth"]],
    "create_annotation": [["PersonalAPIKeyAuth"]],
    "get_annotation": [["PersonalAPIKeyAuth"]],
    "update_annotation": [["PersonalAPIKeyAuth"]],
    "update_annotation_partial": [["PersonalAPIKeyAuth"]],
    "annotations_destroy": [["PersonalAPIKeyAuth"]],
    "get_app_metrics": [["PersonalAPIKeyAuth"]],
    "list_app_metrics_historical_exports": [["PersonalAPIKeyAuth"]],
    "get_historical_export": [["PersonalAPIKeyAuth"]],
    "list_batch_exports_project": [["PersonalAPIKeyAuth"]],
    "list_backfills_for_batch_export": [["PersonalAPIKeyAuth"]],
    "create_backfill_for_batch_export": [["PersonalAPIKeyAuth"]],
    "get_batch_export_backfill": [["PersonalAPIKeyAuth"]],
    "cancel_batch_export_backfill": [["PersonalAPIKeyAuth"]],
    "list_batch_export_runs": [["PersonalAPIKeyAuth"]],
    "get_batch_export_run": [["PersonalAPIKeyAuth"]],
    "cancel_batch_export_run": [["PersonalAPIKeyAuth"]],
    "retry_batch_export_run": [["PersonalAPIKeyAuth"]],
    "get_batch_export_project": [["PersonalAPIKeyAuth"]],
    "update_batch_export_project": [["PersonalAPIKeyAuth"]],
    "update_batch_export_project_partial": [["PersonalAPIKeyAuth"]],
    "delete_batch_export_project": [["PersonalAPIKeyAuth"]],
    "pause_batch_export_project": [["PersonalAPIKeyAuth"]],
    "run_batch_export_test_step": [["PersonalAPIKeyAuth"]],
    "list_cohorts": [["PersonalAPIKeyAuth"]],
    "create_cohort": [["PersonalAPIKeyAuth"]],
    "get_cohort": [["PersonalAPIKeyAuth"]],
    "update_cohort": [["PersonalAPIKeyAuth"]],
    "update_cohort_partial": [["PersonalAPIKeyAuth"]],
    "cohorts_destroy": [["PersonalAPIKeyAuth"]],
    "get_cohort_activity": [["PersonalAPIKeyAuth"]],
    "add_persons_to_static_cohort": [["PersonalAPIKeyAuth"]],
    "get_cohort_calculation_history": [["PersonalAPIKeyAuth"]],
    "list_cohort_persons": [["PersonalAPIKeyAuth"]],
    "remove_person_from_static_cohort": [["PersonalAPIKeyAuth"]],
    "list_cohorts_activity": [["PersonalAPIKeyAuth"]],
    "list_conversation_tickets": [["PersonalAPIKeyAuth"]],
    "create_conversation_ticket": [["PersonalAPIKeyAuth"]],
    "get_ticket": [["PersonalAPIKeyAuth"]],
    "update_ticket": [["PersonalAPIKeyAuth"]],
    "update_conversation_ticket": [["PersonalAPIKeyAuth"]],
    "delete_conversation_ticket": [["PersonalAPIKeyAuth"]],
    "list_dashboard_templates": [["PersonalAPIKeyAuth"]],
    "get_dashboard_template": [["PersonalAPIKeyAuth"]],
    "update_dashboard_template": [["PersonalAPIKeyAuth"]],
    "update_dashboard_template_partial": [["PersonalAPIKeyAuth"]],
    "soft_delete_dashboard_template": [["PersonalAPIKeyAuth"]],
    "list_dashboards": [["PersonalAPIKeyAuth"]],
    "create_dashboard": [["PersonalAPIKeyAuth"]],
    "list_dashboard_collaborators_project": [["PersonalAPIKeyAuth"]],
    "add_collaborator_to_dashboard_project": [["PersonalAPIKeyAuth"]],
    "remove_dashboard_collaborator_project": [["PersonalAPIKeyAuth"]],
    "list_dashboard_sharing": [["PersonalAPIKeyAuth"]],
    "create_dashboard_sharing_password": [["PersonalAPIKeyAuth"]],
    "delete_dashboard_sharing_password": [["PersonalAPIKeyAuth"]],
    "refresh_dashboard_sharing": [["PersonalAPIKeyAuth"]],
    "get_dashboard": [["PersonalAPIKeyAuth"]],
    "update_dashboard": [["PersonalAPIKeyAuth"]],
    "update_dashboard_partial": [["PersonalAPIKeyAuth"]],
    "soft_delete_dashboard": [["PersonalAPIKeyAuth"]],
    "copy_tile_to_dashboard": [["PersonalAPIKeyAuth"]],
    "generate_dashboard_metadata": [["PersonalAPIKeyAuth"]],
    "reorder_dashboard_tiles": [["PersonalAPIKeyAuth"]],
    "list_data_color_themes": [["PersonalAPIKeyAuth"]],
    "create_data_color_theme": [["PersonalAPIKeyAuth"]],
    "get_data_color_theme": [["PersonalAPIKeyAuth"]],
    "update_data_color_theme": [["PersonalAPIKeyAuth"]],
    "delete_data_color_theme": [["PersonalAPIKeyAuth"]],
    "list_dataset_items": [["PersonalAPIKeyAuth"]],
    "create_dataset_item": [["PersonalAPIKeyAuth"]],
    "get_dataset_item": [["PersonalAPIKeyAuth"]],
    "update_dataset_item": [["PersonalAPIKeyAuth"]],
    "update_dataset_item_partial": [["PersonalAPIKeyAuth"]],
    "list_datasets": [["PersonalAPIKeyAuth"]],
    "create_dataset": [["PersonalAPIKeyAuth"]],
    "get_dataset": [["PersonalAPIKeyAuth"]],
    "update_dataset": [["PersonalAPIKeyAuth"]],
    "update_dataset_partial": [["PersonalAPIKeyAuth"]],
    "list_early_access_features": [["PersonalAPIKeyAuth"]],
    "create_early_access_feature": [["PersonalAPIKeyAuth"]],
    "get_early_access_feature": [["PersonalAPIKeyAuth"]],
    "update_early_access_feature": [["PersonalAPIKeyAuth"]],
    "update_early_access_feature_partial": [["PersonalAPIKeyAuth"]],
    "delete_early_access_feature": [["PersonalAPIKeyAuth"]],
    "list_elements": [["PersonalAPIKeyAuth"]],
    "create_element": [["PersonalAPIKeyAuth"]],
    "get_element": [["PersonalAPIKeyAuth"]],
    "update_element": [["PersonalAPIKeyAuth"]],
    "update_element_partial": [["PersonalAPIKeyAuth"]],
    "delete_element": [["PersonalAPIKeyAuth"]],
    "get_element_stats": [["PersonalAPIKeyAuth"]],
    "list_element_values": [["PersonalAPIKeyAuth"]],
    "list_endpoints": [["PersonalAPIKeyAuth"]],
    "get_endpoint": [["PersonalAPIKeyAuth"]],
    "update_endpoint": [["PersonalAPIKeyAuth"]],
    "update_endpoint_partial": [["PersonalAPIKeyAuth"]],
    "delete_endpoint": [["PersonalAPIKeyAuth"]],
    "preview_endpoint_materialization": [["PersonalAPIKeyAuth"]],
    "get_endpoint_materialization_status": [["PersonalAPIKeyAuth"]],
    "run_endpoint": [["PersonalAPIKeyAuth"]],
    "run_endpoint_materialized": [["PersonalAPIKeyAuth"]],
    "list_endpoint_versions": [["PersonalAPIKeyAuth"]],
    "list_error_tracking_releases_project": [["PersonalAPIKeyAuth"]],
    "create_error_tracking_release_project": [["PersonalAPIKeyAuth"]],
    "get_error_tracking_release_project": [["PersonalAPIKeyAuth"]],
    "update_error_tracking_release_project": [["PersonalAPIKeyAuth"]],
    "update_error_tracking_release_project_partial": [["PersonalAPIKeyAuth"]],
    "delete_error_tracking_release_project": [["PersonalAPIKeyAuth"]],
    "get_error_tracking_release_by_hash_project": [["PersonalAPIKeyAuth"]],
    "list_error_tracking_symbol_sets_project": [["PersonalAPIKeyAuth"]],
    "get_error_tracking_symbol_set_project": [["PersonalAPIKeyAuth"]],
    "update_error_tracking_symbol_set_project_partial": [["PersonalAPIKeyAuth"]],
    "delete_error_tracking_symbol_set_project": [["PersonalAPIKeyAuth"]],
    "finish_symbol_set_bulk_upload_project": [["PersonalAPIKeyAuth"]],
    "start_symbol_sets_bulk_upload_project": [["PersonalAPIKeyAuth"]],
    "list_event_definitions": [["PersonalAPIKeyAuth"]],
    "create_event_definition": [["PersonalAPIKeyAuth"]],
    "get_event_definition": [["PersonalAPIKeyAuth"]],
    "update_event_definition": [["PersonalAPIKeyAuth"]],
    "update_event_definition_partial": [["PersonalAPIKeyAuth"]],
    "delete_event_definition": [["PersonalAPIKeyAuth"]],
    "get_event_definition_by_name": [["PersonalAPIKeyAuth"]],
    "list_event_definitions_golang": [["PersonalAPIKeyAuth"]],
    "list_event_definitions_python": [["PersonalAPIKeyAuth"]],
    "get_event_definitions_typescript": [["PersonalAPIKeyAuth"]],
    "list_event_schemas": [["PersonalAPIKeyAuth"]],
    "update_event_schema": [["PersonalAPIKeyAuth"]],
    "update_event_schema_partial": [["PersonalAPIKeyAuth"]],
    "delete_event_schema": [["PersonalAPIKeyAuth"]],
    "get_event": [["PersonalAPIKeyAuth"]],
    "list_experiment_holdouts": [["PersonalAPIKeyAuth"]],
    "get_experiment_holdout": [["PersonalAPIKeyAuth"]],
    "update_experiment_holdout": [["PersonalAPIKeyAuth"]],
    "update_experiment_holdout_partial": [["PersonalAPIKeyAuth"]],
    "delete_experiment_holdout": [["PersonalAPIKeyAuth"]],
    "list_experiment_saved_metrics": [["PersonalAPIKeyAuth"]],
    "create_experiment_saved_metric": [["PersonalAPIKeyAuth"]],
    "get_experiment_saved_metric": [["PersonalAPIKeyAuth"]],
    "update_experiment_saved_metric": [["PersonalAPIKeyAuth"]],
    "update_experiment_saved_metric_partial": [["PersonalAPIKeyAuth"]],
    "delete_experiment_saved_metric": [["PersonalAPIKeyAuth"]],
    "list_experiments": [["PersonalAPIKeyAuth"]],
    "create_experiment": [["PersonalAPIKeyAuth"]],
    "get_experiment": [["PersonalAPIKeyAuth"]],
    "update_experiment": [["PersonalAPIKeyAuth"]],
    "update_experiment_partial": [["PersonalAPIKeyAuth"]],
    "mark_experiment_deleted": [["PersonalAPIKeyAuth"]],
    "archive_experiment": [["PersonalAPIKeyAuth"]],
    "create_exposure_cohort_for_experiment": [["PersonalAPIKeyAuth"]],
    "duplicate_experiment": [["PersonalAPIKeyAuth"]],
    "end_experiment": [["PersonalAPIKeyAuth"]],
    "launch_experiment": [["PersonalAPIKeyAuth"]],
    "pause_experiment": [["PersonalAPIKeyAuth"]],
    "reset_experiment_to_draft": [["PersonalAPIKeyAuth"]],
    "resume_experiment": [["PersonalAPIKeyAuth"]],
    "ship_experiment_variant": [["PersonalAPIKeyAuth"]],
    "list_eligible_feature_flags_for_experiments": [["PersonalAPIKeyAuth"]],
    "list_experiments_requiring_flag_implementation": [["PersonalAPIKeyAuth"]],
    "get_experiments_stats": [["PersonalAPIKeyAuth"]],
    "list_exports": [["PersonalAPIKeyAuth"]],
    "create_export": [["PersonalAPIKeyAuth"]],
    "get_export": [["PersonalAPIKeyAuth"]],
    "get_export_content": [["PersonalAPIKeyAuth"]],
    "list_external_data_sources": [["PersonalAPIKeyAuth"]],
    "get_external_data_source": [["PersonalAPIKeyAuth"]],
    "update_external_data_source": [["PersonalAPIKeyAuth"]],
    "update_external_data_source_partial": [["PersonalAPIKeyAuth"]],
    "delete_external_data_source": [["PersonalAPIKeyAuth"]],
    "create_webhook_for_external_data_source": [["PersonalAPIKeyAuth"]],
    "create_external_data_source_delete_webhook": [["PersonalAPIKeyAuth"]],
    "list_external_data_source_jobs": [["PersonalAPIKeyAuth"]],
    "refresh_external_data_source_schemas": [["PersonalAPIKeyAuth"]],
    "reload_external_data_source": [["PersonalAPIKeyAuth"]],
    "update_external_data_source_revenue_analytics_config": [["PersonalAPIKeyAuth"]],
    "create_external_data_source_webhook_inputs": [["PersonalAPIKeyAuth"]],
    "get_external_data_source_webhook_info": [["PersonalAPIKeyAuth"]],
    "list_feature_flags": [["PersonalAPIKeyAuth"]],
    "create_feature_flag": [["PersonalAPIKeyAuth"]],
    "get_feature_flag": [["PersonalAPIKeyAuth"]],
    "update_feature_flag": [["PersonalAPIKeyAuth"]],
    "update_feature_flag_partial": [["PersonalAPIKeyAuth"]],
    "get_feature_flag_activity": [["PersonalAPIKeyAuth"]],
    "list_dependent_flags": [["PersonalAPIKeyAuth"]],
    "get_feature_flag_remote_config": [["PersonalAPIKeyAuth"]],
    "get_feature_flag_status": [["PersonalAPIKeyAuth"]],
    "list_feature_flags_activity": [["PersonalAPIKeyAuth"]],
    "get_feature_flag_evaluation_reasons": [["PersonalAPIKeyAuth"]],
    "get_feature_flags_for_local_evaluation": [["PersonalAPIKeyAuth"]],
    "list_feature_flag_ids_by_filters": [["PersonalAPIKeyAuth"]],
    "list_feature_flags_for_user": [["PersonalAPIKeyAuth"]],
    "evaluate_feature_flag_user_blast_radius": [["PersonalAPIKeyAuth"]],
    "list_file_system_shortcuts": [["PersonalAPIKeyAuth"]],
    "create_file_system_shortcut": [["PersonalAPIKeyAuth"]],
    "get_file_system_shortcut": [["PersonalAPIKeyAuth"]],
    "update_file_system_shortcut": [["PersonalAPIKeyAuth"]],
    "update_file_system_shortcut_partial": [["PersonalAPIKeyAuth"]],
    "delete_file_system_shortcut": [["PersonalAPIKeyAuth"]],
    "list_groups_by_type": [["PersonalAPIKeyAuth"]],
    "create_group": [["PersonalAPIKeyAuth"]],
    "list_user_group_activity": [["PersonalAPIKeyAuth"]],
    "get_group_by_key_and_type": [["PersonalAPIKeyAuth"]],
    "list_group_property_definitions": [["PersonalAPIKeyAuth"]],
    "list_related_groups_for_user": [["PersonalAPIKeyAuth"]],
    "list_group_types": [["PersonalAPIKeyAuth"]],
    "delete_group_type": [["PersonalAPIKeyAuth"]],
    "list_metrics_for_group_type": [["PersonalAPIKeyAuth"]],
    "create_group_type_metric": [["PersonalAPIKeyAuth"]],
    "get_group_type_metric": [["PersonalAPIKeyAuth"]],
    "update_group_type_metric": [["PersonalAPIKeyAuth"]],
    "update_group_type_metric_partial": [["PersonalAPIKeyAuth"]],
    "delete_group_type_metric": [["PersonalAPIKeyAuth"]],
    "get_heatmap_screenshot_content": [["PersonalAPIKeyAuth"]],
    "list_heatmaps": [["PersonalAPIKeyAuth"]],
    "list_hog_flows": [["PersonalAPIKeyAuth"]],
    "create_hog_flow": [["PersonalAPIKeyAuth"]],
    "get_hog_flow": [["PersonalAPIKeyAuth"]],
    "update_hog_flow": [["PersonalAPIKeyAuth"]],
    "update_hog_flow_partial": [["PersonalAPIKeyAuth"]],
    "delete_hog_flow": [["PersonalAPIKeyAuth"]],
    "list_hog_function_templates": [["PersonalAPIKeyAuth"]],
    "get_hog_function_template": [["PersonalAPIKeyAuth"]],
    "list_hog_functions": [["PersonalAPIKeyAuth"]],
    "create_hog_function": [["PersonalAPIKeyAuth"]],
    "get_hog_function": [["PersonalAPIKeyAuth"]],
    "update_hog_function": [["PersonalAPIKeyAuth"]],
    "update_hog_function_partial": [["PersonalAPIKeyAuth"]],
    "test_hog_function_invocation": [["PersonalAPIKeyAuth"]],
    "update_hog_functions_execution_order": [["PersonalAPIKeyAuth"]],
    "list_insight_variables": [["PersonalAPIKeyAuth"]],
    "create_insight_variable": [["PersonalAPIKeyAuth"]],
    "get_insight_variable": [["PersonalAPIKeyAuth"]],
    "update_insight_variable": [["PersonalAPIKeyAuth"]],
    "update_insight_variable_partial": [["PersonalAPIKeyAuth"]],
    "delete_insight_variable": [["PersonalAPIKeyAuth"]],
    "list_insights": [["PersonalAPIKeyAuth"]],
    "create_insight": [["PersonalAPIKeyAuth"]],
    "list_insight_sharing": [["PersonalAPIKeyAuth"]],
    "create_insight_sharing_password": [["PersonalAPIKeyAuth"]],
    "delete_insight_sharing_password": [["PersonalAPIKeyAuth"]],
    "refresh_insight_sharing": [["PersonalAPIKeyAuth"]],
    "list_insight_thresholds": [["PersonalAPIKeyAuth"]],
    "get_insight_threshold": [["PersonalAPIKeyAuth"]],
    "get_insight": [["PersonalAPIKeyAuth"]],
    "update_insight": [["PersonalAPIKeyAuth"]],
    "update_insight_partial": [["PersonalAPIKeyAuth"]],
    "mark_insight_deleted": [["PersonalAPIKeyAuth"]],
    "get_insight_activity": [["PersonalAPIKeyAuth"]],
    "get_project_activity_insights": [["PersonalAPIKeyAuth"]],
    "generate_insight_metadata": [["PersonalAPIKeyAuth"]],
    "list_integrations": [["PersonalAPIKeyAuth"]],
    "get_integration": [["PersonalAPIKeyAuth"]],
    "delete_integration": [["PersonalAPIKeyAuth"]],
    "list_github_branches": [["PersonalAPIKeyAuth"]],
    "list_github_repos_for_integration": [["PersonalAPIKeyAuth"]],
    "list_live_debugger_breakpoints": [["PersonalAPIKeyAuth"]],
    "create_live_debugger_breakpoint": [["PersonalAPIKeyAuth"]],
    "get_live_debugger_breakpoint": [["PersonalAPIKeyAuth"]],
    "update_live_debugger_breakpoint": [["PersonalAPIKeyAuth"]],
    "update_live_debugger_breakpoint_partial": [["PersonalAPIKeyAuth"]],
    "delete_live_debugger_breakpoint": [["PersonalAPIKeyAuth"]],
    "list_active_breakpoints": [["PersonalAPIKeyAuth"]],
    "list_breakpoint_hits": [["PersonalAPIKeyAuth"]],
    "list_logs_attributes": [["PersonalAPIKeyAuth"]],
    "check_project_has_logs": [["PersonalAPIKeyAuth"]],
    "list_notebooks": [["PersonalAPIKeyAuth"]],
    "create_notebook": [["PersonalAPIKeyAuth"]],
    "get_notebook": [["PersonalAPIKeyAuth"]],
    "update_notebook": [["PersonalAPIKeyAuth"]],
    "update_notebook_partial": [["PersonalAPIKeyAuth"]],
    "soft_delete_notebook": [["PersonalAPIKeyAuth"]],
    "get_notebook_activity": [["PersonalAPIKeyAuth"]],
    "list_object_media_previews": [["PersonalAPIKeyAuth"]],
    "get_object_media_preview": [["PersonalAPIKeyAuth"]],
    "update_object_media_preview": [["PersonalAPIKeyAuth"]],
    "update_object_media_preview_partial": [["PersonalAPIKeyAuth"]],
    "delete_object_media_preview": [["PersonalAPIKeyAuth"]],
    "list_persisted_folders": [["PersonalAPIKeyAuth"]],
    "create_persisted_folder": [["PersonalAPIKeyAuth"]],
    "get_persisted_folder": [["PersonalAPIKeyAuth"]],
    "update_persisted_folder": [["PersonalAPIKeyAuth"]],
    "update_persisted_folder_partial": [["PersonalAPIKeyAuth"]],
    "delete_persisted_folder": [["PersonalAPIKeyAuth"]],
    "list_persons": [["PersonalAPIKeyAuth"]],
    "get_person": [["PersonalAPIKeyAuth"]],
    "update_person_properties": [["PersonalAPIKeyAuth"]],
    "get_person_activity": [["PersonalAPIKeyAuth"]],
    "remove_person_property": [["PersonalAPIKeyAuth"]],
    "split_person": [["PersonalAPIKeyAuth"]],
    "set_person_property": [["PersonalAPIKeyAuth"]],
    "list_persons_activity": [["PersonalAPIKeyAuth"]],
    "list_cohorts_for_person": [["PersonalAPIKeyAuth"]],
    "list_person_property_values": [["PersonalAPIKeyAuth"]],
    "list_plugin_config_logs": [["PersonalAPIKeyAuth"]],
    "list_product_tours": [["PersonalAPIKeyAuth"]],
    "create_product_tour": [["PersonalAPIKeyAuth"]],
    "get_product_tour": [["PersonalAPIKeyAuth"]],
    "update_product_tour": [["PersonalAPIKeyAuth"]],
    "update_product_tour_partial": [["PersonalAPIKeyAuth"]],
    "delete_product_tour": [["PersonalAPIKeyAuth"]],
    "delete_product_tour_draft": [["PersonalAPIKeyAuth"]],
    "update_product_tour_draft": [["PersonalAPIKeyAuth"]],
    "get_product_tour_draft_status": [["PersonalAPIKeyAuth"]],
    "publish_product_tour_draft": [["PersonalAPIKeyAuth"]],
    "get_project_secret_api_key": [["PersonalAPIKeyAuth"]],
    "update_project_secret_api_key": [["PersonalAPIKeyAuth"]],
    "update_project_secret_api_key_partial": [["PersonalAPIKeyAuth"]],
    "delete_project_secret_api_key": [["PersonalAPIKeyAuth"]],
    "list_property_definitions": [["PersonalAPIKeyAuth"]],
    "get_property_definition": [["PersonalAPIKeyAuth"]],
    "update_property_definition": [["PersonalAPIKeyAuth"]],
    "update_property_definition_partial": [["PersonalAPIKeyAuth"]],
    "delete_property_definition": [["PersonalAPIKeyAuth"]],
    "query_create": [["PersonalAPIKeyAuth"]],
    "get_query": [["PersonalAPIKeyAuth"]],
    "delete_query": [["PersonalAPIKeyAuth"]],
    "get_sandbox_environment": [["PersonalAPIKeyAuth"]],
    "update_sandbox_environment": [["PersonalAPIKeyAuth"]],
    "delete_sandbox_environment": [["PersonalAPIKeyAuth"]],
    "list_saved_items": [["PersonalAPIKeyAuth"]],
    "create_saved_url": [["PersonalAPIKeyAuth"]],
    "get_saved_item": [["PersonalAPIKeyAuth"]],
    "update_saved_partial": [["PersonalAPIKeyAuth"]],
    "mark_saved_deleted": [["PersonalAPIKeyAuth"]],
    "list_schema_property_groups": [["PersonalAPIKeyAuth"]],
    "create_schema_property_group": [["PersonalAPIKeyAuth"]],
    "get_schema_property_group": [["PersonalAPIKeyAuth"]],
    "update_schema_property_group": [["PersonalAPIKeyAuth"]],
    "update_schema_property_group_partial": [["PersonalAPIKeyAuth"]],
    "delete_schema_property_group": [["PersonalAPIKeyAuth"]],
    "list_session_group_summaries": [["PersonalAPIKeyAuth"]],
    "get_session_group_summary": [["PersonalAPIKeyAuth"]],
    "update_session_group_summary": [["PersonalAPIKeyAuth"]],
    "update_session_group_summary_partial": [["PersonalAPIKeyAuth"]],
    "delete_session_group_summary": [["PersonalAPIKeyAuth"]],
    "list_session_recording_playlists": [["PersonalAPIKeyAuth"]],
    "get_session_recording_playlist": [["PersonalAPIKeyAuth"]],
    "update_session_recording_playlist": [["PersonalAPIKeyAuth"]],
    "update_session_recording_playlist_partial": [["PersonalAPIKeyAuth"]],
    "list_recordings_in_playlist": [["PersonalAPIKeyAuth"]],
    "list_session_recordings": [["PersonalAPIKeyAuth"]],
    "get_session_recording": [["PersonalAPIKeyAuth"]],
    "update_session_recording": [["PersonalAPIKeyAuth"]],
    "update_session_recording_partial": [["PersonalAPIKeyAuth"]],
    "delete_session_recording": [["PersonalAPIKeyAuth"]],
    "list_session_recording_shares": [["PersonalAPIKeyAuth"]],
    "create_session_recording_sharing_password": [["PersonalAPIKeyAuth"]],
    "refresh_session_recording_sharing": [["PersonalAPIKeyAuth"]],
    "list_session_property_definitions": [["PersonalAPIKeyAuth"]],
    "list_signal_source_configs": [["PersonalAPIKeyAuth"]],
    "create_signal_source_config": [["PersonalAPIKeyAuth"]],
    "get_signal_source_config": [["PersonalAPIKeyAuth"]],
    "update_signal_source_config": [["PersonalAPIKeyAuth"]],
    "update_signal_source_config_partial": [["PersonalAPIKeyAuth"]],
    "delete_signal_source_config": [["PersonalAPIKeyAuth"]],
    "create_subscription": [["PersonalAPIKeyAuth"]],
    "get_subscription": [["PersonalAPIKeyAuth"]],
    "update_subscription": [["PersonalAPIKeyAuth"]],
    "update_subscription_partial": [["PersonalAPIKeyAuth"]],
    "soft_delete_subscription": [["PersonalAPIKeyAuth"]],
    "list_surveys": [["PersonalAPIKeyAuth"]],
    "create_survey": [["PersonalAPIKeyAuth"]],
    "get_survey": [["PersonalAPIKeyAuth"]],
    "update_survey": [["PersonalAPIKeyAuth"]],
    "update_survey_partial": [["PersonalAPIKeyAuth"]],
    "delete_survey": [["PersonalAPIKeyAuth"]],
    "get_survey_activity": [["PersonalAPIKeyAuth"]],
    "list_archived_response_uuids_for_survey": [["PersonalAPIKeyAuth"]],
    "archive_survey_response": [["PersonalAPIKeyAuth"]],
    "unarchive_survey_response": [["PersonalAPIKeyAuth"]],
    "get_survey_statistics": [["PersonalAPIKeyAuth"]],
    "create_survey_summary_headline": [["PersonalAPIKeyAuth"]],
    "list_surveys_activity": [["PersonalAPIKeyAuth"]],
    "get_survey_response_counts": [["PersonalAPIKeyAuth"]],
    "get_surveys_stats": [["PersonalAPIKeyAuth"]],
    "list_tasks": [["PersonalAPIKeyAuth"]],
    "create_task": [["PersonalAPIKeyAuth"]],
    "get_task": [["PersonalAPIKeyAuth"]],
    "update_task": [["PersonalAPIKeyAuth"]],
    "update_task_partial": [["PersonalAPIKeyAuth"]],
    "delete_task": [["PersonalAPIKeyAuth"]],
    "create_task_run": [["PersonalAPIKeyAuth"]],
    "list_task_runs": [["PersonalAPIKeyAuth"]],
    "create_task_run_record": [["PersonalAPIKeyAuth"]],
    "get_task_run": [["PersonalAPIKeyAuth"]],
    "update_task_run": [["PersonalAPIKeyAuth"]],
    "append_log_entries_to_task_run": [["PersonalAPIKeyAuth"]],
    "create_artifacts_for_task_run": [["PersonalAPIKeyAuth"]],
    "get_artifact_presigned_url": [["PersonalAPIKeyAuth"]],
    "send_command_to_task_run": [["PersonalAPIKeyAuth"]],
    "get_task_run_sandbox_connection_token": [["PersonalAPIKeyAuth"]],
    "get_task_run_logs": [["PersonalAPIKeyAuth"]],
    "send_run_message_to_slack": [["PersonalAPIKeyAuth"]],
    "get_task_run_session_logs": [["PersonalAPIKeyAuth"]],
    "update_task_run_output": [["PersonalAPIKeyAuth"]],
    "get_task_run_stream": [["PersonalAPIKeyAuth"]],
    "list_visual_review_repositories": [["PersonalAPIKeyAuth"]],
    "create_visual_review_repo": [["PersonalAPIKeyAuth"]],
    "get_visual_review_repo": [["PersonalAPIKeyAuth"]],
    "update_visual_review_repo_settings": [["PersonalAPIKeyAuth"]],
    "list_visual_review_runs": [["PersonalAPIKeyAuth"]],
    "create_visual_review_run": [["PersonalAPIKeyAuth"]],
    "get_visual_review_run": [["PersonalAPIKeyAuth"]],
    "add_snapshots_to_visual_review_run": [["PersonalAPIKeyAuth"]],
    "approve_visual_review_run": [["PersonalAPIKeyAuth"]],
    "complete_visual_review_run": [["PersonalAPIKeyAuth"]],
    "list_visual_review_run_snapshots": [["PersonalAPIKeyAuth"]],
    "get_visual_review_runs_counts": [["PersonalAPIKeyAuth"]],
    "list_warehouse_saved_queries": [["PersonalAPIKeyAuth"]],
    "create_warehouse_saved_query": [["PersonalAPIKeyAuth"]],
    "get_warehouse_saved_query": [["PersonalAPIKeyAuth"]],
    "update_warehouse_saved_query": [["PersonalAPIKeyAuth"]],
    "update_warehouse_saved_query_partial": [["PersonalAPIKeyAuth"]],
    "delete_warehouse_saved_query": [["PersonalAPIKeyAuth"]],
    "get_warehouse_saved_query_activity": [["PersonalAPIKeyAuth"]],
    "create_materialized_view": [["PersonalAPIKeyAuth"]],
    "revert_saved_query_materialization": [["PersonalAPIKeyAuth"]],
    "run_warehouse_saved_query": [["PersonalAPIKeyAuth"]],
    "get_saved_query_run_history": [["PersonalAPIKeyAuth"]],
    "list_warehouse_saved_query_folders": [["PersonalAPIKeyAuth"]],
    "create_warehouse_saved_query_folder": [["PersonalAPIKeyAuth"]],
    "get_warehouse_saved_query_folder": [["PersonalAPIKeyAuth"]],
    "update_warehouse_saved_query_folder": [["PersonalAPIKeyAuth"]],
    "delete_warehouse_saved_query_folder": [["PersonalAPIKeyAuth"]],
    "list_warehouse_tables": [["PersonalAPIKeyAuth"]],
    "create_warehouse_table": [["PersonalAPIKeyAuth"]],
    "get_warehouse_table": [["PersonalAPIKeyAuth"]],
    "update_warehouse_table": [["PersonalAPIKeyAuth"]],
    "update_warehouse_table_partial": [["PersonalAPIKeyAuth"]],
    "delete_warehouse_table": [["PersonalAPIKeyAuth"]],
    "create_warehouse_table_from_file": [["PersonalAPIKeyAuth"]],
    "list_web_experiments": [["PersonalAPIKeyAuth"]],
    "create_web_experiment": [["PersonalAPIKeyAuth"]],
    "get_web_experiment": [["PersonalAPIKeyAuth"]],
    "update_web_experiment": [["PersonalAPIKeyAuth"]],
    "update_web_experiment_partial": [["PersonalAPIKeyAuth"]],
    "delete_web_experiment": [["PersonalAPIKeyAuth"]],
    "list_hog_function_templates_public": [["PersonalAPIKeyAuth"]],
    "list_users": [["PersonalAPIKeyAuth"]],
    "create_user_with_email_verification": [["PersonalAPIKeyAuth"]],
    "create_user_with_email_verification_confirmation": [["PersonalAPIKeyAuth"]]
}
