"""
Authentication module for Apify API MCP server.

Generated: 2026-03-25 22:42:22 UTC
@generated by MCP Blacksmith (https://mcpblacksmith.com)

This module contains:
1. Authentication class implementations (OAuth2)
2. Operation-to-auth requirements mapping (OPERATION_AUTH_MAP)
"""

from __future__ import annotations

import logging
import os

logger = logging.getLogger(__name__)

__all__ = [
    "BearerTokenAuth",
    "APIKeyAuth",
    "OPERATION_AUTH_MAP",
]

# ============================================================================
# Authentication Classes
# ============================================================================

class BearerTokenAuth:
    """
    Bearer token authentication for Apify API.

    Configuration:
        Provide the raw token in the environment variable.
        The authorization scheme prefix is automatically inserted.
    """

    def __init__(self, env_var: str = "BEARER_TOKEN", token_format: str = "Bearer"):
        """Initialize bearer token authentication from environment variable.

        Args:
            env_var: Environment variable name containing the bearer token.
            token_format: Authorization scheme prefix (e.g., 'Bearer').
        """
        self.token_format = token_format
        self.token = os.getenv(env_var, "").strip()

        # Check for empty token
        if not self.token:
            raise ValueError(
                f"{env_var} environment variable not set. "
                "Leave empty in .env to disable Bearer Token auth."
            )

        # Detect common placeholder patterns
        placeholders = ["placeholder", "your-", "example", "change-me", "todo", "sk_test_placeholder"]
        token_lower = self.token.lower()

        if any(p in token_lower for p in placeholders):
            raise ValueError(
                f"Bearer token appears to be a placeholder ({self.token[:20]}...). "
                "Please set a real token or leave empty to disable Bearer Token auth."
            )

    def get_auth_headers(self) -> dict[str, str]:
        """Get authentication headers for API requests."""
        return {
            'Authorization': f'{self.token_format} {self.token}'
        }
class APIKeyAuth:
    """
    API Key authentication for Apify API.

    Supports header, query parameter, and cookie-based API key injection.
    Configure location and parameter name via constructor arguments.
    """

    def __init__(self, env_var: str = "API_KEY", location: str = "header",
                 param_name: str = "Authorization", prefix: str = ""):
        """Initialize API key authentication from environment variable.

        Args:
            env_var: Environment variable name containing the API key.
            location: Where to inject the key - 'header', 'query', or 'cookie'.
            param_name: Name of the header, query parameter, or cookie.
            prefix: Optional prefix before the key value (e.g., 'Bearer').
        """
        self.location = location
        self.param_name = param_name
        self.prefix = prefix
        self.api_key = os.getenv(env_var, "").strip()

        # Check for empty API key
        if not self.api_key:
            raise ValueError(
                f"{env_var} environment variable not set. "
                "Leave empty in .env to disable API Key auth."
            )

        # Detect common placeholder patterns
        placeholders = ["placeholder", "your-", "example", "change-me", "todo", "bot placeholder"]
        api_key_lower = self.api_key.lower()

        if any(p in api_key_lower for p in placeholders):
            raise ValueError(
                f"API key appears to be a placeholder ({self.api_key[:20]}...). "
                "Please set a real API key or leave empty to disable API Key auth."
            )

    def get_auth_headers(self) -> dict[str, str]:
        """Get authentication headers for API requests."""
        if self.location != "header":
            return {}
        if self.param_name == "Authorization":
            prefix = self.prefix + " " if self.prefix else "Bearer "
            return {"Authorization": f"{prefix}{self.api_key}"}
        value = f"{self.prefix} {self.api_key}" if self.prefix else self.api_key
        return {self.param_name: value}

    def get_auth_params(self) -> dict[str, str]:
        """Get authentication query parameters."""
        if self.location != "query":
            return {}
        return {self.param_name: self.api_key}

    def get_auth_cookies(self) -> dict[str, str]:
        """Get authentication cookies."""
        if self.location != "cookie":
            return {}
        return {self.param_name: self.api_key}

# ============================================================================
# Operation Auth Requirements Map
# ============================================================================

"""
Operation-to-authentication requirements mapping.

This dictionary defines which authentication schemes are required for each operation,
using OR/AND relationships (outer list = OR, inner list = AND).
"""
OPERATION_AUTH_MAP: dict[str, list[list[str]]] = {
    "list_actors": [["httpBearer"], ["apiKey"]],
    "create_actor": [["httpBearer"], ["apiKey"]],
    "get_actor": [["httpBearer"], ["apiKey"]],
    "update_actor": [["httpBearer"], ["apiKey"]],
    "delete_actor": [["httpBearer"], ["apiKey"]],
    "list_actor_versions": [["httpBearer"], ["apiKey"]],
    "create_actor_version": [["httpBearer"], ["apiKey"]],
    "get_actor_version": [["httpBearer"], ["apiKey"]],
    "update_actor_version": [["httpBearer"], ["apiKey"]],
    "delete_actor_version": [["httpBearer"], ["apiKey"]],
    "list_actor_version_env_vars": [["httpBearer"], ["apiKey"]],
    "create_actor_env_var": [["httpBearer"], ["apiKey"]],
    "get_actor_env_var": [["httpBearer"], ["apiKey"]],
    "update_actor_env_var": [["httpBearer"], ["apiKey"]],
    "delete_actor_version_env_var": [["httpBearer"], ["apiKey"]],
    "list_actor_webhooks": [["httpBearer"], ["apiKey"]],
    "list_actor_builds": [["httpBearer"], ["apiKey"]],
    "build_actor": [["httpBearer"], ["apiKey"]],
    "get_default_actor_build": [],
    "get_actor_build_openapi_schema_by_actor": [],
    "list_actor_runs_by_actor": [["httpBearer"], ["apiKey"]],
    "run_actor": [["httpBearer"], ["apiKey"]],
    "run_actor_sync_no_input": [["httpBearer"], ["apiKey"]],
    "run_actor_sync": [["httpBearer"], ["apiKey"]],
    "run_actor_sync_get_dataset_items": [["httpBearer"], ["apiKey"]],
    "run_actor_sync_get_dataset_items_with_input": [["httpBearer"], ["apiKey"]],
    "resurrect_actor_run": [["httpBearer"], ["apiKey"]],
    "get_last_actor_run": [["httpBearer"], ["apiKey"]],
    "list_tasks": [["httpBearer"], ["apiKey"]],
    "create_task": [["httpBearer"], ["apiKey"]],
    "get_task": [["httpBearer"], ["apiKey"]],
    "update_task": [["httpBearer"], ["apiKey"]],
    "delete_task": [["httpBearer"], ["apiKey"]],
    "get_task_input": [["httpBearer"], ["apiKey"]],
    "update_task_input": [["httpBearer"], ["apiKey"]],
    "list_task_webhooks": [["httpBearer"], ["apiKey"]],
    "list_task_runs": [["httpBearer"], ["apiKey"]],
    "run_task": [["httpBearer"], ["apiKey"]],
    "run_task_sync_get": [["httpBearer"], ["apiKey"]],
    "run_task_sync": [["httpBearer"], ["apiKey"]],
    "run_task_sync_and_get_dataset_items": [["httpBearer"], ["apiKey"]],
    "run_task_sync_get_dataset_items": [["httpBearer"], ["apiKey"]],
    "get_last_task_run": [["httpBearer"], ["apiKey"]],
    "list_actor_runs": [["httpBearer"], ["apiKey"]],
    "get_actor_run": [["httpBearer"], ["apiKey"]],
    "update_run": [["httpBearer"], ["apiKey"]],
    "delete_actor_run": [["httpBearer"], ["apiKey"]],
    "abort_run": [["httpBearer"], ["apiKey"]],
    "metamorph_run": [["httpBearer"], ["apiKey"]],
    "reboot_actor_run": [["httpBearer"], ["apiKey"]],
    "resurrect_run": [["httpBearer"], ["apiKey"]],
    "charge_run_event": [["httpBearer"], ["apiKey"]],
    "list_builds": [["httpBearer"], ["apiKey"]],
    "get_actor_build": [],
    "delete_build": [["httpBearer"], ["apiKey"]],
    "abort_build": [["httpBearer"], ["apiKey"]],
    "get_build_log": [["httpBearer"], ["apiKey"]],
    "get_actor_build_openapi_schema": [],
    "list_key_value_stores": [["httpBearer"], ["apiKey"]],
    "create_key_value_store": [["httpBearer"], ["apiKey"]],
    "get_key_value_store": [["httpBearer"], ["apiKey"]],
    "update_key_value_store": [["httpBearer"], ["apiKey"]],
    "delete_key_value_store": [["httpBearer"], ["apiKey"]],
    "list_key_value_store_keys": [["httpBearer"], ["apiKey"]],
    "get_key_value_store_record": [["httpBearer"], ["apiKey"]],
    "put_store_record": [["httpBearer"], ["apiKey"]],
    "delete_key_value_store_record": [["httpBearer"], ["apiKey"]],
    "check_key_value_store_record_exists": [["httpBearer"], ["apiKey"]],
    "list_datasets": [["httpBearer"], ["apiKey"]],
    "create_dataset": [["httpBearer"], ["apiKey"]],
    "get_dataset": [["httpBearer"], ["apiKey"]],
    "update_dataset": [["httpBearer"], ["apiKey"]],
    "delete_dataset": [["httpBearer"], ["apiKey"]],
    "list_dataset_items": [["httpBearer"], ["apiKey"]],
    "append_dataset_items": [["httpBearer"], ["apiKey"]],
    "get_dataset_statistics": [["httpBearer"], ["apiKey"]],
    "list_request_queues": [["httpBearer"], ["apiKey"]],
    "create_request_queue": [["httpBearer"], ["apiKey"]],
    "get_request_queue": [["httpBearer"], ["apiKey"]],
    "update_request_queue": [["httpBearer"], ["apiKey"]],
    "delete_request_queue": [["httpBearer"], ["apiKey"]],
    "batch_add_requests": [["httpBearer"], ["apiKey"]],
    "batch_delete_queue_requests": [["httpBearer"], ["apiKey"]],
    "unlock_queue_requests": [["httpBearer"], ["apiKey"]],
    "list_queue_requests": [["httpBearer"], ["apiKey"]],
    "add_queue_request": [["httpBearer"], ["apiKey"]],
    "get_queue_request": [["httpBearer"], ["apiKey"]],
    "update_queue_request": [["httpBearer"], ["apiKey"]],
    "delete_queue_request": [["httpBearer"], ["apiKey"]],
    "get_request_queue_head": [["httpBearer"], ["apiKey"]],
    "lock_queue_head_requests": [["httpBearer"], ["apiKey"]],
    "prolong_request_lock": [["httpBearer"], ["apiKey"]],
    "delete_request_lock": [["httpBearer"], ["apiKey"]],
    "list_webhooks": [["httpBearer"], ["apiKey"]],
    "create_webhook": [["httpBearer"], ["apiKey"]],
    "get_webhook": [["httpBearer"], ["apiKey"]],
    "update_webhook": [["httpBearer"], ["apiKey"]],
    "delete_webhook": [["httpBearer"], ["apiKey"]],
    "test_webhook": [["httpBearer"], ["apiKey"]],
    "list_webhook_dispatches_by_webhook": [["httpBearer"], ["apiKey"]],
    "list_webhook_dispatches": [["httpBearer"], ["apiKey"]],
    "get_webhook_dispatch": [["httpBearer"], ["apiKey"]],
    "list_schedules": [["httpBearer"], ["apiKey"]],
    "create_schedule": [["httpBearer"], ["apiKey"]],
    "get_schedule": [["httpBearer"], ["apiKey"]],
    "update_schedule": [["httpBearer"], ["apiKey"]],
    "delete_schedule": [["httpBearer"], ["apiKey"]],
    "get_schedule_log": [["httpBearer"], ["apiKey"]],
    "list_store_actors": [["httpBearer"], ["apiKey"]],
    "get_run_log": [["httpBearer"], ["apiKey"]],
    "get_user": [["httpBearer"], ["apiKey"]],
    "get_current_user": [["httpBearer"], ["apiKey"]],
    "get_monthly_usage": [["httpBearer"], ["apiKey"]],
    "get_account_limits": [["httpBearer"], ["apiKey"]],
    "update_account_limits": [["httpBearer"], ["apiKey"]]
}
